Repository dotnet/dotnet-api-docs, pull requests merged in 2018-07, with the labels that each got.

#325 Modified path to FieldBuilder example
  xml/System.Reflection.Emit/FieldBuilder.xml
Labels: :construction: Hold for related PR

#335 fix format
  xml/System.Data.Common/DbCommandBuilder.xml
Labels: :file_folder: Repo - dotnet-api-docs, migration-fixes

#331 Expand ITaskItem.GetMetadata return value docs
  xml/Microsoft.Build.Framework/ITaskItem.xml
Labels: :sparkles: 1st-time docs contributor!

#328 Add macOS and Linux information to GetEnvironmentVariable/SetEnvironmentVariable
  xml/System/Environment.xml
Labels: changes-addressed

#268 remove incorrect exception condition
  xml/System.Threading/ReaderWriterLockSlim.xml
Labels: :file_folder: Repo - dotnet-api-docs

#343 fix broken crefs
  xml/Microsoft.JScript/IVsaScriptCodeItem.xml
  xml/Microsoft.JScript/IVsaScriptScope.xml
  xml/Microsoft.JScript/VSAITEMTYPE2.xml
  xml/Microsoft.JScript/VsaItem.xml
  xml/Microsoft.JScript/VsaItems.xml
  xml/System.Activities.Hosting/WorkflowInstance.xml
  xml/System.Activities.Hosting/WorkflowInstanceProxy.xml
  xml/System.Activities.Persistence/PersistenceParticipant.xml
  xml/System.Activities.Statements/Interop.xml
  xml/System.Activities/FaultCallback.xml
  xml/System.IdentityModel.Configuration/X509CertificateValidationElement.xml
  xml/System.IdentityModel.Metadata/IdentityProviderSingleSignOnDescriptor.xml
  xml/System.IdentityModel.Protocols.WSTrust/Participants.xml
  xml/System.IdentityModel.Protocols.WSTrust/ProtectedKey.xml
  xml/System.IdentityModel.Protocols.WSTrust/RequestClaimCollection.xml
  xml/System.IdentityModel.Protocols.WSTrust/RequestedProofToken.xml
  xml/System.IdentityModel.Tokens/Saml2SecurityTokenHandler.xml
  xml/System.IdentityModel.Tokens/Saml2SubjectConfirmationData.xml
  xml/System.IdentityModel.Tokens/SamlSecurityTokenHandler.xml
  xml/System/HashCode.xml
Labels: :file_folder: Repo - dotnet-api-docs

#340 Make HttpWebResponse.Close documentation more clear
  xml/System.Net/HttpWebResponse.xml
Labels: :file_folder: Repo - dotnet-api-docs

#336 Document that a DirectoryNotFoundException is thrown
  xml/System.IO/Directory.xml
Labels: :file_folder: Repo - dotnet-api-docs, :sparkles: 1st-time docs contributor!

#347 export content - Part 1
  xml/Microsoft.VisualC.StlClr/IList`1.xml
  xml/System.CodeDom.Compiler/CodeDomProvider.xml
  xml/System.Collections.Generic/KeyedByTypeCollection`1.xml
  xml/System.Collections.Generic/SynchronizedKeyedCollection`2.xml
  xml/System.Collections.Generic/SynchronizedReadOnlyCollection`1.xml
  xml/System.Configuration.Internal/DelegatingConfigHost.xml
  xml/System.Configuration.Internal/IInternalConfigHost.xml
  xml/System.Configuration/ConfigXmlDocument.xml
  xml/System.Configuration/Configuration.xml
  xml/System.Configuration/ConfigurationElement.xml
  xml/System.Configuration/ConfigurationElementCollection.xml
  xml/System.Configuration/ConfigurationProperty.xml
  xml/System.Configuration/ConfigurationSectionGroup.xml
  xml/System.Configuration/DpapiProtectedConfigurationProvider.xml
  xml/System.Configuration/ProtectedConfigurationProvider.xml
  xml/System.Configuration/ProviderSettingsCollection.xml
  xml/System.Configuration/RsaProtectedConfigurationProvider.xml
  xml/System.Configuration/SectionInformation.xml
  xml/System.Configuration/SettingElement.xml
  xml/System.Configuration/SpecialSettingAttribute.xml
  xml/System.Configuration/ValidatorCallback.xml
  xml/System.Data.Linq/DataContext.xml
  xml/System.Data.SqlClient/SqlConnection.xml
  xml/System.Data.SqlClient/SqlCredential.xml
Labels: migration-fixes

#161 Correct TreeViewItem.IsSelectionActive description
  xml/System.Windows.Controls/TreeViewItem.xml
Labels: :card_file_box: Technology - WPF, :file_folder: Repo - dotnet-api-docs, :sparkles: 1st-time docs contributor!, waiting-on-reviews

#350 replace msdn link
  xml/ns-System.Drawing.xml
Labels: :file_folder: Repo - dotnet-api-docs

#351 export content - Part 2
  xml/System.Diagnostics/CounterSample.xml
  xml/System.Diagnostics/EventLogEntryCollection.xml
  xml/System.Diagnostics/EventLogTraceListener.xml
  xml/System.IO.Compression/DeflateStream.xml
  xml/System.IO.Compression/GZipStream.xml
  xml/System.IO.Ports/SerialPort.xml
  xml/System.IdentityModel.Claims/Claim.xml
  xml/System.IdentityModel.Claims/ClaimSet.xml
  xml/System.IdentityModel.Claims/WindowsClaimSet.xml
  xml/System.IdentityModel.Policy/AuthorizationContext.xml
  xml/System.IdentityModel.Policy/EvaluationContext.xml
  xml/System.IdentityModel.Selectors/CardSpacePolicyElement.xml
  xml/System.IdentityModel.Selectors/CardSpaceSelector.xml
  xml/System.IdentityModel.Selectors/KerberosSecurityTokenProvider.xml
  xml/System.IdentityModel.Selectors/SecurityTokenManager.xml
  xml/System.IdentityModel.Selectors/SecurityTokenProvider.xml
  xml/System.IdentityModel.Selectors/SecurityTokenRequirement.xml
  xml/System.IdentityModel.Tokens/BinaryKeyIdentifierClause.xml
  xml/System.IdentityModel.Tokens/BootstrapContext.xml
  xml/System.IdentityModel.Tokens/EncryptedKeyIdentifierClause.xml
  xml/System.IdentityModel.Tokens/GenericXmlSecurityToken.xml
  xml/System.IdentityModel.Tokens/InMemorySymmetricSecurityKey.xml
  xml/System.IdentityModel.Tokens/KerberosReceiverSecurityToken.xml
  xml/System.IdentityModel.Tokens/KerberosRequestorSecurityToken.xml
  xml/System.IdentityModel.Tokens/LocalIdKeyIdentifierClause.xml
  xml/System.IdentityModel.Tokens/RsaKeyIdentifierClause.xml
  xml/System.IdentityModel.Tokens/RsaSecurityKey.xml
  xml/System.IdentityModel.Tokens/RsaSecurityToken.xml
  xml/System.IdentityModel.Tokens/SamlAction.xml
  xml/System.IdentityModel.Tokens/SamlAdvice.xml
Labels: :file_folder: Repo - dotnet-api-docs, migration-fixes

#354 export content - Part 4
  xml/System.ServiceModel.Security/BinarySecretKeyIdentifierClause.xml
  xml/System.ServiceModel.Security/KeyNameIdentifierClause.xml
  xml/System.ServiceModel.Security/MessagePartSpecification.xml
  xml/System.ServiceModel.Syndication/Atom10ItemFormatter.xml
  xml/System.ServiceModel.Syndication/SyndicationContent.xml
  xml/System.ServiceModel.Syndication/SyndicationItem.xml
  xml/System.ServiceModel.Syndication/XmlSyndicationContent.xml
  xml/System.ServiceModel.Web/WebChannelFactory`1.xml
  xml/System.ServiceModel.Web/WebGetAttribute.xml
  xml/System.ServiceModel.Web/WebInvokeAttribute.xml
  xml/System.ServiceModel.Web/WebOperationContext.xml
  xml/System.ServiceModel/CallbackBehaviorAttribute.xml
  xml/System.ServiceModel/ChannelFactory.xml
  xml/System.ServiceModel/ChannelFactory`1.xml
  xml/System.ServiceModel/ClientBase`1.xml
  xml/System.ServiceModel/DuplexChannelFactory`1.xml
  xml/System.ServiceModel/DuplexClientBase`1.xml
  xml/System.ServiceModel/EndpointIdentity.xml
  xml/System.ServiceModel/FaultException.xml
  xml/System.ServiceModel/OptionalReliableSession.xml
  xml/System.ServiceModel/ReliableSession.xml
  xml/System.ServiceModel/RsaEndpointIdentity.xml
  xml/System.ServiceModel/UriSchemeKeyedCollection.xml
  xml/System.ServiceModel/WebHttpBinding.xml
  xml/System.ServiceModel/X509CertificateEndpointIdentity.xml
  xml/System.Transactions/CommittableTransaction.xml
  xml/System.Transactions/IDtcTransaction.xml
  xml/System.Transactions/IPromotableSinglePhaseNotification.xml
  xml/System.Transactions/ISinglePhaseNotification.xml
  xml/System.Transactions/PreparingEnlistment.xml
  xml/System.Transactions/SubordinateTransaction.xml
  xml/System.Transactions/Transaction.xml
  xml/System.Transactions/TransactionInterop.xml
  xml/System.Transactions/TransactionManager.xml
  xml/System.Transactions/TransactionOptions.xml
  xml/System.Transactions/TransactionScope.xml
  xml/System.Web.Services.Description/ServiceDescription.xml
  xml/System.Web.Services.Discovery/DiscoveryDocument.xml
  xml/System.Web.Services.Discovery/SchemaReference.xml
  xml/System.Web.Services.Protocols/HttpWebClientProtocol.xml
  xml/System.Web.Services.Protocols/LogicalMethodInfo.xml
  xml/System.Web.Services.Protocols/SoapHttpClientProtocol.xml
  xml/System.Web/HttpUtility.xml
  xml/System.Windows.Forms.Integration/PropertyMap.xml
  xml/System/UriTemplateMatchException.xml
Labels: :file_folder: Repo - dotnet-api-docs, migration-fixes

#362 Fixed some broken links
  xml/System.Workflow.Activities/InvokeWebServiceActivity.xml
  xml/System.Workflow.ComponentModel.Compiler/TypeProvider.xml
  xml/System.Workflow.ComponentModel.Compiler/WorkflowCompilerParameters.xml
Labels: :file_folder: Repo - dotnet-api-docs

#365 export content - .NET Framework 4 APIs - Part 1
  xml/Accessibility/CAccPropServicesClass.xml
  xml/Accessibility/IAccPropServices.xml
  xml/Microsoft.Build.Tasks/Csc.xml
  xml/Microsoft.Build.Tasks/Vbc.xml
  xml/System.Activities.Presentation.View/ExpressionTextBox.xml
  xml/System.Activities.Presentation/ActivityDesigner.xml
  xml/System.Activities.Presentation/WorkflowViewElement.xml
  xml/System.ComponentModel.Composition.Hosting/AggregateCatalog.xml
  xml/System.ComponentModel.Composition.Hosting/AssemblyCatalog.xml
  xml/System.ComponentModel.Composition.Hosting/DirectoryCatalog.xml
  xml/System.ComponentModel.Composition.Hosting/TypeCatalog.xml
  xml/System.ComponentModel.DataAnnotations/ValidationException.xml
  xml/System.Data/EntitySqlException.xml
  xml/System.Data/MetadataException.xml
  xml/System.Diagnostics.SymbolStore/SymBinder.xml
  xml/System.Diagnostics.SymbolStore/SymDocument.xml
  xml/System.Diagnostics.SymbolStore/SymDocumentWriter.xml
  xml/System.Diagnostics.SymbolStore/SymMethod.xml
  xml/System.Diagnostics.SymbolStore/SymReader.xml
  xml/System.Diagnostics.SymbolStore/SymScope.xml
  xml/System.Diagnostics.SymbolStore/SymVariable.xml
  xml/System.Diagnostics.SymbolStore/SymWriter.xml
Labels: :file_folder: Repo - dotnet-api-docs

#373 Fix typos
  xml/System.Web.Script.Serialization/JavaScriptSerializer.xml
Labels: :file_folder: Repo - dotnet-api-docs, :sparkles: 1st-time docs contributor!

#372 Fixed description on RSA.ExportParameters
  xml/System.Security.Cryptography/RSA.xml
Labels: :file_folder: Repo - dotnet-api-docs

#367 Adding snippet links for missing person class.
  xml/System.Windows.Controls/TabControl.xml
Labels: :card_file_box: Technology - WPF

#370 migrate missed table from CAPS
  xml/System.Data.SqlClient/SqlConnection.xml
  xml/System.Windows.Forms/Binding.xml
  xml/System.Xml.Xsl/XslTransform.xml
  xml/System/ArgumentNullException.xml
Labels: verify-build-before-merge

#384 Added text lost in migration
  xml/System.Windows/FrameworkElement.xml
Labels: migration-fixes

#391 Restored text lost in migration
  xml/System.Windows.Markup/XamlReader.xml
Labels: migration-fixes

#396 Interlocked class: added missing words
  xml/System.Threading/Interlocked.xml
Labels: :file_folder: Repo - dotnet-api-docs, migration-fixes

#398 Fixed broken Windows Forms links
  xml/System.Windows.Forms.DataVisualization.Charting/AnnotationPositionChangingEventArgs.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Axis.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Chart.xml
  xml/System.Windows.Forms.DataVisualization.Charting/CustomLabelsCollection.xml
  xml/System.Windows.Forms.DataVisualization.Charting/LegendItemsCollection.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Margins.xml
  xml/System.Windows.Forms.DataVisualization.Charting/ViewEventArgs.xml
Labels: :file_folder: Repo - dotnet-api-docs
