Repository dotnet/dotnet-api-docs, pull requests merged in 2018-11, with the labels that each got.

#690 Update Binding.xml
  xml/System.ServiceModel.Channels/Binding.xml
Labels: verify-build-before-merge

#671 Add clarity on strings that end in newline
  xml/System.IO/StringReader.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#670 Updated description for new argumentlist prop
  xml/System.Diagnostics/ProcessStartInfo.xml
Labels: :checkered_flag: Release: .NET Core 2.1, :file_folder: Repo - dotnet-api-docs, P1

#610 Documented MemoryMarshal class
  xml/System.Runtime.InteropServices/MemoryMarshal.xml
Labels: :checkered_flag: Release: .NET Core 2.1

#688 Standardizes Big O notation use of backticks
  xml/System.Collections.Generic/SortedSet`1.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#699 C++ Code snippet should not have `cpp#` as language tag.
  xml/System.Collections.Generic/LinkedList`1.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#701 Remove reference to MSDN in SocketException
  xml/System.Net.Sockets/SocketException.xml
Labels: verify-build-before-merge

#696 Noted deprecated CultureTypes members
  xml/System.Globalization/CultureTypes.xml
Labels: :construction: Hold for related PR

#708 Fix list formatting
  xml/System/Type.xml
Labels: verify-build-before-merge

#707 Fix wrong remark on DistributedIdentifier
  xml/System.Transactions/TransactionInformation.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#711 Fix comment id in RelationshipEndMember.xml
  xml/System.Data.Metadata.Edm/RelationshipEndMember.xml
Labels: verify-build-before-merge

#717 Update Transaction.xml
  xml/System.Transactions/Transaction.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#720 [master]: Clarify what GetOrAdd() returns.
  xml/System.Collections.Concurrent/ConcurrentDictionary`2.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#692 Added KeyPress, KeyDown and KeyUp sample
  xml/System.Windows.Forms/Control.xml
Labels: :construction: Hold for related PR

#684 Clarify explanation of Regex.Unescape https://github.com/dotnet/docs/…
  xml/System.Text.RegularExpressions/Regex.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#683 Add images for MessageBoxIcons
  add/media/messagebox-asterisk.gif
  add/media/messagebox-asterisk.png
  add/media/messagebox-error.gif
  add/media/messagebox-error.png
  add/media/messagebox-exclamation.gif
  add/media/messagebox-exclamation.png
  add/media/messagebox-hand.gif
  add/media/messagebox-hand.png
  add/media/messagebox-information.gif
  add/media/messagebox-information.png
  add/media/messagebox-question.gif
  add/media/messagebox-question.png
  add/media/messagebox-stop.gif
  add/media/messagebox-stop.png
  add/media/messagebox-warning.gif
  add/media/messagebox-warning.png
  xml/System.Windows.Forms/MessageBoxIcon.xml
  xml/System.Windows/MessageBoxImage.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, blocked, enhancement

#732 Fix URI
  xml/System.Security.Claims/ClaimTypes.xml
Labels: verify-build-before-merge

#566 Updated example instructions
  xml/System.Threading.Tasks/TaskScheduler.xml
Labels: verify-build-before-merge

#742 Add missing space
  xml/System.Threading/ThreadAbortException.xml
Labels: :file_folder: Repo - dotnet-api-docs, :sparkles: 1st-time dotnet-api-docs contributor!

#739 Documented String.IndexOf(Char, StringComparison)
  xml/System/String.xml
Labels: verify-build-before-merge

#750 L51129: Deleting extra line break
  xml/System.Text.RegularExpressions/Regex.xml
Labels: :file_folder: Repo - dotnet-api-docs

#676 Update SignedCms.ComputeSignature overloads
  xml/System.Security.Cryptography.Pkcs/SignedCms.xml
Labels: verify-build-before-merge

#747 Fix xref link
  xml/System.Threading/Interlocked.xml
Labels: :file_folder: Repo - dotnet-api-docs, changes-addressed

#752 fix broken link
  xml/System.Data.Objects.DataClasses/ComplexObject.xml
  xml/System/DateTime.xml
  xml/System/Memory`1.xml
Labels: :file_folder: Repo - dotnet-api-docs, verify-build-before-merge

#666 Documented VB optimization with CInt(Fix(value))
  xml/Microsoft.VisualBasic/Conversion.xml
  xml/System/Math.xml
Labels: verify-build-before-merge

#1208 Escape '~' under certain circumstances
  xml/System.Web.DynamicData/DynamicDataRoute.xml
  xml/System.Web.UI.MobileControls/Image.xml
  xml/System.Web.UI.MobileControls/Link.xml
  xml/System.Web.UI.WebControls.WebParts/PersonalizationAdministration.xml
  xml/System.Web.UI.WebControls.WebParts/PersonalizationProvider.xml
  xml/System.Web.UI.WebControls.WebParts/SqlPersonalizationProvider.xml
  xml/System.Web.UI/Control.xml
  xml/System.Web/HttpRequest.xml
  xml/System.Web/HttpRequestBase.xml
  xml/System.Web/HttpRequestWrapper.xml
  xml/System.Web/HttpResponse.xml
  xml/System.Web/VirtualPathUtility.xml
Labels: migration-fixes

#1214 Add missing word to String.IsNullOrEmpty remarks
  xml/System/String.xml
Labels: verify-build-before-merge

#1147 Add Elementary usage for TrimStart
  xml/System/String.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#1223 M32642: Truncated source
  xml/System.Runtime.InteropServices/MemoryMarshal.xml
Labels: changes-addressed, doc-bug, loc

#1220 C50206: Changing format of <remarks>
  xml/System.Windows.Input.Manipulations/Manipulator2D.xml
Labels: changes-addressed, loc, verify-build-before-merge

#1171 C50190: Escaping @
  xml/System.Data.Objects/ObjectParameterCollection.xml
Labels: loc

#1232 add missing content
  xml/System.ServiceModel/ClientBase`1+ChannelBase`1.xml
Labels: P1, migration-fixes
