Repository dotnet/dotnet-api-docs, pull requests merged in 2018-09, with the labels that each got.

#487 Added spaces and changed .NET Framework to .NET
  xml/System/String.xml
Labels: :file_folder: Repo - dotnet-api-docs

#494 minor grammar issue (docs issue #7461)
  xml/System.Windows.Threading/DispatcherTimer.xml
Labels: :file_folder: Repo - dotnet-api-docs, verify-build-before-merge

#491 Math.DivRem: remainder is calculated according to the remainder operator
  xml/System/Math.xml
Labels: verify-build-before-merge

#498 Addressed localization issue
  xml/System.Web.Profile/ProfileBase.xml
Labels: verify-build-before-merge

#510 System.String: Remove superfluous word
  xml/System/String.xml
Labels: verify-build-before-merge

#493 Escaped backslash in MaskedTextBox.Mask table
  xml/System.Windows.Forms/MaskedTextBox.xml
Labels: migration-fixes

#520 Corrected migration issue in CountdownEvent class
  xml/System.Threading/CountdownEvent.xml
Labels: migration-fixes, verify-build-before-merge

#532 Fixed some broken links
  xml/System.Data.Services.Client/DataServiceContext.xml
  xml/System.IdentityModel.Tokens/SamlSecurityTokenHandler.xml
Labels: :file_folder: Repo - dotnet-api-docs

#529 fix typo
  xml/System.Security.Cryptography/ECDiffieHellman.xml
Labels: :file_folder: Repo - dotnet-api-docs

#534 Documented switches for ASP.NET apps
  xml/System/AppContext.xml
Labels: verify-build-before-merge

#536 Decimal.TryParse: Restored content lost in migration
  xml/System/Decimal.xml
Labels: migration-fixes

#546 Update String.xml
  xml/System/String.xml
Labels: :sparkles: 1st-time docs contributor!

#545 Append and Prepend examples
  xml/System.Linq/Enumerable.xml
Labels: :sparkles: 1st-time docs contributor!

#436 Clarify that ProcessStartInfo.UseShellExecute does not mean bash
  xml/System.Diagnostics/ProcessStartInfo.xml
Labels: verify-build-before-merge
