Repository dotnet/dotnet-api-docs, pull requests merged in 2018-10, with the labels that each got.

#567 Fixes dotnet/docs#7926
  xml/System.Reflection/RuntimeReflectionExtensions.xml
Labels: :sparkles: 1st-time docs contributor!

#569 Update HttpResponseBase.SuppressContent to clarify funcationality
  xml/System.Web/HttpResponseBase.xml
Labels: :sparkles: 1st-time docs contributor!

#579 wrong direction :)
  xml/System/String.xml
Labels: :sparkles: 1st-time docs contributor!

#582 added remark to Remove
  xml/System.Configuration/KeyValueConfigurationCollection.xml
Labels: :sparkles: 1st-time docs contributor!

#587 Change default value for IsAsync
  xml/System.Windows.Data/Binding.xml
Labels: :sparkles: 1st-time docs contributor!

#594 Improve description of KeyData
  xml/System.Windows.Forms/PreviewKeyDownEventArgs.xml
Labels: :sparkles: 1st-time docs contributor!

#585 Added link to chart types
  xml/System.Web.UI.DataVisualization.Charting/SeriesChartType.xml
Labels: :sparkles: 1st-time docs contributor!, verify-build-before-merge

#591 Add remarks to XmlException.xml
  xml/System.Xml/XmlException.xml
Labels: :sparkles: 1st-time docs contributor!

#602 Update DataflowBlockOptions.xml
  xml/System.Threading.Tasks.Dataflow/DataflowBlockOptions.xml
Labels: :sparkles: 1st-time docs contributor!

#581 Clarify behavior for special cases of FileExists & DirectoryExists parameters
  xml/Microsoft.VisualBasic.FileIO/FileSystem.xml
Labels: :sparkles: 1st-time docs contributor!

#603 Combine code snippets in WPF example
  xml/System.Windows/FrameworkElement.xml
Labels: :construction: Hold for related PR

#586 Adding remark about changing the KeySize property #5307
  xml/System.Security.Cryptography/AesCryptoServiceProvider.xml
Labels: :file_folder: Repo - dotnet-api-docs, :sparkles: 1st-time docs contributor!, changes-addressed

#600 Add snippet example of listbox scrollintoview
  xml/System.Windows.Controls/ListBox.xml
Labels: :construction: Hold for related PR

#606 Updated System.Buffers namespace for new types
  xml/ns-System.Buffers.xml
Labels: :checkered_flag: Release: .NET Core 2.1

#565 Added dropped text
  xml/System.Threading.Tasks/Task.xml
Labels: verify-build-before-merge

#575 Updating Vector<T> documentation to include table of hardware acceler…
  xml/System.Numerics/Vector`1.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, changes-addressed

#614 Interlocked.CompareExchange: clarify reference equality
  xml/System.Threading/Interlocked.xml
Labels: verify-build-before-merge

#613 correct remark of HttpCookieCollection.Get
  xml/System.Web/HttpCookieCollection.xml
Labels: verify-build-before-merge

#618 Fix typo
  xml/System/String.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#619 Formatting issue on HashCode
  xml/System/HashCode.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#623 add summary for System.Threading.Channels
  xml/ns-System.Threading.Channels.xml
Labels: :file_folder: Repo - dotnet-api-docs

#631 add missing config file excerpt
  xml/System.Configuration/ConfigurationProperty.xml
Labels: :file_folder: Repo - dotnet-api-docs, migration-fixes

#580 Clarified behaviour of ValidateCredentials
  xml/System.DirectoryServices.AccountManagement/PrincipalContext.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#642 Update XmlWriterSettings.xml
  xml/System.Xml/XmlWriterSettings.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#646 Update ConfigurationManager.xml
  xml/System.Configuration/ConfigurationManager.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#645 Fix dotnet/docs#8427 remove out of place remarks
  xml/System.Web/HttpUtility.xml
Labels: verify-build-before-merge

#655 Fix anchor
  xml/System/DateTime.xml
Labels: :file_folder: Repo - dotnet-api-docs

#644 Fix dotnet/docs#8537 Update remark to topic examples
  xml/System.Configuration/RsaProtectedConfigurationProvider.xml
Labels: :file_folder: Repo - dotnet-api-docs, :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#661 recover IntelliSense tags
  xml/Accessibility/CAccPropServicesClass.xml
  xml/Accessibility/IAccPropServer.xml
  xml/Accessibility/IAccPropServices.xml
  xml/Microsoft.Build.BuildEngine/BuildItemGroup.xml
  xml/Microsoft.Build.BuildEngine/BuildItemGroupCollection.xml
  xml/Microsoft.Build.BuildEngine/BuildPropertyGroup.xml
  xml/Microsoft.Build.BuildEngine/BuildPropertyGroupCollection.xml
  xml/Microsoft.Build.BuildEngine/BuildTask.xml
  xml/Microsoft.Build.BuildEngine/ConsoleLogger.xml
  xml/Microsoft.Build.BuildEngine/Engine.xml
  xml/Microsoft.Build.BuildEngine/ImportCollection.xml
  xml/Microsoft.Build.BuildEngine/InternalLoggerException.xml
  xml/Microsoft.Build.BuildEngine/InvalidProjectFileException.xml
  xml/Microsoft.Build.BuildEngine/InvalidToolsetDefinitionException.xml
  xml/Microsoft.Build.BuildEngine/Project.xml
  xml/Microsoft.Build.BuildEngine/TargetCollection.xml
  xml/Microsoft.Build.BuildEngine/ToolsetCollection.xml
  xml/Microsoft.Build.BuildEngine/UsingTaskCollection.xml
  xml/Microsoft.Build.Framework/LoggerException.xml
  xml/Microsoft.Build.Tasks.Deployment.ManifestUtilities/SecurityUtilities.xml
  xml/System.Diagnostics.SymbolStore/SymWriter.xml
Labels: :file_folder: Repo - dotnet-api-docs, migration-fixes

#663 fix broken links
  xml/System.Windows/FontStretch.xml
  xml/System.Windows/FontStretches.xml
  xml/System.Windows/FontWeight.xml
Labels: :file_folder: Repo - dotnet-api-docs

#658 Broken link corrected
  xml/System.Windows/FontWeights.xml
Labels: :file_folder: Repo - dotnet-api-docs, :sparkles: 1st-time dotnet-api-docs contributor!

#674 Update DataType.xml
  xml/System.ComponentModel.DataAnnotations/DataType.xml
Labels: migration-fixes

#668 Add NullReferenceException to OpenTextFileWriter
  xml/Microsoft.VisualBasic.FileIO/FileSystem.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#680 Update SendKeys.xml
  xml/System.Windows.Forms/SendKeys.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#678 Update Task.xml
  xml/System.Threading.Tasks/Task.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#686 Remove regular expression as validation method
  xml/System.ComponentModel.DataAnnotations/PhoneAttribute.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#584 Added examples for each overload
  xml/System.Net.Http.Headers/AuthenticationHeaderValue.xml
Labels: changes-addressed
