Repository dotnet/dotnet-api-docs, pull requests merged in 2018-06, with the labels that each got.

#235 Restored lost text
  xml/ns-System.Xml.xml
Labels: :file_folder: Repo - dotnet-api-docs, verify-build-before-merge

#238 Updated broken link to contributing guide
  CONTRIBUTING.md
Labels: :sparkles: 1st-time docs contributor!

#239 Updated Example Text
  xml/System.Diagnostics/TraceListenerCollection.xml
Labels: :sparkles: 1st-time docs contributor!

#233 HashCode documentation
  xml/System/HashCode.xml
Labels: verify-build-before-merge

#250 fix a few of the cref warnings
  xml/Microsoft.Build.Framework/BuildErrorEventArgs.xml
  xml/Microsoft.Build.Framework/BuildStatusEventArgs.xml
  xml/Microsoft.Build.Framework/BuildWarningEventArgs.xml
  xml/Microsoft.Build.Framework/IGeneratedTask.xml
  xml/Microsoft.Build.Tasks.Xaml/PropertyRelation.xml
  xml/Microsoft.JScript.Vsa/BaseVsaSite.xml
  xml/Microsoft.JScript.Vsa/IJSVsaError.xml
  xml/Microsoft.JScript.Vsa/JSVsaError.xml
  xml/Microsoft.JScript.Vsa/VsaEngine.xml
  xml/Microsoft.JScript/IEngine2.xml
  xml/Microsoft.JScript/IVsaScriptCodeItem.xml
  xml/Microsoft.JScript/IVsaScriptScope.xml
  xml/Microsoft.JScript/JScriptException.xml
  xml/Microsoft.JScript/VSAITEMTYPE2.xml
  xml/Microsoft.JScript/VsaItem.xml
  xml/Microsoft.JScript/VsaItems.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/FileListBoxArray.xml
  xml/System.Activities.Core.Presentation.Factories/ParallelForEachWithBodyFactory`1.xml
  xml/System.Activities.DurableInstancing/CreateWorkflowOwnerCommand.xml
  xml/System.Activities.DurableInstancing/SaveWorkflowCommand.xml
  xml/System.Activities.Expressions/And`3.xml
  xml/System.Activities.Expressions/GreaterThan`3.xml
  xml/System.Activities.Expressions/LessThanOrEqual`3.xml
  xml/System.Activities.Hosting/WorkflowInstance.xml
  xml/System.Activities.Presentation.PropertyEditing/EditModeSwitchButton.xml
  xml/System.Activities.Presentation.PropertyEditing/PropertyContainerEditMode.xml
  xml/System.Activities.Presentation.PropertyEditing/PropertyEntry.xml
  xml/System.Activities.Presentation.PropertyEditing/PropertyValueEditorCommands.xml
  xml/System.Activities/ActivityBuilder`1.xml
Labels: :file_folder: Repo - dotnet-api-docs

#246 Updated description for PublicKey.Key property
  xml/System.Security.Cryptography.X509Certificates/PublicKey.xml
Labels: :file_folder: Repo - dotnet-api-docs

#254 cref link fixes
  xml/Microsoft.JScript.Vsa/BaseVsaSite.xml
  xml/Microsoft.JScript.Vsa/IJSVsaError.xml
  xml/Microsoft.JScript.Vsa/VsaEngine.xml
  xml/Microsoft.JScript/IEngine2.xml
  xml/Microsoft.JScript/VsaItem.xml
  xml/System.Activities.Presentation.PropertyEditing/CategoryEntry.xml
  xml/System.Activities.Presentation.PropertyEditing/PropertyEntryCollection.xml
  xml/System.Activities.Presentation.PropertyEditing/PropertyValue.xml
  xml/System.Activities.Presentation.PropertyEditing/PropertyValueCollection.xml
  xml/System.Activities.Presentation.Toolbox/ToolboxItemWrapper.xml
  xml/System.Activities.Presentation.View/TypeResolvingOptions.xml
  xml/System.Activities.Presentation/ServiceManager.xml
  xml/System.Activities.Presentation/UndoUnitEventArgs.xml
  xml/System.Composition.Hosting/CompositionFailedException.xml
  xml/System.Data.EntityClient/EntityConnection.xml
  xml/System.Data.Metadata.Edm/MetadataWorkspace.xml
  xml/System.Data.Objects/DbUpdatableDataRecord.xml
  xml/System.Data.Objects/ObjectContext.xml
  xml/System.Data.OleDb/OleDbParameterCollection.xml
  xml/System.Data.SqlTypes/SqlBinary.xml
  xml/System.Data/DataRow.xml
  xml/System.Data/DataSet.xml
  xml/System.Data/InternalDataCollectionBase.xml
  xml/System.Device.Location/CivicAddress.xml
  xml/System.Diagnostics/PresentationTraceSources.xml
Labels: :file_folder: Repo - dotnet-api-docs

#252 remove spaces
  xml/System.DirectoryServices.Protocols/CompareRequest.xml
  xml/System.Management/ComparisonSettings.xml
  xml/System.Management/ManagementEventArgs.xml
  xml/System.Management/ManagementNamedValueCollection.xml
  xml/System.Management/ManagementObjectSearcher.xml
  xml/System.Management/PutOptions.xml
  xml/System.Management/QualifierData.xml
  xml/System.Windows.Shell/WindowChrome.xml
  xml/System/Array.xml
  xml/System/ValueTuple`1.xml
  xml/System/ValueTuple`2.xml
  xml/System/ValueTuple`3.xml
  xml/System/ValueTuple`4.xml
  xml/System/ValueTuple`5.xml
  xml/System/ValueTuple`6.xml
  xml/System/ValueTuple`7.xml
Labels: :file_folder: Repo - dotnet-api-docs

#251 change msdn link to docs
  xml/System/String.xml
Labels: :file_folder: Repo - dotnet-api-docs

#259 update title
  xml/Microsoft.VisualBasic.Compatibility.VB6/Support.xml
Labels: :file_folder: Repo - dotnet-api-docs

#270 added CoC
  README.md
Labels: :file_folder: Repo - dotnet-api-docs

#269 Fixed bad link introduced in migration
  xml/System.Windows.Interop/HwndHost.xml
Labels: :file_folder: Repo - dotnet-api-docs

#264 Update InputEventArgs.xml
  xml/System.Windows.Input/InputEventArgs.xml
Labels: :sparkles: 1st-time docs contributor!

#271 fixed broken link
  xml/System.DirectoryServices.AccountManagement/UserPrincipal.xml
Labels: :file_folder: Repo - dotnet-api-docs

#274 Adds example for GetSection parameter when working beyond root sections.
  xml/System.Configuration/ConfigurationManager.xml
Labels: :sparkles: 1st-time docs contributor!, verify-build-before-merge

#267 Removed example of obsolete member
  xml/System.Net/IPAddress.xml
Labels: :file_folder: Repo - dotnet-api-docs

#273 fixed broken cref links
  xml/System.Activities.DurableInstancing/InstanceLockedExceptionAction.xml
  xml/System.Activities.Presentation.Hosting/ImportedNamespaceContextItem.xml
  xml/System.Activities.Presentation.Model/ModelMemberCollection`2.xml
  xml/System.Activities.Presentation.Model/ModelProperty.xml
  xml/System.Activities.Presentation.PropertyEditing/CategoryEditor.xml
  xml/System.Activities.Presentation.PropertyEditing/DialogPropertyValueEditor.xml
  xml/System.Activities.Presentation.PropertyEditing/EditModeSwitchButton.xml
  xml/System.Activities.Presentation.PropertyEditing/PropertyEntry.xml
  xml/System.Activities.Presentation.PropertyEditing/PropertyValueEditor.xml
  xml/System.Activities.Presentation.Services/ViewService.xml
  xml/System.Activities.Presentation.Toolbox/ToolboxCategory.xml
  xml/System.Activities.Presentation.Toolbox/ToolboxCategoryItems.xml
  xml/System.Activities.Presentation.Toolbox/ToolboxControl.xml
  xml/System.Activities.Presentation.View/DesignerView.xml
  xml/System.Activities.Presentation/ActivityDesignerOptionsAttribute.xml
  xml/System.Activities.Presentation/UndoUnitEventArgs.xml
  xml/System.Activities.Presentation/WorkflowDesigner.xml
  xml/System.Activities.Statements/CompensableActivity.xml
  xml/System.Activities.Statements/DoWhile.xml
  xml/System.Activities.Statements/Flowchart.xml
  xml/System.Activities/NativeActivity.xml
  xml/System.Activities/NativeActivity`1.xml
  xml/System.Data.Objects/ObjectStateManager.xml
  xml/System.Data.Odbc/OdbcParameterCollection.xml
  xml/System.Data.OleDb/OleDbParameterCollection.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalSearchResult`1.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalValueCollection`1.xml
  xml/System.ServiceModel.Channels/ChannelBase.xml
  xml/System.ServiceModel.Channels/ChannelManagerBase.xml
  xml/System.ServiceModel/ChannelFactory.xml
Labels: :file_folder: Repo - dotnet-api-docs

#276 Adding link to best practices doc, as per bug 533984
  xml/System.Net.Security/SslStream.xml
Labels: :file_folder: Repo - dotnet-api-docs

#286 Regex.CompileToAssembly throws PlatformNotSupportedException
  xml/System.Text.RegularExpressions/Regex.xml
Labels: verify-build-before-merge

#266 Removed unsupported configuration attributes
  xml/System.Net.Configuration/ProxyElement.xml
Labels: waiting-on-reviews

#300 Added Unix to description in Environment.UserName
  xml/System/Environment.xml
Labels: :sparkles: 1st-time docs contributor!

#299 Fully qualified xrefs
  xml/System.Globalization/JapaneseLunisolarCalendar.xml
Labels: :file_folder: Repo - dotnet-api-docs

#304 Fixed formatting
  xml/System/TypeInitializationException.xml
Labels: :file_folder: Repo - dotnet-api-docs, migration-fixes

#312 Corrected links to downloadable samples
  xml/System/DateTime.xml
  xml/System/String.xml
Labels: :file_folder: Repo - dotnet-api-docs, verify-build-before-merge

#319 Corrected typos
  xml/System.ComponentModel.DataAnnotations.Schema/ForeignKeyAttribute.xml
Labels: :file_folder: Repo - dotnet-api-docs, bug, verify-build-before-merge

#309 fixed broken crefs
  xml/System.Activities.Presentation.Debug/DebuggerService.xml
  xml/System.Activities.Presentation.PropertyEditing/CategoryEntry.xml
  xml/System.Activities.Presentation.PropertyEditing/EditModeSwitchButton.xml
  xml/System.Activities.Presentation.PropertyEditing/PropertyFilter.xml
  xml/System.Activities.Presentation.Toolbox/ToolboxControl.xml
  xml/System.Activities.Presentation/EditingContext.xml
  xml/System.Activities.Statements/DoWhile.xml
  xml/System.Activities/RuntimeTransactionHandle.xml
  xml/System.DirectoryServices.AccountManagement/ComputerPrincipal.xml
  xml/System.Management.Instrumentation/ManagementBindAttribute.xml
  xml/System.Management.Instrumentation/ManagementCommitAttribute.xml
  xml/System.Management.Instrumentation/ManagementConfigurationAttribute.xml
  xml/System.Management.Instrumentation/ManagementCreateAttribute.xml
  xml/System.Management.Instrumentation/ManagementEntityAttribute.xml
  xml/System.Management.Instrumentation/ManagementEnumeratorAttribute.xml
  xml/System.Management.Instrumentation/ManagementKeyAttribute.xml
  xml/System.Management.Instrumentation/ManagementMemberAttribute.xml
  xml/System.Management.Instrumentation/ManagementNameAttribute.xml
  xml/System.Management.Instrumentation/ManagementNewInstanceAttribute.xml
  xml/System.Management.Instrumentation/ManagementProbeAttribute.xml
  xml/System.Management.Instrumentation/ManagementReferenceAttribute.xml
  xml/System.Management.Instrumentation/ManagementRemoveAttribute.xml
  xml/System.Management.Instrumentation/ManagementTaskAttribute.xml
  xml/System.Management.Instrumentation/WmiConfigurationAttribute.xml
  xml/System.Net.Http/HttpClientHandler.xml
  xml/System.Net.Sockets/SocketReceiveMessageFromResult.xml
  xml/System.Net.Sockets/SocketType.xml
  xml/System.Web.Services.Description/ProtocolReflector.xml
  xml/System.Web.Services.Protocols/SoapException.xml
  xml/System.Workflow.Activities.Rules.Design/RuleSetDialog.xml
  xml/System.Workflow.Activities/OperationInfoBase.xml
  xml/System.Workflow.ComponentModel.Design/ActivityDesigner.xml
  xml/System.Workflow.ComponentModel.Design/ConnectorEventArgs.xml
  xml/System.Workflow.ComponentModel.Design/ConnectorEventHandler.xml
  xml/System/UriTemplate.xml
Labels: :file_folder: Repo - dotnet-api-docs
