Repository dotnet/dotnet-api-docs, pull requests merged in 2018-12, with the labels that each got.

#1261 Update OpCodes.xml
  xml/System.Reflection.Emit/OpCodes.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#1248 Documented 2 new APIs for .NET Core 2.2
  xml/System.Diagnostics.Tracing/EventWrittenEventArgs.xml
Labels: P1, new-content

#1285 Fixed 2 typos (scenarious --> scenario)
  xml/System/GC.xml
  xml/System/Span`1.xml
Labels: verify-build-before-merge

#1297 Update FileStream example
  xml/System/NotSupportedException.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#1311 IntelliSense fixes - PR 1/?
  xml/Microsoft.Aspnet.Snapin/IExtendPropertySheet2.xml
  xml/Microsoft.Build.Evaluation/Toolset.xml
  xml/Microsoft.Build.Utilities/ToolLocationHelper.xml
  xml/Microsoft.VisualBasic.ApplicationServices/AssemblyInfo.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/CONNECTDATA.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/DBBINDING.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/DBCOLUMNINFO.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/DBID.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/DBPROPIDSET.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/UGUID.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/UNAME.xml
  xml/Microsoft.VisualBasic.CompilerServices/ObjectType.xml
  xml/Microsoft.VisualBasic.CompilerServices/Operators.xml
  xml/Microsoft.VisualBasic.CompilerServices/ProjectData.xml
  xml/Microsoft.VisualBasic/Collection.xml
  xml/Microsoft.VisualBasic/DateAndTime.xml
  xml/Microsoft.VisualBasic/ErrObject.xml
  xml/Microsoft.VisualBasic/FileSystem.xml
  xml/Microsoft.VisualBasic/Financial.xml
  xml/Microsoft.VisualBasic/Information.xml
  xml/Microsoft.VisualBasic/Interaction.xml
  xml/Microsoft.VisualBasic/OpenMode.xml
  xml/Microsoft.VisualBasic/OpenShare.xml
  xml/Microsoft.VisualBasic/Strings.xml
  xml/Microsoft.VisualC/DecoratedNameAttribute.xml
  xml/Microsoft.Win32/RegistryKey.xml
  xml/System.Activities.Hosting/WorkflowInstance.xml
  xml/System.Activities.Presentation.Hosting/CommandValues.xml
  xml/System.Activities.Presentation.Model/ModelItemCollection.xml
  xml/System.Activities.Presentation.Model/ModelItemDictionary.xml
  xml/System.Activities.Presentation.PropertyEditing/CategoryEntry.xml
  xml/System.Activities.Presentation.PropertyEditing/PropertyValueExceptionEventArgs.xml
  xml/System.AddIn.Contract.Collections/IArrayContract`1.xml
  xml/System.AddIn.Contract.Collections/ICollectionContract`1.xml
  xml/System.AddIn.Contract.Collections/IEnumerableContract`1.xml
  xml/System.AddIn.Contract.Collections/IEnumeratorContract`1.xml
  xml/System.AddIn.Contract.Collections/IListContract`1.xml
  xml/System.AddIn.Pipeline/CollectionAdapters.xml
  xml/System.Collections.Concurrent/ConcurrentDictionary`2.xml
  xml/System/AppDomain.xml
  xml/System/AppDomainSetup.xml
  xml/System/Array.xml
  xml/System/Delegate.xml
  xml/System/FormattableString.xml
  xml/System/GC.xml
  xml/System/IndexOutOfRangeException.xml
  xml/System/Random.xml
  xml/System/String.xml
  xml/System/TimeZoneInfo.xml
  xml/System/Type.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8

#1312 intellisense fixes - PR 2/?
  xml/System.CodeDom.Compiler/CompilerInfo.xml
  xml/System.Collections.Generic/List`1.xml
  xml/System.Collections.Immutable/ImmutableList.xml
  xml/System.Collections.Immutable/ImmutableList`1+Builder.xml
  xml/System.Collections.Immutable/ImmutableList`1.xml
  xml/System.Collections.ObjectModel/KeyedCollection`2.xml
  xml/System.ComponentModel.Composition.Registration/PartBuilder`1.xml
  xml/System.ComponentModel.Design.Serialization/CodeDomSerializerBase.xml
  xml/System.ComponentModel.Design/DesignerActionPropertyItem.xml
  xml/System.ComponentModel.Design/DesignerCommandSet.xml
  xml/System.ComponentModel.Design/IComponentInitializer.xml
  xml/System.ComponentModel/LookupBindingPropertiesAttribute.xml
  xml/System.ComponentModel/NestedContainer.xml
  xml/System.Configuration.Install/InstallerCollection.xml
  xml/System.Configuration/ApplicationScopedSettingAttribute.xml
  xml/System.Configuration/ConfigurationBuilder.xml
  xml/System.Configuration/ConfigurationElement.xml
  xml/System.Configuration/ConfigurationElementCollection.xml
  xml/System.Configuration/ConfigurationPermission.xml
  xml/System.Configuration/ConnectionStringSettingsCollection.xml
  xml/System.Configuration/DefaultSettingValueAttribute.xml
  xml/System.Configuration/PropertyInformationCollection.xml
  xml/System.Configuration/SettingsPropertyValue.xml
  xml/System.Configuration/SettingsProvider.xml
  xml/System.Configuration/SettingsProviderAttribute.xml
  xml/System.Configuration/UserScopedSettingAttribute.xml
  xml/System.Data.Odbc/OdbcType.xml
  xml/System.Data.OleDb/OleDbConnection.xml
  xml/System.Data.OleDb/OleDbSchemaGuid.xml
  xml/System.Data.Services.Client/DataServiceContext.xml
  xml/System.Data.SqlClient/SqlBulkCopyColumnMapping.xml
  xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml
  xml/System.Data.SqlClient/SqlConnection.xml
  xml/System.Data/DataColumn.xml
  xml/System.Data/DataRowExtensions.xml
  xml/System.Data/EnumerableRowCollectionExtensions.xml
  xml/System.Device.Location/GeoCoordinateWatcher.xml
  xml/System.Diagnostics/EventLog.xml
  xml/System.Diagnostics/EventSchemaTraceListener.xml
  xml/System.Diagnostics/PerformanceCounterType.xml
  xml/System.DirectoryServices.AccountManagement/AdvancedFilters.xml
  xml/System.DirectoryServices.AccountManagement/AuthenticablePrincipal.xml
  xml/System.DirectoryServices.AccountManagement/ComputerPrincipal.xml
  xml/System.DirectoryServices.AccountManagement/ContextOptions.xml
  xml/System.DirectoryServices.AccountManagement/ContextType.xml
  xml/System.DirectoryServices.AccountManagement/DirectoryObjectClassAttribute.xml
  xml/System.DirectoryServices.AccountManagement/DirectoryPropertyAttribute.xml
  xml/System.DirectoryServices.AccountManagement/DirectoryRdnPrefixAttribute.xml
  xml/System.DirectoryServices.AccountManagement/GroupPrincipal.xml
  xml/System.DirectoryServices.AccountManagement/GroupScope.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8

#1313 IntelliSense fixes - PR 3/?
  xml/System.Reflection.Emit/TypeBuilder.xml
  xml/System.Reflection/MemberInfo.xml
  xml/System.Reflection/MethodInfo.xml
  xml/System.Reflection/PropertyInfo.xml
  xml/System.Reflection/StrongNameKeyPair.xml
  xml/System.Runtime.CompilerServices/ReadOnlyCollectionBuilder`1.xml
  xml/System.Runtime.DurableInstancing/InstancePersistenceContext.xml
  xml/System.Runtime.InteropServices/_ConstructorInfo.xml
  xml/System.Runtime.InteropServices/_MemberInfo.xml
  xml/System.Runtime.InteropServices/_MethodBase.xml
  xml/System.Runtime.InteropServices/_MethodInfo.xml
  xml/System.Security.Cryptography.Xml/SignedXml.xml
  xml/System.Security.Cryptography/AesManaged.xml
  xml/System.Security.Cryptography/DSA.xml
  xml/System.Security.Cryptography/ECDsa.xml
  xml/System.Security.Cryptography/ICspAsymmetricAlgorithm.xml
  xml/System.Security.Cryptography/RSA.xml
  xml/System.Security.Permissions/KeyContainerPermissionAccessEntry.xml
  xml/System.Security.Permissions/KeyContainerPermissionAccessEntryCollection.xml
  xml/System.ServiceModel.Channels/ContextBindingElement.xml
  xml/System.ServiceModel.Configuration/StandardEndpointCollectionElement`2.xml
  xml/System.ServiceModel.Syndication/SyndicationItem.xml
  xml/System.ServiceModel/HttpClientCredentialType.xml
  xml/System.ServiceModel/HttpProxyCredentialType.xml
  xml/System.ServiceModel/MessageHeaderAttribute.xml
  xml/System.Speech.Recognition.SrgsGrammar/SrgsToken.xml
  xml/System.Text.RegularExpressions/Regex.xml
  xml/System.Text.RegularExpressions/RegexOptions.xml
  xml/System.Threading/AbandonedMutexException.xml
  xml/System.Threading/AutoResetEvent.xml
  xml/System.Threading/Monitor.xml
  xml/System.Threading/WaitHandle.xml
  xml/System.Web.Configuration/HttpCapabilitiesBase.xml
  xml/System.Web.Configuration/PagesSection.xml
  xml/System.Web.Configuration/ProcessModelSection.xml
  xml/System.Web.Configuration/TagPrefixCollection.xml
  xml/System.Web.Configuration/TagPrefixInfo.xml
  xml/System.Web.Configuration/WebPartsPersonalization.xml
  xml/System.Web.Configuration/WebPartsSection.xml
  xml/System.Web.Hosting/ApplicationManager.xml
  xml/System.Web.ModelBinding/ModelMetadata.xml
  xml/System.Web.UI/Control.xml
  xml/System.Web.UI/DesignerDataBoundLiteralControl.xml
  xml/System.Web.UI/Html32TextWriter.xml
  xml/System.Web.UI/UpdatePanel.xml
  xml/System.Web/HttpBrowserCapabilitiesBase.xml
  xml/System.Web/HttpBrowserCapabilitiesWrapper.xml
  xml/System.Web/HttpResponse.xml
  xml/System.Web/ParserErrorCollection.xml
  xml/System.Web/SiteMap.xml
  xml/System.Web/SiteMapProvider.xml
  xml/System.Web/StaticSiteMapProvider.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8

#1314 IntelliSense fixes - PR 4/?
  xml/System.DirectoryServices.AccountManagement/IdentityType.xml
  xml/System.DirectoryServices.AccountManagement/MatchType.xml
  xml/System.DirectoryServices.AccountManagement/MultipleMatchesException.xml
  xml/System.DirectoryServices.AccountManagement/NoMatchingPrincipalException.xml
  xml/System.DirectoryServices.AccountManagement/PasswordException.xml
  xml/System.DirectoryServices.AccountManagement/Principal.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalCollection.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalContext.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalException.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalExistsException.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalOperationException.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalSearchResult`1.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalSearcher.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalServerDownException.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalValueCollection`1.xml
  xml/System.DirectoryServices.AccountManagement/UserPrincipal.xml
  xml/System.Drawing.Drawing2D/Matrix.xml
  xml/System.Drawing/Color.xml
  xml/System.Drawing/Pen.xml
  xml/System.Dynamic/ExpandoObject.xml
  xml/System.EnterpriseServices/BYOT.xml
  xml/System.Globalization/CompareInfo.xml
  xml/System.Globalization/CultureAndRegionInfoBuilder.xml
  xml/System.Globalization/RegionInfo.xml
  xml/System.IO.Packaging/PackWebRequest.xml
  xml/System.IO.Packaging/Package.xml
  xml/System.IO.Packaging/PackageDigitalSignature.xml
  xml/System.IO.Packaging/PackageDigitalSignatureManager.xml
  xml/System.IO.Packaging/PackageRelationship.xml
  xml/System.IO.Packaging/PackageRelationshipCollection.xml
  xml/System.IO.Packaging/ZipPackage.xml
  xml/System.IO.Ports/Parity.xml
  xml/System.IO.Ports/SerialPort.xml
  xml/System.IdentityModel.Protocols.WSTrust/EndpointReference.xml
  xml/System.IdentityModel.Services/WSFederationMessage.xml
  xml/System.IdentityModel.Tokens/Saml2SecurityTokenHandler.xml
  xml/System.Linq.Expressions/DynamicExpression.xml
  xml/System.Linq/Enumerable.xml
  xml/System.Linq/Queryable.xml
  xml/System.Messaging/AcknowledgeTypes.xml
  xml/System.Messaging/Message.xml
  xml/System.Messaging/MessageQueueException.xml
  xml/System.Net.PeerToPeer.Collaboration/PeerCollaboration.xml
  xml/System.Net.PeerToPeer.Collaboration/PeerEndPoint.xml
  xml/System.Net.Sockets/Socket.xml
  xml/System.Net/AuthenticationSchemes.xml
  xml/System.Net/HttpListenerResponse.xml
  xml/System.Reflection/ConstructorInfo.xml
  xml/System.Reflection/EventInfo.xml
  xml/System.Reflection/FieldInfo.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8

#1315 IntelliSense fixes - PR 5/?
  xml/System.Windows.Controls.Primitives/TextBoxBase.xml
  xml/System.Windows.Controls.Primitives/Track.xml
  xml/System.Windows.Controls/Canvas.xml
  xml/System.Windows.Controls/ComboBox.xml
  xml/System.Windows.Controls/ContextMenu.xml
  xml/System.Windows.Controls/ContextMenuService.xml
  xml/System.Windows.Controls/Control.xml
  xml/System.Windows.Controls/GridViewColumn.xml
  xml/System.Windows.Controls/InkCanvas.xml
  xml/System.Windows.Controls/MenuItem.xml
  xml/System.Windows.Controls/Page.xml
  xml/System.Windows.Controls/TextBox.xml
  xml/System.Windows.Controls/ToolTipService.xml
  xml/System.Windows.Controls/VirtualizingStackPanel.xml
  xml/System.Windows.Data/BindingBase.xml
  xml/System.Windows.Data/CollectionView.xml
  xml/System.Windows.Documents.DocumentStructures/StoryFragment.xml
  xml/System.Windows.Documents/FrameworkTextComposition.xml
  xml/System.Windows.Documents/TextPointer.xml
  xml/System.Windows.Documents/Typography.xml
  xml/System.Windows.Forms.DataVisualization.Charting/ArrowAnnotation.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Axis.xml
  xml/System.Windows.Forms/BindingContext.xml
  xml/System.Windows.Forms/ColumnStyle.xml
  xml/System.Windows.Forms/DataGridView+DataGridViewAccessibleObject.xml
  xml/System.Windows.Forms/DataGridView+DataGridViewTopRowAccessibleObject.xml
  xml/System.Windows.Forms/DataGridView.xml
  xml/System.Windows.Forms/DataGridViewButtonCell+DataGridViewButtonCellAccessibleObject.xml
  xml/System.Windows.Forms/DataGridViewCell+DataGridViewCellAccessibleObject.xml
  xml/System.Windows.Forms/DataGridViewCheckBoxCell+DataGridViewCheckBoxCellAccessibleObject.xml
  xml/System.Windows.Forms/DataGridViewColumnHeaderCell+DataGridViewColumnHeaderCellAccessibleObject.xml
  xml/System.Windows.Forms/DataGridViewImageCell+DataGridViewImageCellAccessibleObject.xml
  xml/System.Windows.Forms/DataGridViewLinkCell+DataGridViewLinkCellAccessibleObject.xml
  xml/System.Windows.Forms/DataGridViewRow+DataGridViewRowAccessibleObject.xml
  xml/System.Windows.Forms/DataGridViewRowHeaderCell+DataGridViewRowHeaderCellAccessibleObject.xml
  xml/System.Windows.Forms/DataGridViewTopLeftHeaderCell+DataGridViewTopLeftHeaderCellAccessibleObject.xml
  xml/System.Windows.Forms/IDataGridViewEditingControl.xml
  xml/System.Windows.Forms/Label.xml
  xml/System.Windows.Forms/ListView.xml
  xml/System.Windows.Forms/ListViewGroupCollection.xml
  xml/System.Windows.Forms/ListViewItem.xml
  xml/System.Windows.Forms/MaskFormat.xml
  xml/System.Windows.Forms/MaskedTextBox.xml
  xml/System.Windows.Forms/Padding.xml
  xml/System.Windows.Forms/PowerStatus.xml
  xml/System.Windows.Forms/RowStyle.xml
  xml/System.Windows.Forms/ScrollableControl.xml
  xml/System.Windows.Forms/ToolStrip.xml
  xml/System.Windows.Forms/ToolStripItem.xml
  xml/System.Windows.Forms/ToolStripItemImageScaling.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8

#1316 IntelliSense fixes - PR 6/?
  xml/System.Windows.Forms.DataVisualization.Charting/AxisScrollBar.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Chart.xml
  xml/System.Windows.Forms.DataVisualization.Charting/ChartArea.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Cursor.xml
  xml/System.Windows.Forms.DataVisualization.Charting/CursorEventArgs.xml
  xml/System.Windows.Forms.DataVisualization.Charting/CustomLabel.xml
  xml/System.Windows.Forms.DataVisualization.Charting/DataPoint.xml
  xml/System.Windows.Forms.DataVisualization.Charting/DataPointCollection.xml
  xml/System.Windows.Forms.DataVisualization.Charting/DataPointCustomProperties.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Grid.xml
  xml/System.Windows.Forms.DataVisualization.Charting/HitTestResult.xml
  xml/System.Windows.Forms.DataVisualization.Charting/ImageAnnotation.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Legend.xml
  xml/System.Windows.Forms.DataVisualization.Charting/LegendCell.xml
  xml/System.Windows.Forms.DataVisualization.Charting/LineAnchorCapStyle.xml
  xml/System.Windows.Forms.DataVisualization.Charting/NamedImage.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Point3D.xml
  xml/System.Windows.Forms.DataVisualization.Charting/ScrollBarEventArgs.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Series.xml
  xml/System.Windows.Forms.DataVisualization.Charting/StripLine.xml
  xml/System.Windows.Forms.DataVisualization.Charting/TickMark.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Title.xml
  xml/System.Windows.Forms.DataVisualization.Charting/ViewEventArgs.xml
  xml/System.Windows.Forms.Design.Behavior/SnapLinePriority.xml
  xml/System.Windows.Forms.Integration/PropertyMap.xml
  xml/System.Windows.Input/InputBindingCollection.xml
  xml/System.Windows.Input/Touch.xml
  xml/System.Windows.Input/TouchDevice.xml
  xml/System.Windows.Media.Animation/AnimationTimeline.xml
  xml/System.Windows.Media.Media3D/AffineTransform3D.xml
  xml/System.Windows.Media.Media3D/GeneralTransform3DCollection.xml
  xml/System.Windows.Media.TextFormatting/TextFormatter.xml
  xml/System.Windows.Media.TextFormatting/TextRun.xml
  xml/System.Windows.Media.TextFormatting/TextRunTypographyProperties.xml
  xml/System.Windows.Media/CharacterMetrics.xml
  xml/System.Windows.Media/DrawingVisual.xml
  xml/System.Windows.Media/FontFamily.xml
  xml/System.Windows.Media/FormattedText.xml
  xml/System.Windows.Media/GlyphRun.xml
  xml/System.Windows.Media/GlyphTypeface.xml
  xml/System.Windows.Xps.Packaging/XpsFont.xml
  xml/System.Windows.Xps.Serialization/ColorTypeConverter.xml
  xml/System.Windows.Xps.Serialization/FontTypeConverter.xml
  xml/System.Windows.Xps.Serialization/ImageSourceTypeConverter.xml
  xml/System.Workflow.ComponentModel.Design/WorkflowPageSetupDialog.xml
  xml/System.Xaml/XamlLanguage.xml
  xml/System.Xml.Linq/Extensions.xml
  xml/System.Xml.Linq/XElement.xml
  xml/System.Xml.Schema/XmlSchemaSet.xml
  xml/System.Xml.XPath/XPathDocument.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8

#1317 IntelliSense fixes - PR 7/?
  xml/System.Web.UI.Adapters/ControlAdapter.xml
  xml/System.Web.UI.DataVisualization.Charting/ArrowAnnotation.xml
  xml/System.Web.UI.DataVisualization.Charting/Axis.xml
  xml/System.Web.UI.DataVisualization.Charting/Chart.xml
  xml/System.Web.UI.DataVisualization.Charting/ChartArea.xml
  xml/System.Web.UI.DataVisualization.Charting/CustomLabel.xml
  xml/System.Web.UI.DataVisualization.Charting/DataPoint.xml
  xml/System.Web.UI.DataVisualization.Charting/DataPointCollection.xml
  xml/System.Web.UI.DataVisualization.Charting/DataPointCustomProperties.xml
  xml/System.Web.UI.DataVisualization.Charting/Grid.xml
  xml/System.Web.UI.DataVisualization.Charting/HitTestResult.xml
  xml/System.Web.UI.DataVisualization.Charting/ImageAnnotation.xml
  xml/System.Web.UI.DataVisualization.Charting/Legend.xml
  xml/System.Web.UI.DataVisualization.Charting/LegendCell.xml
  xml/System.Web.UI.DataVisualization.Charting/LineAnchorCapStyle.xml
  xml/System.Web.UI.DataVisualization.Charting/MapArea.xml
  xml/System.Web.UI.DataVisualization.Charting/NamedImage.xml
  xml/System.Web.UI.DataVisualization.Charting/Point3D.xml
  xml/System.Web.UI.DataVisualization.Charting/Series.xml
  xml/System.Web.UI.DataVisualization.Charting/StripLine.xml
  xml/System.Web.UI.DataVisualization.Charting/TickMark.xml
  xml/System.Web.UI.DataVisualization.Charting/Title.xml
  xml/System.Web.UI.WebControls.Adapters/DataBoundControlAdapter.xml
  xml/System.Web.UI.WebControls.WebParts/SqlPersonalizationProvider.xml
  xml/System.Web.UI.WebControls/AccessDataSource.xml
  xml/System.Web.UI.WebControls/MailMessageEventArgs.xml
  xml/System.Web.UI.WebControls/NumericPagerField.xml
  xml/System.Web.UI.WebControls/ObjectDataSource.xml
  xml/System.Web.UI.WebControls/SiteMapDataSource.xml
  xml/System.Web.UI.WebControls/SqlDataSource.xml
  xml/System.Web.UI.WebControls/SqlDataSourceView.xml
  xml/System.Web.UI.WebControls/TreeNodeStyleCollection.xml
  xml/System.Web.UI.WebControls/TreeView.xml
  xml/System.Web.UI.WebControls/TreeViewImageSet.xml
  xml/System.Windows.Annotations/Annotation.xml
  xml/System.Windows.Automation/AutomationElement.xml
  xml/System.Windows.Automation/ExpandCollapsePattern.xml
  xml/System.Windows.Automation/TextPattern.xml
  xml/System.Windows.Automation/TextPatternIdentifiers.xml
  xml/System.Windows.Controls/AccessText.xml
  xml/System.Windows.Controls/AlternationConverter.xml
  xml/System.Windows/Application.xml
  xml/System.Windows/ContentElement.xml
  xml/System.Windows/FontNumeralAlignment.xml
  xml/System.Windows/FontStretch.xml
  xml/System.Windows/FrameworkElement.xml
  xml/System.Windows/Rect.xml
  xml/System.Windows/ThemeInfoAttribute.xml
  xml/System.Windows/UIElement.xml
  xml/System.Windows/UIElement3D.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8

#1324 IntelliSense fixes - PR 8/?
  xml/System.Management.Instrumentation/InstrumentationManager.xml
  xml/System.Management/MethodDataCollection.xml
  xml/System.Net.Http/HttpClient.xml
  xml/System.Net.Http/WebRequestHandler.xml
  xml/System.Runtime.Caching/ObjectCache.xml
  xml/System.Runtime.DurableInstancing/InstancePersistenceContext.xml
  xml/System.Runtime.DurableInstancing/InstanceView.xml
  xml/System.Runtime.Remoting.Services/RemotingClientProxy.xml
  xml/System.Security.Cryptography.Xml/EncryptedXml.xml
  xml/System.ServiceModel.Web/WebOperationContext.xml
  xml/System.Speech.Recognition/SemanticValue.xml
  xml/System.Transactions/TransactionScope.xml
  xml/System.Web.ApplicationServices/AuthenticationService.xml
  xml/System.Web.Handlers/ScriptModule.xml
  xml/System.Web.Services.Configuration/ProtocolElementCollection.xml
  xml/System.Web.Services.Description/SoapProtocolImporter.xml
  xml/System.Web.Services.Protocols/SoapException.xml
  xml/System.Web.Services.Protocols/SoapFaultSubCode.xml
  xml/System.Web.Services.Protocols/SoapHttpClientProtocol.xml
  xml/System.Web.Services.Protocols/SoapMessage.xml
  xml/System.Web.UI.DataVisualization.Charting/ChartSerializer.xml
  xml/System.Web.UI/ScriptManager.xml
  xml/System.Web.UI/ScriptResourceAttribute.xml
  xml/System.Xml/UniqueId.xml
  xml/System.Xml/XmlDictionaryReader.xml
  xml/System.Xml/XmlDictionaryString.xml
  xml/System.Xml/XmlDictionaryWriter.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8, migration-fixes

#1309 Qualified member name in SqlParameter.Value documentation
  xml/System.Data.SqlClient/SqlParameter.xml
Labels: verify-build-before-merge

#1304 New .NET Framework 4.8 types/members, Part 1
  xml/System.Net.Configuration/SettingsSection.xml
  xml/System.Net.Configuration/WebProxyScriptElement.xml
  xml/System.Net.Configuration/WindowsAuthenticationElement.xml
  xml/System.Net/SecurityProtocolType.xml
  xml/System.Security.Authentication/SslProtocols.xml
  xml/System.Security.Cryptography.X509Certificates/X509Certificate.xml
  xml/System.Windows.Automation.Peers/AutomationPeer.xml
  xml/System.Windows.Automation.Peers/ContentElementAutomationPeer.xml
  xml/System.Windows.Automation.Peers/GroupItemAutomationPeer.xml
  xml/System.Windows.Automation.Peers/ItemAutomationPeer.xml
  xml/System.Windows.Automation.Peers/MenuItemAutomationPeer.xml
  xml/System.Windows.Automation.Peers/UIElement3DAutomationPeer.xml
  xml/System.Windows.Automation.Peers/UIElementAutomationPeer.xml
  xml/System.Windows.Automation/AutomationElement.xml
  xml/System.Windows.Automation/AutomationElementIdentifiers.xml
  xml/System.Windows.Automation/AutomationProperties.xml
  xml/System.Windows.Forms/ToolStripComboBox.xml
  xml/System.Windows.Forms/ToolStripProgressBar.xml
  xml/System.Windows.Forms/ToolStripTextBox.xml
Labels: :checkered_flag: Release: .NET Framework 4.8

#1305 New .NET Framework 4.8 types/members, Part 2
  xml/System.ServiceModel.Configuration/ServiceHealthElement.xml
  xml/System.ServiceModel.Description/ServiceHealthBehavior.xml
  xml/System.ServiceModel.Description/ServiceHealthBehaviorBase.xml
  xml/System.ServiceModel.Description/ServiceHealthData.xml
  xml/System.ServiceModel.Description/ServiceHealthDataCollection.xml
  xml/System.ServiceModel.Description/ServiceHealthModel+ChannelDispatcherModel.xml
  xml/System.ServiceModel.Description/ServiceHealthModel+CommunicationTimeoutsModel.xml
  xml/System.ServiceModel.Description/ServiceHealthModel+ProcessInformationModel.xml
  xml/System.ServiceModel.Description/ServiceHealthModel+ProcessThreadsModel.xml
  xml/System.ServiceModel.Description/ServiceHealthModel+ServiceEndpointModel.xml
  xml/System.ServiceModel.Description/ServiceHealthModel+ServicePropertiesModel.xml
  xml/System.ServiceModel.Description/ServiceHealthModel+ServiceThrottleModel.xml
  xml/System.ServiceModel.Description/ServiceHealthModel.xml
  xml/System.ServiceModel.Description/ServiceHealthSection.xml
  xml/System.ServiceModel.Description/ServiceHealthSectionCollection.xml
Labels: :checkered_flag: Release: .NET Framework 4.8

#1328 Localization fixes for @ character
  xml/System.Data.Common/DbCommandBuilder.xml
  xml/System.Data.Odbc/OdbcCommandBuilder.xml
  xml/System.Data.OleDb/OleDbCommandBuilder.xml
  xml/System.Data.SqlClient/SqlCommandBuilder.xml
  xml/System.Data.SqlClient/SqlParameter.xml
  xml/System.Data/IDataParameter.xml
Labels: loc

#1333 IntelliSense fixes - PR 9/?
  xml/System.Data.OracleClient/OracleConnectionStringBuilder.xml
  xml/System.Data.OracleClient/OracleDataReader.xml
  xml/System.Data.OracleClient/OracleString.xml
  xml/System.DirectoryServices.AccountManagement/AuthenticablePrincipal.xml
  xml/System.DirectoryServices.AccountManagement/ComputerPrincipal.xml
  xml/System.DirectoryServices.AccountManagement/GroupPrincipal.xml
  xml/System.DirectoryServices.AccountManagement/Principal.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalCollection.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalContext.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalOperationException.xml
  xml/System.DirectoryServices.AccountManagement/PrincipalSearcher.xml
  xml/System.DirectoryServices.Protocols/DirectoryAttribute.xml
  xml/System.DirectoryServices.Protocols/DirectoryAttributeCollection.xml
  xml/System.DirectoryServices.Protocols/DirectoryAttributeModificationCollection.xml
  xml/System.DirectoryServices.Protocols/DirectoryControlCollection.xml
  xml/System.DirectoryServices.Protocols/DsmlResponseDocument.xml
  xml/System.DirectoryServices.Protocols/NotifyOfNewConnectionCallback.xml
  xml/System.DirectoryServices.Protocols/PartialResultsCollection.xml
  xml/System.DirectoryServices.Protocols/SearchResultAttributeCollection.xml
  xml/System.DirectoryServices.Protocols/SearchResultEntryCollection.xml
  xml/System.DirectoryServices.Protocols/SearchResultReferenceCollection.xml
  xml/System.Messaging/MessageQueue.xml
  xml/System.Numerics/BigInteger.xml
  xml/System.Numerics/Vector2.xml
  xml/System.Numerics/Vector3.xml
  xml/System.Numerics/Vector4.xml
  xml/System.Xml.Xsl.Runtime/XsltFunctions.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8, migration-fixes

#1349 IntelliSense fixes - PR 11/?
  xml/System.Collections.Generic/SynchronizedCollection`1.xml
  xml/System.Collections.Generic/SynchronizedKeyedCollection`2.xml
  xml/System.Collections.Generic/SynchronizedReadOnlyCollection`1.xml
  xml/System.Data.Common.CommandTrees.ExpressionBuilder/DbExpressionBuilder.xml
  xml/System.Data.Common.CommandTrees/DbCaseExpression.xml
  xml/System.Data.Common.CommandTrees/DbCastExpression.xml
  xml/System.Data.Common.CommandTrees/DbComparisonExpression.xml
  xml/System.Data.Common.CommandTrees/DbConstantExpression.xml
  xml/System.Data.Common.CommandTrees/DbCrossJoinExpression.xml
  xml/System.Data.Common.CommandTrees/DbDerefExpression.xml
  xml/System.Data.Common.CommandTrees/DbDistinctExpression.xml
  xml/System.Data.Common.CommandTrees/DbElementExpression.xml
  xml/System.Data.Common.CommandTrees/DbEntityRefExpression.xml
  xml/System.Data.Common.CommandTrees/DbExceptExpression.xml
  xml/System.Data.Common/DbCommandBuilder.xml
  xml/System.Data.Common/DbConnectionStringBuilder.xml
  xml/System.Data.EntityClient/EntityConnectionStringBuilder.xml
  xml/System.Data.Objects.DataClasses/StructuralObject.xml
  xml/System.Data.Objects.SqlClient/SqlFunctions.xml
  xml/System.Data.Objects/CompiledQuery.xml
  xml/System.Data.Objects/ObjectContext.xml
  xml/System.Data.Objects/ObjectStateManager.xml
  xml/System.Data.Odbc/OdbcConnectionStringBuilder.xml
  xml/System.Data.OleDb/OleDbConnectionStringBuilder.xml
  xml/System.Data.SqlClient/SqlAuthenticationMethod.xml
  xml/System.Data.SqlClient/SqlConnection.xml
  xml/System.Data.SqlClient/SqlConnectionStringBuilder.xml
  xml/System.Data.SqlClient/SqlDependency.xml
  xml/System.Data/DataView.xml
  xml/System.DirectoryServices.ActiveDirectory/ActiveDirectorySiteLink.xml
  xml/System.DirectoryServices.ActiveDirectory/ApplicationPartition.xml
  xml/System.DirectoryServices/ExtendedRightAccessRule.xml
  xml/System.Drawing.Imaging/EncoderParameter.xml
  xml/System.Drawing.Printing/PrintingPermission.xml
  xml/System.Drawing/Graphics.xml
  xml/System.Drawing/Icon.xml
  xml/System.Drawing/Image.xml
  xml/System.IdentityModel.Metadata/MetadataSerializer.xml
  xml/System.IdentityModel.Protocols.WSTrust/ContextItem.xml
  xml/System.IdentityModel.Protocols.WSTrust/WSTrust13RequestSerializer.xml
  xml/System.IdentityModel.Protocols.WSTrust/WSTrustFeb2005RequestSerializer.xml
  xml/System.IdentityModel.Tokens/Saml2Id.xml
  xml/System.IdentityModel.Tokens/Saml2SecurityTokenHandler.xml
  xml/System.IdentityModel.Tokens/SamlAuthorityBinding.xml
  xml/System.IdentityModel.Tokens/SamlAuthorizationDecisionClaimResource.xml
  xml/System.IdentityModel/DelegatingXmlDictionaryWriter.xml
  xml/System.ServiceModel.Channels/AddressHeader.xml
  xml/System.ServiceModel.Channels/ConnectionOrientedTransportBindingElement.xml
  xml/System.ServiceModel.Channels/FaultConverter.xml
  xml/System.ServiceModel.Channels/MessageProperties.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8, migration-fixes

#1351 IntelliSense fixes - PR 12/?
  xml/System.Collections.Generic/SynchronizedReadOnlyCollection`1.xml
  xml/System.ServiceModel.Channels/MsmqBindingElementBase.xml
  xml/System.ServiceModel.Channels/MsmqTransportBindingElement.xml
  xml/System.ServiceModel.Channels/OneWayBindingElement.xml
  xml/System.ServiceModel.Channels/ReliableSessionBindingElement.xml
  xml/System.ServiceModel.Channels/TransportBindingElementImporter.xml
  xml/System.ServiceModel.Configuration/ConfigurationChannelFactory`1.xml
  xml/System.ServiceModel.Configuration/ConfigurationDuplexChannelFactory`1.xml
  xml/System.ServiceModel.Configuration/ServiceMetadataPublishingElement.xml
  xml/System.ServiceModel.Description/ServiceSecurityAuditBehavior.xml
  xml/System.ServiceModel.Description/WsdlExporter.xml
  xml/System.ServiceModel.Description/WsdlImporter.xml
  xml/System.ServiceModel.Dispatcher/ChannelDispatcher.xml
  xml/System.ServiceModel.Dispatcher/MessageFilterTable`1.xml
  xml/System.ServiceModel.Dispatcher/XPathMessageFilter.xml
  xml/System.ServiceModel.Dispatcher/XPathMessageFilterTable`1.xml
  xml/System.ServiceModel.MsmqIntegration/MsmqIntegrationBindingElement.xml
  xml/System.ServiceModel.MsmqIntegration/MsmqIntegrationMessageProperty.xml
  xml/System.ServiceModel.Security/SecurityMessageProperty.xml
  xml/System.ServiceModel.Security/WSSecurityTokenSerializer.xml
  xml/System.ServiceModel.Security/WSTrustServiceContract.xml
  xml/System.ServiceModel.Security/X509CertificateRecipientClientCredential.xml
  xml/System.ServiceModel.Syndication/AtomPub10ServiceDocumentFormatter.xml
  xml/System.ServiceModel.Syndication/InlineCategoriesDocument.xml
  xml/System.ServiceModel.Syndication/ReferencedCategoriesDocument.xml
  xml/System.ServiceModel.Syndication/ResourceCollectionInfo.xml
  xml/System.ServiceModel.Syndication/ServiceDocument.xml
  xml/System.ServiceModel.Syndication/ServiceDocumentFormatter.xml
  xml/System.ServiceModel.Syndication/Workspace.xml
  xml/System.ServiceModel/ClientBase`1.xml
  xml/System.ServiceModel/DuplexClientBase`1.xml
  xml/System.ServiceModel/EndpointAddress.xml
  xml/System.ServiceModel/WSHttpSecurity.xml
  xml/System.ServiceModel/X509CertificateEndpointIdentity.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8, migration-fixes

#1362 IntelliSense fixes - PR 14/?
  xml/System.Net.Sockets/SocketAsyncEventArgs.xml
  xml/System.Net.Sockets/SocketReceiveMessageFromResult.xml
  xml/System.Net.Sockets/SocketTaskExtensions.xml
  xml/System.Net.Sockets/UdpReceiveResult.xml
  xml/System.Net.WebSockets/ClientWebSocket.xml
  xml/System.Net.WebSockets/ClientWebSocketOptions.xml
  xml/System.Net.WebSockets/HttpListenerWebSocketContext.xml
  xml/System.Net.WebSockets/WebSocket.xml
  xml/System.Resources/ResourceManager.xml
  xml/System.Runtime.InteropServices/MemoryMarshal.xml
  xml/System.Security.Cryptography/AsnEncodedDataCollection.xml
  xml/System.Security.Cryptography/RSACng.xml
  xml/System.Security.Cryptography/RSAEncryptionPadding.xml
  xml/System.ServiceModel.Activities.Configuration/WorkflowControlEndpointElement.xml
  xml/System.ServiceModel.Channels/MsmqBindingElementBase.xml
  xml/System.ServiceModel.Channels/MsmqTransportBindingElement.xml
  xml/System.ServiceModel.Dispatcher/XPathMessageFilter.xml
  xml/System.ServiceModel.MsmqIntegration/MsmqIntegrationBindingElement.xml
  xml/System.Web.Caching/OutputCacheUtility.xml
  xml/System.Web.UI.DataVisualization.Charting/SeriesCollection.xml
  xml/System.Web/AspNetHostingPermission.xml
  xml/System.Windows.Forms/AccessibleObject.xml
  xml/System.Windows.Forms/ComboBox+ObjectCollection.xml
  xml/System.Windows.Forms/Control+ControlCollection.xml
  xml/System.Windows.Forms/Control.xml
  xml/System.Windows.Forms/ControlBindingsCollection.xml
  xml/System.Windows.Forms/DataGridBoolColumn.xml
  xml/System.Windows.Forms/DataGridColumnStyle.xml
  xml/System.Windows.Forms/DataGridTextBoxColumn.xml
  xml/System.Windows.Forms/DataGridViewComboBoxCell+ObjectCollection.xml
  xml/System.Windows.Forms/GridColumnStylesCollection.xml
  xml/System.Windows.Forms/GridTableStylesCollection.xml
  xml/System.Windows.Forms/Help.xml
  xml/System.Windows.Forms/HtmlElementCollection.xml
  xml/System.Windows.Forms/HtmlWindow.xml
  xml/System.Windows.Forms/LinkLabel+LinkCollection.xml
  xml/System.Windows.Forms/ListBox+ObjectCollection.xml
  xml/System.Windows.Forms/ListBox+SelectedIndexCollection.xml
  xml/System.Windows.Forms/ListBox+SelectedObjectCollection.xml
  xml/System.Windows.Forms/ListView+ColumnHeaderCollection.xml
  xml/System.Windows.Forms/ListView+ListViewItemCollection.xml
  xml/System.Windows.Forms/RichTextBox.xml
  xml/System.Windows.Forms/TabControl.xml
  xml/System.Windows.Forms/ToolStripManager.xml
  xml/System.Xaml.Schema/XamlTypeName.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8, migration-fixes, style-guide, verify-build-before-merge

#1293 Refer <gcAllowVeryLargeObjects> element
  xml/System.Collections.Generic/HashSet`1.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#1366 IntelliSense fixes - PR 15/15
  xml/Microsoft.Build.Conversion/ProjectFileConverter.xml
  xml/System.ComponentModel.Design/DesignerActionListsChangedEventArgs.xml
  xml/System.Data.Objects/MergeOption.xml
  xml/System.Diagnostics/TraceSwitch.xml
  xml/System.Globalization/NumberFormatInfo.xml
  xml/System.IO/Directory.xml
  xml/System.Net.Http/HttpContent.xml
  xml/System.Net.PeerToPeer.Collaboration/PeerContact.xml
  xml/System.Numerics/BigInteger.xml
  xml/System.Runtime.Caching/ChangeMonitor.xml
  xml/System.Security.Claims/ClaimValueTypes.xml
  xml/System.Threading.Tasks/Task.xml
  xml/System.Threading.Tasks/Task`1.xml
  xml/System.Web.Caching/Cache.xml
  xml/System.Web.Caching/CacheDependency.xml
  xml/System.Web.Caching/CacheItemRemovedCallback.xml
  xml/System.Web.Caching/FileResponseElement.xml
  xml/System.Web.Caching/HeaderElement.xml
  xml/System.Web.Configuration/TransformerInfo.xml
  xml/System.Web.Hosting/HostingEnvironment.xml
  xml/System.Web.Hosting/ProcessHost.xml
  xml/System.Web.ModelBinding/DataAnnotationsModelValidatorProvider.xml
  xml/System.Web.Routing/RouteValueDictionary.xml
  xml/System.Web.Security.AntiXss/AntiXssEncoder.xml
  xml/System.Web.UI.WebControls.WebParts/ProxyWebPart.xml
  xml/System.Web.UI.WebControls.WebParts/WebPart.xml
  xml/System.Web.UI.WebControls.WebParts/WebPartPersonalization.xml
  xml/System.Web.UI.WebControls/BaseCompareValidator.xml
  xml/System.Web.UI.WebControls/CompareValidator.xml
  xml/System.Web.UI.WebControls/Literal.xml
  xml/System.Web.UI/ClientScriptManager.xml
  xml/System.Web.UI/Page.xml
  xml/System.Web.UI/PageParserFilter.xml
  xml/System.Web/HttpCachePolicy.xml
  xml/System.Web/HttpFileCollectionBase.xml
  xml/System.Web/HttpFileCollectionWrapper.xml
  xml/System.Web/HttpRequest.xml
  xml/System.Web/HttpRequestWrapper.xml
  xml/System.Web/HttpResponse.xml
  xml/System.Web/HttpResponseBase.xml
  xml/System.Windows.Forms/DataGridView.xml
  xml/System.Windows.Forms/LinkLabel.xml
  xml/System.Windows.Forms/ToolStripLabel.xml
  xml/System.Windows.Media.Animation/Timeline.xml
  xml/System.Windows/FontStretchConverter.xml
  xml/System.Windows/FontStyleConverter.xml
  xml/System.Windows/FontWeightConverter.xml
  xml/System.Windows/Window.xml
  xml/System.Xaml/XamlObjectWriter.xml
  xml/System.Xml.Schema/XmlValueGetter.xml
  xml/System.Xml/XmlNode.xml
  xml/System/Double.xml
  xml/System/Single.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8, migration-fixes

#1381 recover missing content
  xml/Microsoft.Build.Tasks/VCBuild.xml
Labels: migration-fixes

#1375 Revised TmeZoneInfo for .NET Core, modifed information on caching
  xml/System/TimeZoneInfo.xml
Labels: verify-build-before-merge

#1388 Documented AutomationProperties.PositionInSet attached property
  xml/System.Windows.Automation/AutomationProperties.xml
Labels: :checkered_flag: Release: .NET Framework 4.8

#1432 Grammar fix
  xml/System.Net.Sockets/NetworkStream.xml
Labels: verify-build-before-merge

#1424 Fixed typo
  xml/System/Environment.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#1420 Documented newest .NET Framework 4.8 APIs
  xml/System.Windows.Forms/DataGridViewTextBoxEditingControl.xml
  xml/System.Windows.Forms/ToolStrip.xml
  xml/System.Windows.Forms/ToolStripRenderer.xml
Labels: :checkered_flag: Release: .NET Framework 4.8

#1434 add missing content
  xml/System.Device.Location/GeoCoordinateWatcher.xml
  xml/System.Security.Cryptography.Xml/EncryptedXml.xml
  xml/System.ServiceModel.Channels/UdpTransportBindingElement.xml
  xml/System.Web.Hosting/CustomLoaderAttribute.xml
  xml/System.Web.Services.Protocols/SoapException.xml
  xml/System.Web.Services.Protocols/SoapFaultSubCode.xml
  xml/System.Web.UI.MobileControls/Command.xml
  xml/System.Web.UI.MobileControls/DeviceSpecificChoice.xml
  xml/System.Web.UI.MobileControls/Image.xml
  xml/System.Web.UI.MobileControls/Link.xml
  xml/System.Web.UI.MobileControls/ObjectListFieldCollection.xml
  xml/System.Web.UI.MobileControls/PhoneCall.xml
  xml/System.Web.UI.MobileControls/SelectionList.xml
  xml/System.Windows.Forms/Control+ControlCollection.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8, migration-fixes, new-content

#1441 improve summary
  xml/System.Windows.Automation/AutomationProperties.xml
Labels: :checkered_flag: Release: .NET Framework 4.8

#1438 typo
  xml/System.Net/Dns.xml
Labels: :card_file_box: Technology - NCL, :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#1449 Add missing descriptions
  xml/System.ServiceModel.Description/ServiceHealthBehavior.xml
  xml/System.Windows.Forms/ToolStripStatusLabel.xml
Labels: :checkered_flag: Release: .NET Framework 4.8

#1457 add missing descriptions
  xml/Microsoft.VisualBasic/Interaction.xml
  xml/Microsoft.VisualC/MiscellaneousBitsAttribute.xml
  xml/System.Collections.ObjectModel/ReadOnlyDictionary`2.xml
  xml/System.Configuration.Install/AssemblyInstaller.xml
  xml/System.Configuration/ConfigurationElement.xml
  xml/System.Configuration/ConfigurationElementCollection.xml
  xml/System.Configuration/ConnectionStringSettingsCollection.xml
  xml/System.Data.Common/DbDataReader.xml
  xml/System.Data.Linq/ITable`1.xml
  xml/System.Data/DataRow.xml
  xml/System.Diagnostics/StackTrace.xml
  xml/System.IO.Compression/DeflateStream.xml
  xml/System.Management.Instrumentation/InstrumentationManager.xml
  xml/System.Security.Cryptography/SHA1Managed.xml
  xml/System.Security.Permissions/FileIOPermission.xml
  xml/System.Security.Permissions/PrincipalPermission.xml
  xml/System.Security.Permissions/RegistryPermission.xml
  xml/System.Security.Permissions/StrongNamePublicKeyBlob.xml
  xml/System.Security.Policy/ApplicationTrust.xml
  xml/System.Security.Policy/PolicyStatement.xml
  xml/System.Security/NamedPermissionSet.xml
  xml/System.Threading/CancellationTokenSource.xml
  xml/System.Windows.Forms/TabControl+TabPageCollection.xml
  xml/System/Environment.xml
  xml/System/StringComparer.xml
  xml/System/TimeZoneInfo.xml
Labels: :bookmark_tabs: Information Architecture, :checkered_flag: Release: .NET Framework 4.8
