Repository dotnet/dotnet-api-docs, pull requests merged in 2018-05, with the labels that each got.

#109 Replace ADO token with plain text
  includes/tla2sharptla-ado-md.md
  xml/System.Windows.Data/DataSourceProvider.xml
Labels: verify-build-before-merge

#110 Replace ".NET Framework 4.6" token with plain text
  includes/net-2015-md.md
  xml/Microsoft.Win32/RegistryKey.xml
  xml/System.IO/UnmanagedMemoryStream.xml
  xml/System.Windows.Forms/DataGridViewColumn.xml
  xml/System.Windows.Forms/DataGridViewComboBoxColumn.xml
  xml/System.Windows.Forms/DomainUpDown.xml
  xml/System.Windows.Forms/NumericUpDown.xml
  xml/System.Windows.Forms/ToolStripSplitButton.xml
  xml/System.Windows.Forms/UpDownBase.xml
Labels: verify-build-before-merge

#125 Replace RTF and AES tokens with plain text
  includes/tla2sharptla-rtf-md.md
  includes/tlasharptla-aes-md.md
  xml/System.Security.RightsManagement/CryptoProvider.xml
  xml/System.Windows/DataFormats.xml
Labels: :file_folder: Repo - dotnet-api-docs, verify-build-before-merge

#133 Replaced vba token with token text, removed token
  includes/tlasharptla-vba-md.md
  xml/System.Windows/FrameworkContentElement.xml
  xml/System.Windows/FrameworkElement.xml
Labels: :file_folder: Repo - dotnet-api-docs, verify-build-before-merge

#136 Switch msdn link to /docs/standard/events/index.md
  xml/System.Web.UI.WebControls/AdRotator.xml
  xml/System.Windows.Forms/Binding.xml
  xml/System.Windows.Forms/BindingContext.xml
  xml/System.Windows.Forms/Button.xml
  xml/System.Windows.Forms/ButtonBase.xml
  xml/System.Windows.Forms/CheckBox.xml
  xml/System.Windows.Forms/ComboBox.xml
  xml/System.Windows.Forms/CommonDialog.xml
  xml/System.Windows.Forms/ContextMenu.xml
  xml/System.Windows.Forms/Control.xml
  xml/System.Windows.Forms/FileDialog.xml
  xml/System.Windows.Forms/Form.xml
  xml/System.Windows.Forms/GroupBox.xml
  xml/System.Windows.Forms/Label.xml
  xml/System.Windows.Forms/ListBox.xml
  xml/System.Windows.Forms/ListControl.xml
  xml/System.Windows.Forms/ListView.xml
  xml/System.Windows.Forms/MenuItem.xml
  xml/System.Windows.Forms/Panel.xml
  xml/System.Windows.Forms/ProgressBar.xml
  xml/System.Windows.Forms/RadioButton.xml
  xml/System.Windows.Forms/StatusBar.xml
  xml/System.Windows.Forms/TabControl.xml
  xml/System.Windows.Forms/Timer.xml
  xml/System.Windows.Forms/ToolBar.xml
  xml/System.Windows.Forms/ToolTip.xml
  xml/System.Windows.Forms/TreeView.xml
  xml/System.Windows.Forms/UserControl.xml
  xml/System.Windows.Forms/WebBrowser.xml
  xml/System/Console.xml
Labels: :file_folder: Repo - dotnet-api-docs, verify-build-before-merge

#134 Corrected error, stylistic changes
  xml/System.Windows/TextMarkerStyle.xml
Labels: :file_folder: Repo - dotnet-api-docs, verify-build-before-merge

#135 Convert links to https (1/3)
  xml/System.Text.RegularExpressions/Regex.xml
  xml/System.Text/Encoding.xml
  xml/System.Text/NormalizationForm.xml
  xml/System.Web.Configuration/DeploymentSection.xml
  xml/System.Web.Security.AntiXss/AntiXssEncoder.xml
  xml/System.Web/HttpResponse.xml
  xml/System.Web/HttpResponseBase.xml
  xml/System.Web/HttpResponseWrapper.xml
  xml/System.Windows.Automation.Provider/ITextRangeProvider.xml
  xml/System.Windows.Automation.Text/TextPatternRange.xml
  xml/System.Xml/ConformanceLevel.xml
  xml/System.Xml/XmlConvert.xml
  xml/System.Xml/XmlDocument.xml
  xml/System.Xml/XmlNamespaceManager.xml
  xml/System.Xml/XmlNode.xml
  xml/System.Xml/XmlNodeReader.xml
  xml/System.Xml/XmlReader.xml
  xml/System.Xml/XmlReaderSettings.xml
  xml/System.Xml/XmlTextReader.xml
  xml/System.Xml/XmlValidatingReader.xml
  xml/System.Xml/XmlWriter.xml
  xml/System.Xml/XmlWriterSettings.xml
  xml/System/Array.xml
  xml/System/Char.xml
  xml/System/Convert.xml
  xml/System/Object.xml
  xml/System/String.xml
Labels: :file_folder: Repo - dotnet-api-docs

#143 Replace MSDN links
  xml/System.Diagnostics.CodeAnalysis/SuppressMessageAttribute.xml
Labels: :file_folder: Repo - dotnet-api-docs

#153 obsolete workaround
  xml/System.IO.Enumeration/FileSystemEntry.xml
  xml/System/ReadOnlySpan`1+Enumerator.xml
  xml/System/ReadOnlySpan`1.xml
  xml/System/Span`1+Enumerator.xml
  xml/System/Span`1.xml
Labels: :file_folder: Repo - dotnet-api-docs

#146 Replace "Microsoft Windows XP" token with plain text
  includes/tlasharptla-whistler-md.md
  xml/System.Printing/PrintSystemJobInfo.xml
  xml/System.Windows.Controls/Viewport3D.xml
  xml/System.Windows/SystemParameters.xml
Labels: :file_folder: Repo - dotnet-api-docs

#149 Replace "Windows XP" token with plain text
  includes/tla2sharptla-whistler2-md.md
  xml/System.Windows/SystemParameters.xml
Labels: :file_folder: Repo - dotnet-api-docs

#150 Replace XAML token with plain text
  includes/tla2sharptla-xamlsharpinitcap-md.md
  xml/System.Windows/DataFormats.xml
Labels: verify-build-before-merge

#151 Replace "Microsoft Notepad" token with plain text
  includes/tlasharptla-notepad-md.md
  xml/System.Windows.Automation/TextPattern.xml
Labels: verify-build-before-merge

#158 Small typo in System.Reflection.Emit
  xml/System.Reflection.Emit/DynamicMethod.xml
Labels: :sparkles: 1st-time GH contributor!

#160 Generic Stack and Queue: clarified undefined behavior
  xml/System.Collections.Generic/Queue`1+Enumerator.xml
  xml/System.Collections.Generic/Queue`1.xml
  xml/System.Collections.Generic/Stack`1+Enumerator.xml
  xml/System.Collections.Generic/Stack`1.xml
Labels: :file_folder: Repo - dotnet-api-docs, enhancement, merge-on-hold-for-live-update

#163 Improve ConcurrentDictionary.TryUpdate
  xml/System.Collections.Concurrent/ConcurrentDictionary`2.xml
Labels: :file_folder: Repo - dotnet-api-docs, :sparkles: 1st-time docs contributor!, merge-on-hold-for-live-update

#162 Remove bad Interlocked.Exchange example
  xml/System.Threading/Interlocked.xml
Labels: :file_folder: Repo - dotnet-api-docs, bug

#170 remove locale from link and vista info
  xml/ns-System.Diagnostics.Eventing.xml
Labels: :file_folder: Repo - dotnet-api-docs

#169 Add lang identifiers (3)
  xml/System.Diagnostics/BooleanSwitch.xml
  xml/System.Diagnostics/ConsoleTraceListener.xml
  xml/System.Diagnostics/Debug.xml
  xml/System.Diagnostics/DebuggerDisplayAttribute.xml
  xml/System.Diagnostics/DebuggerNonUserCodeAttribute.xml
  xml/System.Diagnostics/DebuggerStepThroughAttribute.xml
  xml/System.Diagnostics/DefaultTraceListener.xml
  xml/System.Diagnostics/DelimitedListTraceListener.xml
  xml/System.Diagnostics/EventSchemaTraceListener.xml
  xml/System.Diagnostics/Process.xml
  xml/System.Diagnostics/ProcessStartInfo.xml
  xml/System.Diagnostics/SourceSwitch.xml
  xml/System.Diagnostics/Switch.xml
  xml/System.Diagnostics/TextWriterTraceListener.xml
  xml/System.Diagnostics/Trace.xml
  xml/System.Diagnostics/TraceLevel.xml
  xml/System.Diagnostics/TraceListener.xml
  xml/System.Diagnostics/TraceOptions.xml
  xml/System.Diagnostics/TraceSource.xml
  xml/System.Diagnostics/TraceSwitch.xml
  xml/System.Diagnostics/XmlWriterTraceListener.xml
  xml/System.Reflection/AssemblyDelaySignAttribute.xml
  xml/System.Reflection/AssemblyKeyFileAttribute.xml
  xml/System.Reflection/AssemblySignatureKeyAttribute.xml
  xml/System.Reflection/ModuleResolveEventHandler.xml
  xml/System.Reflection/PropertyInfo.xml
  xml/System.Reflection/TypeDelegator.xml
  xml/System.Threading/CancellationToken.xml
  xml/System.Threading/SemaphoreSlim.xml
  xml/System.Threading/SpinLock.xml
  xml/System.Threading/Thread.xml
Labels: :file_folder: Repo - dotnet-api-docs

#168 Add lang identifiers (2)
  xml/System.Xml/XmlTextReader.xml
  xml/System.Xml/XmlTextWriter.xml
  xml/System.Xml/XmlUrlResolver.xml
  xml/System.Xml/XmlValidatingReader.xml
  xml/System.Xml/XmlWriter.xml
  xml/System.Xml/XmlWriterSettings.xml
Labels: :file_folder: Repo - dotnet-api-docs

#167 Add language identifiers to snippets
  xml/System.Xml/IFragmentCapableXmlDictionaryWriter.xml
  xml/System.Xml/IHasXmlNode.xml
  xml/System.Xml/XmlConvert.xml
  xml/System.Xml/XmlDataDocument.xml
  xml/System.Xml/XmlDictionaryWriter.xml
  xml/System.Xml/XmlDocument.xml
  xml/System.Xml/XmlEntity.xml
  xml/System.Xml/XmlNamespaceManager.xml
  xml/System.Xml/XmlNode.xml
  xml/System.Xml/XmlNodeChangedEventArgs.xml
  xml/System.Xml/XmlNodeReader.xml
  xml/System.Xml/XmlReader.xml
  xml/System.Xml/XmlResolver.xml
Labels: :file_folder: Repo - dotnet-api-docs

#180 Changed list format to ordered
  xml/System.Data.Linq/DataContext.xml
Labels: verify-build-before-merge

#184 Fix typo in ForeignKeyAttribute.xml
  xml/System.ComponentModel.DataAnnotations.Schema/ForeignKeyAttribute.xml
Labels: :sparkles: 1st-time docs contributor!, verify-build-before-merge

#191 Fix typo
  xml/ns-System.Configuration.Install.xml
Labels: verify-build-before-merge

#174 Consistently xref properties in ArgumentException
  xml/System/ArgumentException.xml
Labels: verify-build-before-merge

#188 Replace fwlink (5)
  xml/System.Activities.DynamicUpdate/ActivityBlockingUpdate.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateInfo.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMap.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapBuilder.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapItem.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapQuery.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateServices.xml
  xml/System.Activities.DynamicUpdate/InstanceUpdateException.xml
  xml/System.Activities.DynamicUpdate/NativeActivityUpdateContext.xml
  xml/System.Activities.DynamicUpdate/NativeActivityUpdateMapMetadata.xml
  xml/System.Activities.DynamicUpdate/UpdateMapMetadata.xml
  xml/System.Activities/VersionMismatchException.xml
  xml/System.Activities/WorkflowApplicationInstance.xml
  xml/System.Activities/WorkflowIdentity.xml
  xml/System.Activities/WorkflowIdentityFilter.xml
Labels: :file_folder: Repo - dotnet-api-docs

#189 Replace fwlink (6)
  xml/System.Activities.DynamicUpdate/ActivityBlockingUpdate.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateInfo.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMap.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapBuilder.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapItem.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapQuery.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateServices.xml
  xml/System.Activities.DynamicUpdate/InstanceUpdateException.xml
  xml/System.Activities.DynamicUpdate/NativeActivityUpdateContext.xml
  xml/System.Activities.DynamicUpdate/NativeActivityUpdateMapMetadata.xml
  xml/System.Activities.DynamicUpdate/UpdateMapMetadata.xml
  xml/System.Activities/VersionMismatchException.xml
  xml/System.Activities/WorkflowApplicationInstance.xml
  xml/System.Activities/WorkflowIdentity.xml
  xml/System.Activities/WorkflowIdentityFilter.xml
Labels: :file_folder: Repo - dotnet-api-docs

#198 Replace fwlink (8)
  xml/System.Activities.DynamicUpdate/ActivityBlockingUpdate.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateInfo.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMap.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapBuilder.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapItem.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapQuery.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateServices.xml
  xml/System.Activities.DynamicUpdate/InstanceUpdateException.xml
  xml/System.Activities.DynamicUpdate/NativeActivityUpdateContext.xml
  xml/System.Activities.DynamicUpdate/NativeActivityUpdateMapMetadata.xml
  xml/System.Activities.DynamicUpdate/UpdateMapMetadata.xml
  xml/System.Activities/VersionMismatchException.xml
  xml/System.Activities/WorkflowApplicationInstance.xml
  xml/System.Activities/WorkflowIdentity.xml
  xml/System.Activities/WorkflowIdentityFilter.xml
Labels: :file_folder: Repo - dotnet-api-docs

#190 Replace fwlink (7)
  xml/System.Activities.DynamicUpdate/ActivityBlockingUpdate.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateInfo.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMap.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapBuilder.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapItem.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapQuery.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateServices.xml
  xml/System.Activities.DynamicUpdate/InstanceUpdateException.xml
  xml/System.Activities.DynamicUpdate/NativeActivityUpdateContext.xml
  xml/System.Activities.DynamicUpdate/NativeActivityUpdateMapMetadata.xml
  xml/System.Activities.DynamicUpdate/UpdateMapMetadata.xml
  xml/System.Activities/VersionMismatchException.xml
  xml/System.Activities/WorkflowApplicationInstance.xml
  xml/System.Activities/WorkflowIdentity.xml
  xml/System.Activities/WorkflowIdentityFilter.xml
Labels: :file_folder: Repo - dotnet-api-docs

#199 Replace fwlink (9)
  xml/System.Activities.DynamicUpdate/ActivityBlockingUpdate.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateInfo.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMap.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapBuilder.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapItem.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapQuery.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateServices.xml
  xml/System.Activities.DynamicUpdate/InstanceUpdateException.xml
  xml/System.Activities.DynamicUpdate/NativeActivityUpdateContext.xml
  xml/System.Activities.DynamicUpdate/NativeActivityUpdateMapMetadata.xml
  xml/System.Activities.DynamicUpdate/UpdateMapMetadata.xml
  xml/System.Activities/VersionMismatchException.xml
  xml/System.Activities/WorkflowApplicationInstance.xml
  xml/System.Activities/WorkflowIdentity.xml
  xml/System.Activities/WorkflowIdentityFilter.xml
Labels: :file_folder: Repo - dotnet-api-docs

#200 Replace fwlink (10)
  xml/System.Activities.DynamicUpdate/ActivityBlockingUpdate.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateInfo.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMap.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapBuilder.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapItem.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateMapQuery.xml
  xml/System.Activities.DynamicUpdate/DynamicUpdateServices.xml
  xml/System.Activities.DynamicUpdate/InstanceUpdateException.xml
  xml/System.Activities.DynamicUpdate/NativeActivityUpdateContext.xml
  xml/System.Activities.DynamicUpdate/NativeActivityUpdateMapMetadata.xml
  xml/System.Activities.DynamicUpdate/UpdateMapMetadata.xml
  xml/System.Activities/VersionMismatchException.xml
  xml/System.Activities/WorkflowApplicationInstance.xml
  xml/System.Activities/WorkflowIdentity.xml
  xml/System.Activities/WorkflowIdentityFilter.xml
Labels: :file_folder: Repo - dotnet-api-docs

#201 Replace MSDN link (1)
  xml/System.Windows.Forms/HtmlElement.xml
  xml/System.Windows.Forms/HtmlWindow.xml
Labels: changes-addressed

#216 fix broken links
  xml/System/Span`1.xml
Labels: :file_folder: Repo - dotnet-api-docs

#172 Clarified undefined behaviors for SortedDictionary
  xml/System.Collections.Generic/SortedDictionary`2+Enumerator.xml
  xml/System.Collections.Generic/SortedDictionary`2+KeyCollection+Enumerator.xml
  xml/System.Collections.Generic/SortedDictionary`2+KeyCollection.xml
  xml/System.Collections.Generic/SortedDictionary`2+ValueCollection+Enumerator.xml
  xml/System.Collections.Generic/SortedDictionary`2+ValueCollection.xml
  xml/System.Collections.Generic/SortedDictionary`2.xml
Labels: :file_folder: Repo - dotnet-api-docs

#219 Fixed codefencing
  xml/System/Span`1.xml
Labels: :file_folder: Repo - dotnet-api-docs

#221 update CacheItemPolicy.xml
  xml/System.Runtime.Caching/CacheItemPolicy.xml
Labels: :sparkles: 1st-time docs contributor!

#222 Remove the confusing word "custom" from the description for MachineKeySection.ValidationAlgorithm
  xml/System.Web.Configuration/MachineKeySection.xml
Labels: :sparkles: 1st-time docs contributor!, verify-build-before-merge

#218 Added information on useSocketsHttpHandler switch
  xml/System.Net.Http/HttpClient.xml
  xml/System.Net.Http/HttpClientHandler.xml
  xml/System/AppContext.xml
Labels: :checkered_flag: Release: .NET Core 2.1

#224 Update X509Certificate2.xml
  xml/System.Security.Cryptography.X509Certificates/X509Certificate2.xml
Labels: :sparkles: 1st-time docs contributor!, verify-build-before-merge
