Repository dotnet/dotnet-api-docs, pull requests merged in 2019-03, with the labels that each got.

#1971 Update HttpResponseMessage.EnsureSuccessStatusCode method
  xml/System.Net.Http/HttpResponseMessage.xml
Labels: :card_file_box: Technology - NCL

#1982 Update Message.xml
  xml/System.Windows.Forms/Message.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#1986 enable xref links to UWP APIs
  .openpublishing.publish.config.json
Labels: :bookmark_tabs: Information Architecture, verify-build-before-merge

#1994 Use typeparamref in ReadOnlySequence<T> summary
  xml/System.Buffers/ReadOnlySequence`1.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#1996 Tiny typo fix.
  includes/c-and-posix-cultures.md
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#1972 UnauthorizedAccessException added to FileStream(String, FileMode) constructor
  xml/System.IO/FileStream.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2001 Initial documentation for System.IO.Compression.BrotliStream, amending GZipStream/DeflateStream
  xml/System.IO.Compression/BrotliStream.xml
  xml/System.IO.Compression/DeflateStream.xml
  xml/System.IO.Compression/GZipStream.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content

#1975 AssemblyLoadContext unloadability documentation
  xml/System.Reflection/Assembly.xml
  xml/System.Reflection/MemberInfo.xml
  xml/System.Runtime.Loader/AssemblyLoadContext.xml
Labels: :checkered_flag: Release: .NET Core 3.0, :file_folder: Repo - dotnet-api-docs, new-content

#1988 US-70351 : Changes implemented for fixing.
  xml/Microsoft.Aspnet.Snapin/MMC_CONTROL_TYPE.xml
  xml/Microsoft.Build.Tasks/ResolveVCProjectOutput.xml
  xml/Microsoft.VisualC.StlClr.Generic/ConstReverseRandomAccessIterator`1.xml
  xml/Microsoft.Vsa/BaseVsaSite.xml
  xml/System.Speech.Recognition/SemanticResultKey.xml
  xml/System.Web.UI.Design.WebControls/TreeViewBindingsEditor.xml
  xml/System.Web.UI.Design.WebControls/XmlDesigner.xml
  xml/System.Web.UI.WebControls/ListItem.xml
  xml/System.Web.UI.WebControls/Wizard.xml
  xml/System.Windows.Forms/MaskedTextBox.xml
Labels: migration-fixes, verify-build-before-merge

#1998 migrate content from MSDN
  xml/System/WindowsRuntimeSystemExtensions.xml
Labels: migration-fixes, verify-build-before-merge

#2006 Update CacheControlHeaderValue.xml
  xml/System.Net.Http.Headers/CacheControlHeaderValue.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#1970 add content from MSDN pages
  xml/System.IO/WindowsRuntimeStorageExtensions.xml
  xml/System.IO/WindowsRuntimeStreamExtensions.xml
Labels: migration-fixes

#2019 replace problematic cdata section
  xml/System.Xml.Xsl/XslCompiledTransform.xml
Labels: verify-build-before-merge

#2027 FixBlogLinks: updates to 6 files
  includes/calendar-era.md
  xml/System.Collections.Concurrent/ConcurrentBag`1.xml
  xml/System.Threading.Tasks/Task.xml
  xml/System.Threading.Tasks/TaskCompletionSource`1.xml
  xml/System.Threading.Tasks/TaskFactory.xml
  xml/System.Xml.Linq/XObject.xml
Labels: verify-build-before-merge

#2022 Summary & Return type updated
  xml/Microsoft.Vsa/BaseVsaStartup.xml
Labels: migration-fixes

#2026 lock non-working URLs
  xml/System.IdentityModel.Claims/ClaimTypes.xml
  xml/System.IdentityModel.Claims/Rights.xml
  xml/System.IdentityModel.Selectors/UnsupportedPolicyOptionsException.xml
  xml/System.Security.Claims/ClaimTypes.xml
Labels: verify-build-before-merge

#2033 added missing return value + minor changes
  xml/Microsoft.Build.Tasks/ResolveAssemblyReference.xml
Labels: migration-fixes

#2034 Replaced dropped cross-references
  xml/System.Resources/MissingManifestResourceException.xml
  xml/System.Resources/ResXResourceReader.xml
  xml/System.Security/SecurityException.xml
Labels: migration-fixes

#2036 recover some dropout content
  xml/Microsoft.Build.BuildEngine/Project.xml
  xml/Microsoft.Build.Tasks.Xaml/GenerateTemporaryAssemblyTask.xml
  xml/Microsoft.CSharp/CSharpCodeProvider.xml
  xml/Microsoft.VisualBasic.CompilerServices/Operators.xml
Labels: migration-fixes

#2037 update engine value
  docfx.json
Labels: :bookmark_tabs: Information Architecture

#2041 Fix typo
  xml/Microsoft.Build.Evaluation/ProjectCollection.xml
  xml/System.Data.Common/DbProviderFactories.xml
  xml/System.Data.SqlClient/SqlException.xml
  xml/System.Globalization/CalendarWeekRule.xml
  xml/System.ServiceModel.Channels/ConnectionOrientedTransportBindingElement.xml
  xml/System.ServiceModel.Channels/CustomBinding.xml
  xml/System.ServiceModel/NetTcpContextBinding.xml
  xml/System.Xml.Serialization.Configuration/DateTimeSerializationSection+DateTimeSerializationMode.xml
  xml/System.Xml.Serialization.Configuration/SchemaImporterExtensionElement.xml
  xml/System.Xml.Serialization.Configuration/SchemaImporterExtensionsSection.xml
Labels: verify-build-before-merge

#1979 Updates for new Japanese calendar era
  xml/System.Globalization/Calendar.xml
  xml/System.Globalization/JapaneseCalendar.xml
Labels: verify-build-before-merge

#2064 Added some trydotnet to System.String
  xml/System/String.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, example-make-interactive

#2063 Remove unused memory stream
  xml/System.Speech.Synthesis/SpeechSynthesizer.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2071 More interactive support for System.String
  xml/System/String.xml
Labels: example-make-interactive

#2099 Fix casing of case-sensitive switch
  xml/System.Net.Http/HttpClient.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2121 Update Form.xml
  xml/System.Windows.Forms/Form.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2179 typo: indes -> indexes
  xml/System.Collections.Immutable/IImmutableList`1.xml
Labels: verify-build-before-merge

#2180 typo: begining -> beginning
  xml/System.Configuration.Install/InstallerCollection.xml
Labels: verify-build-before-merge

#2181 typo: succesfully -> successfully
  xml/System.Collections.Concurrent/ConcurrentQueue`1.xml
  xml/System.Collections.Concurrent/ConcurrentStack`1.xml
  xml/System.Messaging/MessageEnumerator.xml
Labels: verify-build-before-merge

#2183 typo: Colletion -> Collection
  xml/System.Collections.Generic/Dictionary`2+KeyCollection.xml
  xml/System.Collections.Generic/Dictionary`2+ValueCollection.xml
  xml/System.Collections.Generic/Queue`1.xml
Labels: verify-build-before-merge

#2182 typo: sychronize -> synchronize
  xml/System.ComponentModel/IBindingList.xml
  xml/System.Threading/Thread.xml
  xml/System.Threading/Timeout.xml
Labels: verify-build-before-merge

#2184 typo: dictonary -> dictionary
  xml/System.Collections.Immutable/ImmutableSortedDictionary.xml
Labels: verify-build-before-merge

#2185 typo: inport -> import
  xml/System.ComponentModel.Composition/AttributedModelServices.xml
Labels: verify-build-before-merge

#2186 typo: Resturns -> Returns
  xml/System.ComponentModel/DependencyPropertyDescriptor.xml
Labels: verify-build-before-merge

#2187 typo: Thismethod -> This method
  xml/System.Collections.Specialized/StringCollection.xml
Labels: verify-build-before-merge

#2188 typo: committ -> commit
  xml/System.Configuration.Install/Installer.xml
Labels: verify-build-before-merge

#2189 typo: accessd -> accessed
  xml/System.Collections.Concurrent/BlockingCollection`1.xml
Labels: verify-build-before-merge

#2191 typo: Srevices -> Services
  xml/System.DirectoryServices/DirectoryServicesPermissionAccess.xml
Labels: verify-build-before-merge

#2193 typo: dtabase -> database
  xml/System.Data.Linq/ObjectChangeConflict.xml
Labels: verify-build-before-merge

#2152 XmlSerializer.xml — fix cache example
  xml/System.Xml.Serialization/XmlSerializer.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#2190 typo: objets -> objects
  xml/System.Collections.Generic/List`1.xml
Labels: verify-build-before-merge

#2120 Add reference to `ISOWeek`
  xml/System.Globalization/CalendarWeekRule.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#2155 typo: hander -> handler
  xml/System.Activities.Tracking/FaultPropagationQuery.xml
  xml/System.ComponentModel.Design/EventBindingService.xml
  xml/System.Reflection/EventInfo.xml
  xml/System.Speech.Recognition/SpeechRecognitionEngine.xml
  xml/System.Web/IHttpAsyncHandler.xml
  xml/System.Windows.Input/ExecutedRoutedEventArgs.xml
  xml/System.Windows.Media.Animation/Clock.xml
  xml/System.Windows.Media.Animation/Timeline.xml
  xml/System.Windows/PresentationSource.xml
Labels: verify-build-before-merge

#2044 Forbidden link
  xml/System.Dynamic/DynamicObject.xml
Labels: changes-addressed

#2008 Add content for System.Runtime.Intrinsics APIs
  xml/System.Runtime.Intrinsics.Arm.Arm64/Aes.xml
  xml/System.Runtime.Intrinsics.Arm.Arm64/Base.xml
  xml/System.Runtime.Intrinsics.Arm.Arm64/Sha1.xml
  xml/System.Runtime.Intrinsics.Arm.Arm64/Sha256.xml
  xml/System.Runtime.Intrinsics.Arm.Arm64/Simd.xml
  xml/System.Runtime.Intrinsics.X86/Aes.xml
  xml/System.Runtime.Intrinsics.X86/Avx.xml
  xml/System.Runtime.Intrinsics.X86/Avx2.xml
  xml/System.Runtime.Intrinsics.X86/Bmi1+X64.xml
  xml/System.Runtime.Intrinsics.X86/Bmi1.xml
  xml/System.Runtime.Intrinsics.X86/Bmi2+X64.xml
  xml/System.Runtime.Intrinsics.X86/Bmi2.xml
  xml/System.Runtime.Intrinsics.X86/FloatComparisonMode.xml
  xml/System.Runtime.Intrinsics.X86/Fma.xml
  xml/System.Runtime.Intrinsics.X86/Lzcnt+X64.xml
  xml/System.Runtime.Intrinsics.X86/Lzcnt.xml
  xml/System.Runtime.Intrinsics.X86/Pclmulqdq.xml
  xml/System.Runtime.Intrinsics.X86/Popcnt+X64.xml
  xml/System.Runtime.Intrinsics.X86/Popcnt.xml
  xml/System.Runtime.Intrinsics.X86/Sse+X64.xml
  xml/System.Runtime.Intrinsics.X86/Sse.xml
  xml/System.Runtime.Intrinsics.X86/Sse2+X64.xml
  xml/System.Runtime.Intrinsics.X86/Sse2.xml
  xml/System.Runtime.Intrinsics.X86/Sse3.xml
  xml/System.Runtime.Intrinsics.X86/Sse41+X64.xml
  xml/System.Runtime.Intrinsics.X86/Sse41.xml
  xml/System.Runtime.Intrinsics.X86/Sse42+X64.xml
  xml/System.Runtime.Intrinsics.X86/Sse42.xml
  xml/System.Runtime.Intrinsics.X86/Ssse3.xml
  xml/System.Runtime.Intrinsics/Vector128.xml
  xml/System.Runtime.Intrinsics/Vector128`1.xml
  xml/System.Runtime.Intrinsics/Vector256.xml
  xml/System.Runtime.Intrinsics/Vector256`1.xml
  xml/System.Runtime.Intrinsics/Vector64.xml
  xml/System.Runtime.Intrinsics/Vector64`1.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content
