Repository dotnet/dotnet-api-docs, pull requests merged in 2019-11, with the labels that each got.

#3237 Add documentations for System.Data.SqlDataReader
  xml/System.Data.Common/DbDataReader.xml
  xml/System.Data.SqlClient/SqlDataReader.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content

#3412 Document System.IO.Enumeration.FileSystemEnumerator
  xml/System.IO.Enumeration/FileSystemEnumerator`1.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content

#3236 Add missing System.Text docs
  xml/System.Text/CodePagesEncodingProvider.xml
  xml/System.Text/Decoder.xml
  xml/System.Text/Encoder.xml
  xml/System.Text/Encoding.xml
  xml/System.Text/StringBuilder.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge

#3394 Fix a few complex generic <see cref /> references
  xml/System.Data.Objects.DataClasses/StructuralObject.xml
  xml/System.Numerics/Vector.xml
  xml/System.Reflection/MetadataLoadContext.xml
  xml/System.Resources.Extensions/PreserializedResourceWriter.xml
Labels: verify-build-before-merge

#3352 FileStream constructor fix for FileSecurity
  xml/System.IO/FileStream.xml
Labels: doc-bug, verify-build-before-merge

#3379 Document System.IO.Compression.Brotli.BrotliDecoder
  xml/System.IO.Compression/BrotliDecoder.xml
Labels: :checkered_flag: Release: .NET Core 2.x, changes-addressed, new-content, verify-build-before-merge

#3441 Document OdbcParameter.Offset
  xml/System.Data.Odbc/OdbcParameter.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content

#3443 set default devlang
  docfx.json
Labels: verify-build-before-merge

#3413 Document System.IO.Enumeration.FileSystemEnumerable
  xml/System.IO.Enumeration/FileSystemEnumerable`1.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge

#3438 Document System.DateTime.ParseExact method overloads that receive Spans
  xml/System/DateTime.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3437 Document Parse method overloads that take a Span in System types
  xml/System/Boolean.xml
  xml/System/Byte.xml
  xml/System/DateTimeOffset.xml
  xml/System/Decimal.xml
  xml/System/Double.xml
  xml/System/Guid.xml
  xml/System/Int16.xml
  xml/System/Int32.xml
  xml/System/Int64.xml
  xml/System/SByte.xml
  xml/System/Single.xml
  xml/System/TimeSpan.xml
  xml/System/UInt16.xml
  xml/System/UInt32.xml
  xml/System/UInt64.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3436 Document TryFormat methods in System types
  xml/System/Boolean.xml
  xml/System/Byte.xml
  xml/System/DateTime.xml
  xml/System/DateTimeOffset.xml
  xml/System/Decimal.xml
  xml/System/Double.xml
  xml/System/Guid.xml
  xml/System/Int16.xml
  xml/System/Int32.xml
  xml/System/Int64.xml
  xml/System/SByte.xml
  xml/System/Single.xml
  xml/System/TimeSpan.xml
  xml/System/UInt16.xml
  xml/System/UInt32.xml
  xml/System/UInt64.xml
  xml/System/Version.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3435 Document TryParseExact Span method overloads in System date and time types
  xml/System/DateTime.xml
  xml/System/DateTimeOffset.xml
  xml/System/TimeSpan.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3431 Document TryGetValue from System.Collections.ObjectModel.KeyedCollection
  xml/System.Collections.ObjectModel/KeyedCollection`2.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3433 Document TryParse Span method overloads for System.B-G
  xml/System/Boolean.xml
  xml/System/Byte.xml
  xml/System/DateTime.xml
  xml/System/DateTimeOffset.xml
  xml/System/Decimal.xml
  xml/System/Double.xml
  xml/System/Enum.xml
  xml/System/Guid.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge

#3452 Document System.Globalization.UnicodeCategory.GetUnicodeCategory(int codePoint)
  xml/System.Globalization/CharUnicodeInfo.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3459 Document System.Collections.Generic.CollectionExtensions
  xml/System.Collections.Generic/CollectionExtensions.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3472 Test commit for .NET Framework project
  xml/ns-Microsoft.Aspnet.Snapin.xml
Labels: new-content, vendor-project

#3486 IntelliSense review fixes - Part 5
  xml/System.Threading.Channels/ChannelOptions.xml
  xml/System.Threading.Tasks/Task.xml
  xml/System.Web.Hosting/ProcessHost.xml
  xml/System.Web.ModelBinding/DataAnnotationsModelValidatorProvider.xml
  xml/System.Web.UI.WebControls.WebParts/WebPart.xml
  xml/System.Web.UI.WebControls.WebParts/WebPartPersonalization.xml
  xml/System.Web.UI/ScriptManager.xml
  xml/System.Windows.Automation.Peers/UIElementAutomationPeer.xml
  xml/System.Windows.Automation/GridPattern.xml
  xml/System.Windows.Forms.Automation/AutomationNotificationProcessing.xml
  xml/System.Windows.Forms/ControlBindingsCollection.xml
  xml/System.Windows.Forms/DataGridViewComboBoxCell+ObjectCollection.xml
  xml/System.Windows.Forms/RichTextBox.xml
  xml/System.Windows.Forms/WebBrowser.xml
  xml/System.Windows.Interop/ComponentDispatcher.xml
  xml/System.Windows.Threading/DispatcherTimer.xml
  xml/System.Workflow.ComponentModel/DependencyObject.xml
  xml/System.Xml/EntityHandling.xml
  xml/System.Xml/ValidationType.xml
  xml/System.Xml/XmlDictionaryWriter.xml
  xml/System.Xml/XmlReader.xml
  xml/System.Xml/XmlWriter.xml
Labels: migration-fixes

#3485 IntelliSense review fixes - Part 4
  xml/System.Security.Cryptography.Pkcs/CmsRecipientCollection.xml
  xml/System.Security.Cryptography.Pkcs/Pkcs12CertBag.xml
  xml/System.Security.Cryptography.Pkcs/Pkcs12Info.xml
  xml/System.Security.Cryptography.X509Certificates/CertificateRequest.xml
  xml/System.Security.Principal/NTAccount.xml
  xml/System.Security.Principal/SecurityIdentifier.xml
  xml/System.ServiceModel.Dispatcher/XPathMessageFilter.xml
  xml/System.ServiceModel/WorkflowServiceHost.xml
  xml/System.Text.Json/Utf8JsonReader.xml
  xml/System.Text.Json/Utf8JsonWriter.xml
  xml/System.Text.RegularExpressions/GroupCollection.xml
  xml/System.Text.RegularExpressions/RegexOptions.xml
  xml/System.Text.Unicode/UnicodeRange.xml
  xml/System.Text/ASCIIEncoding.xml
  xml/System.Text/Decoder.xml
  xml/System.Text/Encoder.xml
  xml/System.Text/Encoding.xml
  xml/System.Text/UTF32Encoding.xml
  xml/System.Text/UTF7Encoding.xml
  xml/System.Text/UTF8Encoding.xml
  xml/System.Text/UnicodeEncoding.xml
  xml/System.Threading/ManualResetEventSlim.xml
Labels: migration-fixes

#3484 IntelliSense review fixes - Part 3
  xml/System.Linq/Enumerable.xml
  xml/System.Messaging/MessageQueue.xml
  xml/System.Net.Http/HttpClient.xml
  xml/System.Net.Http/HttpResponseMessage.xml
  xml/System.Net.NetworkInformation/IPAddressCollection.xml
  xml/System.Net.PeerToPeer.Collaboration/PeerCollaborationPermission.xml
  xml/System.Net.PeerToPeer/PnrpPermission.xml
  xml/System.Net.Security/NegotiateStream.xml
  xml/System.Net.Security/SslStream.xml
  xml/System.Net.Sockets/NetworkStream.xml
  xml/System.Net.Sockets/Socket.xml
  xml/System.Net/FileWebRequest.xml
  xml/System.Net/IPAddress.xml
  xml/System.Printing/PrintQueue.xml
  xml/System.Reflection.Metadata/ManifestResource.xml
  xml/System.Reflection/MethodImplAttributes.xml
  xml/System.Resources.Extensions/PreserializedResourceWriter.xml
  xml/System.Runtime.CompilerServices/Unsafe.xml
  xml/System.Runtime.InteropServices/Marshal.xml
  xml/System.Security.Cryptography/AsnEncodedDataCollection.xml
  xml/System.Security.Cryptography/ECDiffieHellman.xml
  xml/System.Security.Cryptography/ECDsa.xml
Labels: migration-fixes

#3482 Intellisense review fixes - Part 1
  xml/Microsoft.Extensions.DependencyInjection/HttpClientBuilderExtensions.xml
  xml/System.Buffers/SequenceReader`1.xml
  xml/System.Collections/CollectionBase.xml
  xml/System.Collections/ReadOnlyCollectionBase.xml
  xml/System.Data.Common/DbCommand.xml
  xml/System.Data.Common/DbConnection.xml
  xml/System.Data.Common/DbDataReader.xml
  xml/System.Data.Common/DbTransaction.xml
  xml/System.DirectoryServices.ActiveDirectory/ActiveDirectorySchedule.xml
  xml/System.DirectoryServices.ActiveDirectory/ActiveDirectorySchemaClass.xml
  xml/System.DirectoryServices.ActiveDirectory/ActiveDirectorySite.xml
  xml/System.DirectoryServices.ActiveDirectory/ActiveDirectorySiteLink.xml
  xml/System.DirectoryServices.ActiveDirectory/ApplicationPartition.xml
  xml/System.DirectoryServices/ActiveDirectoryRights.xml
  xml/System.DirectoryServices/AuthenticationTypes.xml
  xml/System/GCNotificationStatus.xml
  xml/System/Index.xml
  xml/System/ReadOnlySpan`1.xml
  xml/System/String.xml
  xml/System/Type.xml
Labels: migration-fixes

#3457 Document System.Buffers.Binary namespace
  xml/ns-System.Buffers.Binary.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3453 Document System.Diagnostics.Tracing.EventCounter.Dispose
  xml/System.Diagnostics.Tracing/EventCounter.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3488 Remove extra > in documentation
  xml/System.Net.Mail/SmtpClient.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#3483 Intellisense review fixes - Part 2
  _zip/missingapi.yml
  xml/System.Buffers/ArrayBufferWriter`1.xml
  xml/System.ComponentModel.DataAnnotations/DisplayAttribute.xml
  xml/System.ComponentModel/VersionConverter.xml
  xml/System.Composition.Hosting.Core/CompositionOperation.xml
  xml/System.Data.SqlClient/SqlConnection.xml
  xml/System.Data/XmlReadMode.xml
  xml/System.Device.Location/GeoCoordinate.xml
  xml/System.Diagnostics/PresentationTraceSources.xml
  xml/System.DirectoryServices.ActiveDirectory/ReplicationConnection.xml
  xml/System.IO.Compression/BrotliDecoder.xml
  xml/System.IO.Compression/BrotliEncoder.xml
  xml/System.IO.Compression/DeflateStream.xml
  xml/System.IO.Compression/ZipFileExtensions.xml
  xml/System.IO.Packaging/PackageRelationshipSelector.xml
  xml/System.IO.Pipelines/PipeWriter.xml
  xml/System.IO.Pipes/PipeStream.xml
  xml/System/ArraySegment`1.xml
  xml/System/HashCode.xml
  xml/System/Span`1.xml
  xml/System/Uri.xml
Labels: migration-fixes, verify-build-before-merge

#3233 Clarify Path.GetPathRoot return value when path is effectively empty
  xml/System.IO/Path.xml
Labels: doc-enhancement, verify-build-before-merge

#3434 Document TryParse Span method overloads for System.I-U
  xml/System/Int16.xml
  xml/System/Int32.xml
  xml/System/Int64.xml
  xml/System/SByte.xml
  xml/System/Single.xml
  xml/System/TimeSpan.xml
  xml/System/UInt16.xml
  xml/System/UInt32.xml
  xml/System/UInt64.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge

#3454 Document System.Reflection.PortableExecutable.SubSystem enum
  xml/System.Reflection.PortableExecutable/Subsystem.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge

#3495 Document System.IO.Pipelines.Pipe
  xml/System.IO.Pipelines/Pipe.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge

#3492 Document System.IO.Pipelines.PipeScheduler
  xml/System.IO.Pipelines/PipeScheduler.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3501 remove tla_wpfxmlnsv1 token
  includes/tlasharptla-wpfxmlnsv1-md.md
  xml/System.Windows.Markup/TypeExtension.xml
  xml/System.Windows.Markup/XmlnsDictionary.xml
Labels: loc, verify-build-before-merge

#3500 Add missing DateTime/DateTimeOffset/TimeSpan docs
  xml/System/DateTime.xml
  xml/System/DateTimeOffset.xml
  xml/System/TimeSpan.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3478 Object.ToString -- updating for Try .NET
  xml/System/Object.xml
Labels: vendor-project

#3489 add see also link
  xml/System.Net/SecurityProtocolType.xml
Labels: verify-build-before-merge

#3491 Document System.IO.Pipelines.ReadResult
  xml/System.IO.Pipelines/ReadResult.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3493 Document System.IO.Pipelines.PipeReader
  xml/System.IO.Pipelines/PipeReader.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3497 Document System.IO.Pipelines namespace
  xml/ns-System.IO.Pipelines.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3511 Address missed suggestion for Pipelines namespace
  xml/ns-System.IO.Pipelines.xml
Labels: doc-enhancement

#3449 US 1621691 - Loc content review.
  xml/System.Net.WebSockets/ClientWebSocket.xml
Labels: :card_file_box: Technology - NCL

#3496 Document System.IO.Pipelines.FlushResult
  xml/System.IO.Pipelines/FlushResult.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3510 Fix reference to CancelPendingRead
  xml/System.IO.Pipelines/ReadResult.xml
Labels: doc-bug

#3214 Automatically port Reflection.Metadata.Ecma335.MetadataBuilder
  xml/System.Reflection.Metadata.Ecma335/MetadataBuilder.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3499 Document EIIs of integer types (IComparable/IConvertible)
  xml/System/Int16.xml
  xml/System/Int32.xml
  xml/System/Int64.xml
  xml/System/UInt16.xml
  xml/System/UInt32.xml
  xml/System/UInt64.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3479 Enumerable.xml -- updating Select for Try .NET
  xml/System.Linq/Enumerable.xml
Labels: vendor-project

#3494 Document System.IO.Pipelines.PipeOptions
  xml/System.IO.Pipelines/PipeOptions.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge

#3505 Document System.IO.DirectoryInfo
  xml/System.IO/DirectoryInfo.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3527 Document System.IO.EnumerationOptions
  xml/System.IO/EnumerationOptions.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3528 Document System.IO.MatchCasing
  xml/System.IO/MatchCasing.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3529 Document System.IO.MatchType
  xml/System.IO/MatchType.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3536 Document System.Type.GetMethod and GetMethodImpl
  xml/System/Type.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content

#3535 Document System.IO.Enumeration namespace
  xml/ns-System.IO.Enumeration.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3439 Update RSACryptoServiceProvider.xml
  xml/System.Security.Cryptography/RSACryptoServiceProvider.xml
Labels: verify-build-before-merge

#3212 Automatically port Reflection.Metadata.Ecma335 L-Metadata APIs
  xml/System.Reflection.Metadata.Ecma335/LabelHandle.xml
  xml/System.Reflection.Metadata.Ecma335/LiteralEncoder.xml
  xml/System.Reflection.Metadata.Ecma335/MetadataAggregator.xml
  xml/System.Reflection.Metadata.Ecma335/MetadataReaderExtensions.xml
  xml/System.Reflection.Metadata.Ecma335/MetadataRootBuilder.xml
  xml/System.Reflection.Metadata.Ecma335/MetadataSizes.xml
  xml/System.Reflection.Metadata.Ecma335/MetadataTokens.xml
Labels: :checkered_flag: Release: .NET Core 2.x, changes-addressed, new-content, verify-build-before-merge

#3543 Clarify LazyInitialize.EnsureInitialized
  xml/System.Threading/LazyInitializer.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3532 Document System.IO.MemoryStream
  xml/System.IO/MemoryStream.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content

#3545 Remove outdated comment
  xml/System.Threading/Thread.xml
Labels: verify-build-before-merge

#3460 Add references to new F# Console method examples
  xml/System/Console.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3530 Document System.IO.StreamReader
  xml/System.IO/StreamReader.xml
Labels: :checkered_flag: Release: .NET Core 2.x, changes-addressed, new-content, verify-build-before-merge

#3476 Add missing documentation for the CryptographicOperations class.
  xml/System.Security.Cryptography/CryptographicOperations.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content

#3533 Document System.IO.TextReader
  xml/System.IO/TextReader.xml
Labels: :checkered_flag: Release: .NET Core 2.x, changes-addressed, new-content, verify-build-before-merge

#3548 Document System.Convert
  xml/System/Convert.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge, waiting-on-reviews

#3556 Document System.ArraySegment and its enumerator
  xml/System/ArraySegment`1+Enumerator.xml
  xml/System/ArraySegment`1.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3531 Missing API docs part 1 - SA
  xml/Microsoft.Build.Tasks/GenerateManifestBase.xml
  xml/Microsoft.CSharp.Activities/CSharpReference`1.xml
  xml/Microsoft.CSharp/ErrorLevel.xml
  xml/Microsoft.IE/Manager+URL_CANONFLAGS.xml
  xml/Microsoft.IE/Manager+URL_IS.xml
  xml/Microsoft.IE/Manager+URL_PART.xml
  xml/Microsoft.IE/SecureFactory+WININET_CACHE_ENTRY.xml
  xml/Microsoft.JScript/IDebugConvert.xml
  xml/Microsoft.JScript/JScriptException.xml
  xml/Microsoft.VisualBasic.CompilerServices/ProjectData.xml
  xml/Microsoft.VisualBasic.Vsa/VsaEngine.xml
  xml/Microsoft.VisualBasic.Vsa/VsaGlobalItem.xml
Labels: new-content, vendor-project

#3555 Add documentation for System.Net.WebSockets APIs introduced in 2.x
  xml/System.Net.WebSockets/ClientWebSocketOptions.xml
  xml/System.Net.WebSockets/ValueWebSocketReceiveResult.xml
  xml/System.Net.WebSockets/WebSocket.xml
Labels: :checkered_flag: Release: .NET Core 2.x, changes-addressed, new-content

#3504 Document System.IO.Directory
  xml/System.IO/Directory.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3280 Added documentation for APIs in System.Net namespace introduced in 2.x
  xml/System.Net/FtpWebResponse.xml
  xml/System.Net/HttpVersion.xml
  xml/System.Net/IPAddress.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3469 Add missing documentation for SymmetricAlgorithm types
  xml/System.Security.Cryptography/Aes.xml
  xml/System.Security.Cryptography/AesCryptoServiceProvider.xml
  xml/System.Security.Cryptography/DESCryptoServiceProvider.xml
  xml/System.Security.Cryptography/RijndaelManaged.xml
  xml/System.Security.Cryptography/SymmetricAlgorithm.xml
  xml/System.Security.Cryptography/TripleDES.xml
  xml/System.Security.Cryptography/TripleDESCryptoServiceProvider.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content

#3498 Add missing documentation for DSA types
  xml/System.Security.Cryptography/DSA.xml
  xml/System.Security.Cryptography/DSACng.xml
  xml/System.Security.Cryptography/DSACryptoServiceProvider.xml
  xml/System.Security.Cryptography/DSAOpenSsl.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge

#3537 Func`2.xml -- updating for Try .NET
  xml/System/Func`2.xml
Labels: vendor-project

#3542 Add missing, and update existing, ECDH API documentation.
  xml/System.Security.Cryptography/ECDiffieHellman.xml
  xml/System.Security.Cryptography/ECDiffieHellmanCng.xml
  xml/System.Security.Cryptography/ECDiffieHellmanOpenSsl.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3490 DateTime.xml -- .ctor, Compare, and Ticks -- updating for Try .NET
  xml/System/DateTime.xml
Labels: :construction: Hold for related PR, vendor-project

#3553 Add documentation for WebSocketProtocol class and its members.
  xml/System.Net.WebSockets/WebSocketProtocol.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge

#3564 Add missing, and update existing, ECDsa API documentation
  xml/System.Security.Cryptography/ECDsa.xml
  xml/System.Security.Cryptography/ECDsaCng.xml
  xml/System.Security.Cryptography/ECDsaOpenSsl.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3569 Update API for SameSitemode
  xml/System.Web/HttpCookie.xml
  xml/System.Web/SameSiteMode.xml
Labels: P0
