Repository dotnet/dotnet-api-docs, pull requests merged in 2019-04, with the labels that each got.

#2219 Add link to ISO/IEC/IEEE 60559:2011
  xml/System/Object.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2216 Updated OSPlatform type
  xml/System.Runtime.InteropServices/OSPlatform.xml
Labels: verify-build-before-merge

#2055 Update BasicHttpBinding.xml
  xml/System.ServiceModel/BasicHttpBinding.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, changes-addressed

#2225 fixing loc issue per task 1494310
  includes/xsltransform-script.md
  xml/System.Xml.Xsl/XslTransform.xml
Labels: verify-build-before-merge

#2230 Fixed clt opcode page
  xml/System.Reflection.Emit/OpCodes.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2233 Note that shutdown finalization is .NET Framework only
  xml/System/Environment.xml
Labels: verify-build-before-merge

#2243 fix sample inversion
  xml/System.Net/HttpListener.xml
Labels: doc-bug

#2241 remove dupe sentence + mig fix
  xml/System/String.xml
Labels: migration-fixes

#2258 Fixes dotnet/dotnet-api-docs#1512
  xml/System.IO/File.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#1616 Move notes to inheritors to inside CDATA block
  xml/System.Windows/ContentElement.xml
Labels: loc

#2274 Fix CallingConvention examples
  xml/System.Runtime.InteropServices/DllImportAttribute.xml
Labels: migration-fixes

#2276 System.Security.Permissions missing documentation
  xml/System.Security.Permissions/PrincipalPermission.xml
  xml/System.Security.Permissions/RegistryPermission.xml
  xml/System.Security.Permissions/StrongNamePublicKeyBlob.xml
Labels: new-content

#2059 Document that StreamWriter.Dispose flushes
  xml/System.IO/StreamWriter.xml
Labels: waiting-on-reviews

#2281 migrate some API content added by latest mdoc version
  xml/System.Windows.Controls.Primitives/Selector.xml
  xml/System.Windows.Controls.Ribbon/RibbonControlService.xml
  xml/System.Windows.Controls.Ribbon/RibbonQuickAccessToolBar.xml
  xml/System.Windows.Controls/Validation.xml
  xml/System.Windows.Navigation/BaseUriHelper.xml
  xml/System.Windows/VisualStateManager.xml
Labels: migration-fixes

#2284 Fix typo.
  xml/System/AccessViolationException.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2282 Add links to specific overloads of ZipFileExtensions
  xml/System.IO.Compression/ZipArchive.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#1880 add content for System.Text.Json APIs
  xml/System.Text.Json/JsonCommentHandling.xml
  xml/System.Text.Json/JsonReaderException.xml
  xml/System.Text.Json/JsonReaderOptions.xml
  xml/System.Text.Json/JsonReaderState.xml
  xml/System.Text.Json/JsonTokenType.xml
  xml/System.Text.Json/JsonWriterOptions.xml
  xml/System.Text.Json/JsonWriterState.xml
  xml/System.Text.Json/Utf8JsonReader.xml
  xml/System.Text.Json/Utf8JsonWriter.xml
Labels: :checkered_flag: Release: .NET Core 3.0

#2286 test char
  xml/System/UriKind.xml
Labels: :bookmark_tabs: Information Architecture

#2260 Add missing documentation for TryAdd API
  xml/System.Collections.Generic/Dictionary`2.xml
Labels: verify-build-before-merge

#2253 Documented some new 4.8 APIs
  xml/System.Reflection/MethodImplAttributes.xml
  xml/System.Runtime.CompilerServices/MethodImplOptions.xml
  xml/System.Threading/Interlocked.xml
Labels: :checkered_flag: Release: .NET Framework 4.8

#2030 Update FileAttributes.xml
  xml/System.IO/FileAttributes.xml
Labels: waiting-on-reviews

#2294 Update live with current master
  xml/System.Collections.Generic/Dictionary`2.xml
  xml/System.Data.Services.Client/DataServiceCollection`1.xml
  xml/System.Data.Services.Client/DataServiceContext.xml
  xml/System.Data.Services.Client/DataServiceQueryContinuation`1.xml
  xml/System.Data.Services.Client/DataServiceQuery`1.xml
  xml/System.Data.Services.Client/EntityChangedParams.xml
  xml/System.Data.Services.Client/EntityCollectionChangedParams.xml
  xml/System.Data.Services.Client/QueryOperationResponse`1.xml
  xml/System.Data.Services.Common/EntityPropertyMappingAttribute.xml
  xml/System.Data.Services/DataServiceConfiguration.xml
  xml/System.IO.Compression/ZipArchive.xml
  xml/System.IO/FileAttributes.xml
  xml/System.Reflection/MethodImplAttributes.xml
  xml/System.Runtime.CompilerServices/MethodImplOptions.xml
  xml/System.Text.Json/JsonCommentHandling.xml
  xml/System.Text.Json/JsonReaderException.xml
  xml/System.Text.Json/JsonReaderOptions.xml
  xml/System.Text.Json/JsonReaderState.xml
  xml/System.Text.Json/JsonTokenType.xml
  xml/System.Text.Json/JsonWriterOptions.xml
  xml/System.Text.Json/JsonWriterState.xml
  xml/System.Text.Json/Utf8JsonReader.xml
  xml/System.Text.Json/Utf8JsonWriter.xml
  xml/System.Threading/Interlocked.xml
  xml/System/UriKind.xml
Labels: verify-build-before-merge

#2203 fix possible misunderstanding (Return value of Current property and Entry property at IDictionaryEnumerator Interface)
  xml/System.Collections/IDictionaryEnumerator.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#2297 Updated FileAttributes for Linux and macOS
  xml/System.IO/FileAttributes.xml
Labels: verify-build-before-merge

#2299 Typos in includes/calendar-era.md
  includes/calendar-era.md
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2301 Update Windows API terms
  xml/Microsoft.Win32/RegistryValueKind.xml
  xml/System.Diagnostics/EventLogEntry.xml
  xml/System.Diagnostics/Stopwatch.xml
  xml/System.Drawing.Printing/StandardPrintController.xml
  xml/System.Drawing/Icon.xml
  xml/System.Globalization/CultureAndRegionInfoBuilder.xml
  xml/System.Reflection.Emit/ModuleBuilder.xml
  xml/System.Reflection/ImageFileMachine.xml
  xml/System.Runtime.CompilerServices/CompilerMarshalOverride.xml
  xml/System.Runtime.InteropServices/CriticalHandle.xml
  xml/System.Runtime.InteropServices/DllImportAttribute.xml
  xml/System.Runtime.InteropServices/SafeHandle.xml
  xml/System.Runtime.InteropServices/UnmanagedFunctionPointerAttribute.xml
  xml/System.Security.Authentication.ExtendedProtection/TokenBinding.xml
  xml/System.Security.Principal/WindowsIdentity.xml
  xml/System.Threading/Overlapped.xml
  xml/System.Threading/ThreadPool.xml
  xml/System.Web.Configuration/WebConfigurationManager.xml
  xml/System.Web/HttpException.xml
  xml/System.Windows.Forms/Form.xml
  xml/System.Windows.Forms/HtmlWindow.xml
  xml/System.Windows.Forms/IWin32Window.xml
  xml/System.Windows.Forms/IWindowTarget.xml
  xml/System.Windows.Forms/Keys.xml
  xml/System.Windows.Forms/NativeWindow.xml
  xml/System/GC.xml
  xml/ns-System.Windows.Interop.xml
Labels: verify-build-before-merge

#2293 Update UpdatePanel.xml
  xml/System.Web.UI/UpdatePanel.xml
Labels: verify-build-before-merge

#2309 Port System.Security.Cryptography.Pkcs source comments to Docs
  xml/System.Security.Cryptography.Pkcs/Pkcs12CertBag.xml
  xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampRequest.xml
  xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampToken.xml
Labels: new-content

#2316 Documented Unsafe.Unbox method
  xml/System.Runtime.CompilerServices/Unsafe.xml
Labels: verify-build-before-merge

#2334 Documented 2 new members for .NET Framework 4.8
  xml/System.Windows.Forms.DataVisualization.Charting/Chart.xml
Labels: :checkered_flag: Release: .NET Framework 4.8

#2351 Minor grammar correction in System.Threading.Tasks/Task.xml
  xml/System.Threading.Tasks/Task.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2356 Fix summary of Binding.PropertyName
  xml/System.Windows.Forms/Binding.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2357 Fix broken link
  xml/System/Object.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2308 Ported missing System.Threading.Channels comments from source to Docs
  xml/System.Threading.Channels/ChannelReader`1.xml
  xml/System.Threading.Channels/Channel`2.xml
Labels: new-content

#2311 Port System.Text.RegularExpressions source comments to Docs
  xml/System.Text.RegularExpressions/Regex.xml
Labels: doc-enhancement

#2296 Porting source comments from System.IO.Compression
  xml/System.IO.Compression/ZipFile.xml
  xml/System.IO.Compression/ZipFileExtensions.xml
Labels: new-content

#2340 US-80785 fixes - add missing content
  xml/Microsoft.VisualBasic.Vsa/VsaEngine.xml
  xml/Microsoft.Vsa/BaseVsaStartup.xml
  xml/Microsoft.Win32/RegistryKey.xml
  xml/System.Collections.Generic/SortedDictionary`2+ValueCollection.xml
  xml/System.ComponentModel.Design.Serialization/CodeDomSerializer.xml
  xml/System.ComponentModel.Design/ByteViewer.xml
  xml/System.Data.Common/DbDataAdapter.xml
  xml/System.Data.Odbc/OdbcCommand.xml
  xml/System.Data.Odbc/OdbcCommandBuilder.xml
  xml/System.Data.Odbc/OdbcConnection.xml
  xml/System.Data.Odbc/OdbcDataReader.xml
  xml/System.Data.Odbc/OdbcException.xml
  xml/System.Data.Odbc/OdbcTransaction.xml
  xml/System.Data.OleDb/OleDbCommand.xml
  xml/System.Data.OleDb/OleDbCommandBuilder.xml
  xml/System.Data.OleDb/OleDbConnection.xml
  xml/System.Data.OleDb/OleDbDataReader.xml
  xml/System.Data.OleDb/OleDbException.xml
  xml/System.Data.OleDb/OleDbPermission.xml
  xml/System.Data.OleDb/OleDbTransaction.xml
  xml/System.Data.OracleClient/OracleConnection.xml
  xml/System.Data.SqlClient/SqlConnection.xml
  xml/System.Data.SqlClient/SqlException.xml
  xml/System.Globalization/GregorianCalendar.xml
  xml/System.Security.Cryptography/CryptoAPITransform.xml
  xml/System.Security.Cryptography/CryptoStream.xml
  xml/System.Security.Cryptography/HMACSHA1.xml
  xml/System.Security.Cryptography/PasswordDeriveBytes.xml
  xml/System.Security.Cryptography/SHA1CryptoServiceProvider.xml
  xml/System.Threading/RegisteredWaitHandle.xml
  xml/System.Threading/Timer.xml
  xml/System.Web.Services.Description/Message.xml
  xml/System.Web.Services.Description/MessageBinding.xml
  xml/System.Web.Services.Description/MessagePart.xml
  xml/System.Web.Services.Description/Operation.xml
  xml/System.Web.Services.Description/OperationBinding.xml
  xml/System.Web.Services.Description/OperationMessage.xml
  xml/System.Web.Services.Description/Port.xml
  xml/System.Web.Services.Description/PortType.xml
  xml/System.Web.Services.Description/ServiceDescription.xml
  xml/System.Web.UI.WebControls/AdRotator.xml
  xml/System.Web.UI.WebControls/DropDownList.xml
  xml/System.Web.UI.WebControls/ListBox.xml
  xml/System.Web.UI.WebControls/ListControl.xml
  xml/System.Web.UI.WebControls/ValidatedControlConverter.xml
  xml/System.Web/HttpBrowserCapabilities.xml
  xml/System.Windows.Forms.Design/ComponentTray.xml
  xml/System.Windows.Forms.Design/ControlDesigner.xml
  xml/System.Windows.Forms.Design/ParentControlDesigner.xml
  xml/System.Xml.Serialization/XmlTypeMapping.xml
  xml/System.Xml.Xsl/XsltCompileException.xml
  xml/System.Xml/XmlTextReader.xml
  xml/System.Xml/XmlValidatingReader.xml
Labels: migration-fixes, verify-build-before-merge

#2366 Revised ValidationContext.MemberName
  xml/System.ComponentModel.DataAnnotations/ValidationContext.xml
Labels: :checkered_flag: Release: .NET Framework 4.8

#2306 Ported System.Collections source code comments to Docs
  xml/System.Collections.Concurrent/BlockingCollection`1.xml
  xml/System.Collections.Concurrent/ConcurrentDictionary`2.xml
  xml/System.Collections.Immutable/IImmutableQueue`1.xml
  xml/System.Collections.Immutable/IImmutableStack`1.xml
  xml/System.Collections.Immutable/ImmutableArray.xml
  xml/System.Collections.Immutable/ImmutableArray`1+Builder.xml
  xml/System.Collections.Immutable/ImmutableArray`1.xml
  xml/System.Collections.Immutable/ImmutableDictionary`2+Builder.xml
  xml/System.Collections.Immutable/ImmutableInterlocked.xml
  xml/System.Collections.Immutable/ImmutableList`1+Builder.xml
  xml/System.Collections.Immutable/ImmutableList`1.xml
  xml/System.Collections.Immutable/ImmutableQueue.xml
  xml/System.Collections.Immutable/ImmutableQueue`1.xml
  xml/System.Collections.Immutable/ImmutableSortedDictionary`2+Builder.xml
  xml/System.Collections.Immutable/ImmutableSortedDictionary`2.xml
  xml/System.Collections.Immutable/ImmutableSortedSet`1+Builder.xml
  xml/System.Collections.Immutable/ImmutableSortedSet`1.xml
  xml/System.Collections.Immutable/ImmutableStack.xml
  xml/System.Collections.Immutable/ImmutableStack`1.xml
Labels: verify-build-before-merge

#2317 Port System.Reflection source comments to Docs
  xml/System.Reflection/DispatchProxy.xml
  xml/System.Reflection/MetadataLoadContext.xml
Labels: verify-build-before-merge

#2304 Port System.IO.Pipelines source code comments to Docs
  xml/System.IO.Pipelines/PipeReader.xml
  xml/System.IO.Pipelines/PipeWriter.xml
  xml/System.IO.Pipelines/StreamPipeExtensions.xml
Labels: verify-build-before-merge

#2319 Port System.Net.WebSockets triple slash comments to Docs
  xml/System.Net.WebSockets/ValueWebSocketReceiveResult.xml
  xml/System.Net.WebSockets/WebSocket.xml
Labels: new-content, verify-build-before-merge

#2374 Added documentation for DataflowBlockOptions.EnsureOrdered
  xml/System.Threading.Tasks.Dataflow/DataflowBlockOptions.xml
Labels: changes-addressed

#2372 Fix a typo on System.IO.Path API docs
  xml/System.IO/Path.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2361 Add some api-docs for AssemblyDependencyResolver.
  xml/System.Runtime.Loader/AssemblyDependencyResolver.xml
Labels: changes-addressed, new-content
