Repository dotnet/dotnet-api-docs, pull requests merged in 2019-09, with the labels that each got.

#3097 Automatically port System.Xml.Linq.XDocument triple slash
  xml/System.Xml.Linq/XDocument.xml
Labels: waiting-on-reviews

#3121 remove extra spaces/wrong tag
  xml/System.Collections.Immutable/ImmutableArray`1.xml
Labels: migration-fixes

#3114 review msdn blogs links
  xml/System.Data.SqlClient/SqlColumnEncryptionCertificateStoreProvider.xml
  xml/System.Data.SqlClient/SqlColumnEncryptionCngProvider.xml
  xml/System.Data.SqlClient/SqlColumnEncryptionCspProvider.xml
  xml/System.Data.SqlClient/SqlColumnEncryptionKeyStoreProvider.xml
  xml/System.Data.SqlClient/SqlCommandColumnEncryptionSetting.xml
  xml/System.Data.SqlClient/SqlConnectionColumnEncryptionSetting.xml
  xml/System.Security.Cryptography/RSAParameters.xml
  xml/System.Text/Encoding.xml
  xml/System/OutOfMemoryException.xml
  xml/ns-System.Globalization.xml
Labels: verify-build-before-merge

#3095 Automatically port System.Runtime.Intrinsics.X86 triple slash comments
  xml/System.Runtime.Intrinsics.X86/Avx2.xml
  xml/System.Runtime.Intrinsics.X86/FloatComparisonMode.xml
  xml/System.Runtime.Intrinsics.X86/Sse.xml
  xml/System.Runtime.Intrinsics.X86/Sse2.xml
  xml/System.Runtime.Intrinsics.X86/Sse41.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#3125 Intrinsics: Enclose instructions with param, move comments to remarks
  xml/System.Runtime.Intrinsics.X86/Aes.xml
  xml/System.Runtime.Intrinsics.X86/Avx.xml
  xml/System.Runtime.Intrinsics.X86/Bmi1+X64.xml
  xml/System.Runtime.Intrinsics.X86/Bmi1.xml
  xml/System.Runtime.Intrinsics.X86/Bmi2+X64.xml
  xml/System.Runtime.Intrinsics.X86/Bmi2.xml
  xml/System.Runtime.Intrinsics.X86/Fma.xml
  xml/System.Runtime.Intrinsics.X86/Lzcnt+X64.xml
  xml/System.Runtime.Intrinsics.X86/Lzcnt.xml
  xml/System.Runtime.Intrinsics.X86/Pclmulqdq.xml
  xml/System.Runtime.Intrinsics.X86/Popcnt+X64.xml
  xml/System.Runtime.Intrinsics.X86/Popcnt.xml
  xml/System.Runtime.Intrinsics.X86/Sse+X64.xml
  xml/System.Runtime.Intrinsics.X86/Sse2+X64.xml
  xml/System.Runtime.Intrinsics.X86/Sse3.xml
  xml/System.Runtime.Intrinsics.X86/Sse41+X64.xml
  xml/System.Runtime.Intrinsics.X86/Sse42+X64.xml
  xml/System.Runtime.Intrinsics.X86/Sse42.xml
  xml/System.Runtime.Intrinsics.X86/Ssse3.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#3130 Fixed typo (atttributes)
  xml/System.Reflection.Metadata/ManifestResource.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3124 Space characters are encoded as '+'
  xml/System.Net/WebUtility.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3077 Additional tweaks to new System.Data async APIs
  xml/System.Data.Common/DbCommand.xml
  xml/System.Data.Common/DbConnection.xml
  xml/System.Data.Common/DbTransaction.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#3133 updated TryParse example for Try .NET
  xml/System/UInt32.xml
Labels: vendor-project

#3144 Update JsonSerializer docs for clarity.
  xml/System.Text.Json/JsonDocumentOptions.xml
  xml/System.Text.Json/JsonSerializer.xml
  xml/System.Text.Json/JsonValueKind.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#3150 Add some missing Json exceptions, fix spacing.
  xml/System.Text.Json/JsonDocument.xml
  xml/System.Text.Json/JsonElement.xml
Labels: :checkered_flag: Release: .NET Core 3.0, doc-enhancement

#3152 remove extra space
  xml/System.Text.Json/Utf8JsonWriter.xml
Labels: doc-enhancement

#2996 Add docs for HighDpiMode
  xml/System.Windows.Forms/Application.xml
  xml/System.Windows.Forms/HighDpiMode.xml
Labels: :card_file_box: Technology - WinForms, new-content, waiting-on-feedback

#3151 Automatically port System.Text.Encodings
  xml/System.Text.Encodings.Web/TextEncoder.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content, verify-build-before-merge

#3142 Update Utf8JsonReader ValueSpan, Sequence, and ValueTextEquals docs.
  xml/System.Text.Json/Utf8JsonReader.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#3143 Update Utf8JsonWriter for null strings, double/single formatting, and consistency.
  xml/System.Text.Json/JsonReaderOptions.xml
  xml/System.Text.Json/JsonWriterOptions.xml
  xml/System.Text.Json/Utf8JsonWriter.xml
Labels: :checkered_flag: Release: .NET Core 3.0, doc-enhancement, waiting-on-reviews

#3155 Further updates to Utf8JsonReader
  xml/System.Text.Json/Utf8JsonReader.xml
Labels: :checkered_flag: Release: .NET Core 3.0, doc-enhancement

#3158 fix IntelliSense tag
  xml/System.Collections.Immutable/ImmutableArray`1.xml
Labels: doc-bug

#3098 Automatically port System.Xml.Linq.XElement triple slash
  xml/System.Xml.Linq/XElement.xml
Labels: waiting-on-reviews

#3165 Updating IsControl Char page
  xml/System/Char.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3174 fix exception links
  xml/System.Text.Json/JsonSerializerOptions.xml
Labels: verify-build-before-merge

#3217 Spelling error
  xml/System/Environment.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3221 M39422: Fixing typo cakk ti/call to
  xml/System.Activities/UnhandledExceptionAction.xml
Labels: loc, verify-build-before-merge

#3176 Automatically port some remarks for System.Security.Cryptography (.NET Core 2.X)
  xml/System.Security.Cryptography/HashAlgorithmName.xml
  xml/System.Security.Cryptography/RSAEncryptionPaddingMode.xml
  xml/System.Security.Cryptography/RSASignaturePaddingMode.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3183 Automatically port Reflection.AssemblyHashAlgorithm
  xml/System.Reflection/AssemblyHashAlgorithm.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3187 Automatically port Collections.Immutable.ImmutableArray
  xml/System.Collections.Immutable/ImmutableArray`1.xml
  xml/System.Collections.Immutable/ImmutableList`1+Builder.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3179 Automatically port ReadOnlySpan.GetPinnableReference
  xml/System/ReadOnlySpan`1.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3185 Automatically port IO.Enumeration.FileSystemName remark
  xml/System.IO.Enumeration/FileSystemName.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3186 Automatically port Data.DataRowView remark and exception
  xml/System.Data/DataRowView.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3232 Document System.Version
  xml/System/Version.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content

#3243 L124989: Fixing CDATA formatting
  xml/System.Reflection/AssemblyHashAlgorithm.xml
Labels: loc

#3231 Document namespace System.Threading.Tasks.Sources
  xml/ns-System.Threading.Tasks.Sources.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content

#3249 Fixed typo mressage to message
  xml/System.Net.Http.Headers/CacheControlHeaderValue.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3247 Fix wrong color value
  xml/System.Drawing/Color.xml
Labels: doc-bug

#3189 Automatically port Reflection ManifestResourceAttributes and MethodSemanticsAttributes
  xml/System.Reflection/ManifestResourceAttributes.xml
  xml/System.Reflection/MethodSemanticsAttributes.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge

#3192 Automatically port Reflection.PortableExecutable.Machine
  xml/System.Reflection.PortableExecutable/Machine.xml
Labels: :checkered_flag: Release: .NET Core 2.x, changes-addressed, new-content, verify-build-before-merge

#3240 Fix mistake (?) in IEnumerable<T> documentation.
  xml/System.Collections.Generic/IEnumerable`1.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#3206 Document System.IO.BinaryReader Read methods
  xml/System.IO/BinaryReader.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge

#3261 syntax highlighting of c# example code
  xml/System.Xml.Linq/XElement.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!
