Repository dotnet/dotnet-api-docs, pull requests merged in 2019-05, with the labels that each got.

#2324 Port System.ComponentModel.Composition source code comments to Docs
  xml/System.ComponentModel.Composition/AttributedModelServices.xml
  xml/System.ComponentModel.Composition/CompositionContractMismatchException.xml
  xml/System.ComponentModel.Composition/CompositionException.xml
  xml/System.ComponentModel.Composition/ICompositionService.xml
Labels: changes-addressed, doc-enhancement

#2307 Port System.Security.Claims source comments to Docs
  xml/System.Security.Claims/Claim.xml
  xml/System.Security.Claims/ClaimsIdentity.xml
  xml/System.Security.Claims/ClaimsPrincipal.xml
Labels: changes-addressed, doc-enhancement

#2321 Port triple slash comment from System.IO to Docs
  xml/System.IO/FileSystemInfo.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#2391 Update DataColumn.xml
  xml/System.Data/DataColumn.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#2398 Quick grammatical fix.
  xml/System/NotImplementedException.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#2401 Fixed a typo
  xml/System.Threading/ReaderWriterLockSlim.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2396 Clarifying which way the function works
  xml/System/Type.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, merge-on-hold-for-live-update

#2389 Corrected formatting issue and added detail
  xml/System/String.xml
Labels: migration-fixes

#2416 Update XmlReader.ReadElementContentAsInt() exception listing
  xml/System.Xml/XmlReader.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2421 Remove ArgumentException in GCHandle.Alloc(object)
  xml/System.Runtime.InteropServices/GCHandle.xml
Labels: verify-build-before-merge

#2425 Upgrade links to https
  includes/wif-wstrust-ref-md.md
  xml/System.Collections.Specialized/INotifyCollectionChanged.xml
  xml/System.Collections.Specialized/NotifyCollectionChangedAction.xml
  xml/System.IO.Packaging/PackagePart.xml
  xml/System.IdentityModel.Protocols.WSTrust/EndpointReference.xml
  xml/System.Net.WebSockets/WebSocket.xml
  xml/System.Security.Cryptography.Xml/SignedXml.xml
  xml/System.ServiceModel.Discovery/FindCriteria.xml
  xml/System.Web.UI.HtmlControls/HtmlArea.xml
  xml/System.Web.UI.HtmlControls/HtmlAudio.xml
  xml/System.Web.UI.HtmlControls/HtmlEmbed.xml
  xml/System.Web.UI.HtmlControls/HtmlIframe.xml
  xml/System.Web.UI.HtmlControls/HtmlSource.xml
  xml/System.Web.UI.HtmlControls/HtmlTrack.xml
  xml/System.Web.UI.HtmlControls/HtmlVideo.xml
  xml/System.Web/HttpResponse.xml
  xml/System.Web/HttpResponseBase.xml
  xml/ns-System.IdentityModel.Protocols.WSTrust.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2427 Update ComRegisterFunctionAttribute.xml
  xml/System.Runtime.InteropServices/ComRegisterFunctionAttribute.xml
Labels: changes-addressed

#2426 Add missing docs for HttpClient.PatchAsync
  xml/System.Net.Http/HttpClient.xml
Labels: changes-addressed

#2432 Revised MissingManifestResourceException for .NET Core, .NET Framework, UWP
  xml/System.Resources/MissingManifestResourceException.xml
Labels: doc-enhancement

#2403 Fix GCHandle null typo
  xml/System.Buffers/MemoryHandle.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2406 recover some content from msdn
  xml/System.Data.Common/DataAdapter.xml
  xml/System.Data.Common/DbDataAdapter.xml
  xml/System.Windows.Forms.Design/ComponentTray.xml
  xml/System.Windows.Xps/XpsDocumentWriter.xml
  xml/System.Xml.Serialization/XmlMembersMapping.xml
  xml/System.Xml.Serialization/XmlTypeMapping.xml
  xml/System.Xml.XPath/XPathNavigator.xml
Labels: migration-fixes, verify-build-before-merge

#2434 Update ComUnregisterFunctionAttribute.xml
  xml/System.Runtime.InteropServices/ComUnregisterFunctionAttribute.xml
Labels: verify-build-before-merge

#2433 Document PlatformNotSupportedExceptions in System.Console
  xml/System/Console.xml
Labels: verify-build-before-merge

#2067 Added VB sample link
  xml/System.Net.Security/SslStream.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#2367 Added example for setting HttpClient.Timeout Property
  xml/System.Net.Http/HttpClient.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2448 Added VB examples for AuthenticatedStream, NegotiateStream
  xml/System.Net.Security/AuthenticatedStream.xml
  xml/System.Net.Security/NegotiateStream.xml
Labels: :construction: Hold for related PR

#2436 add reference to new samples
  xml/Microsoft.VisualBasic.FileIO/FileSystem.xml
Labels: :construction: Hold for related PR

#2456 Port Windows.UI.Xaml source code comments to Docs
  xml/Windows.UI.Xaml/CornerRadius.xml
  xml/Windows.UI.Xaml/Duration.xml
  xml/Windows.UI.Xaml/DurationType.xml
  xml/Windows.UI.Xaml/GridLength.xml
  xml/Windows.UI.Xaml/GridUnitType.xml
  xml/Windows.UI.Xaml/LayoutCycleException.xml
  xml/Windows.UI.Xaml/Thickness.xml
Labels: new-content

#2459 L89834: Removing extra spaces
  xml/System.Collections.Specialized/INotifyCollectionChanged.xml
Labels: loc

#2464 Update Claim.xml
  xml/System.Security.Claims/Claim.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2465 Noted Windows-only support for ProtectedData
  xml/System.Security.Cryptography/ProtectedData.xml
Labels: verify-build-before-merge

#2468 Correct parameter names for (ReadOnly)Span.Slice(Int32, Int32) methods
  xml/System/ReadOnlySpan`1.xml
  xml/System/Span`1.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2312 Port System.Threading.Tasks source comments to Docs
  xml/System.Threading.Tasks.Dataflow/BatchedJoinBlock`2.xml
  xml/System.Threading.Tasks.Dataflow/DataflowBlockOptions.xml
  xml/System.Threading.Tasks/Parallel.xml
Labels: doc-enhancement, verify-build-before-merge

#2333 Port System.Reflection.Metadata source code comments to Docs (L-Metadata* files)
  xml/System.Reflection.Metadata/LocalConstant.xml
  xml/System.Reflection.Metadata/ManifestResource.xml
  xml/System.Reflection.Metadata/MemberReference.xml
  xml/System.Reflection.Metadata/MetadataKind.xml
  xml/System.Reflection.Metadata/MetadataReader.xml
  xml/System.Reflection.Metadata/MetadataReaderOptions.xml
  xml/System.Reflection.Metadata/MetadataReaderProvider.xml
  xml/System.Reflection.Metadata/MetadataStreamOptions.xml
  xml/System.Reflection.Metadata/MetadataStringDecoder.xml
Labels: new-content

#2463 Updated culture-sensitive formatting information
  includes/thread-formatting.md
  xml/System/DateTime.xml
Labels: :construction: Hold for related PR

#2480 [OracleType] Remove useless remarks
  xml/System.Data.OracleClient/OracleType.xml
Labels: doc-enhancement

#2473 import UWP content from IntelliSense - Windows.Foundation namespace
  xml/Windows.Foundation/Point.xml
  xml/Windows.Foundation/Rect.xml
  xml/Windows.Foundation/Size.xml
Labels: migration-fixes, verify-build-before-merge

#2454 Moved more enum member remarks
  xml/System.Data.Common/CatalogLocation.xml
  xml/System.Data.Objects/MergeOption.xml
  xml/System.Data.OleDb/OleDbType.xml
  xml/System.Data.OracleClient/OracleType.xml
  xml/System.Data/CommandBehavior.xml
  xml/System.Data/IsolationLevel.xml
  xml/System.Data/XmlReadMode.xml
  xml/System.Device.Location/GeoPositionStatus.xml
Labels: migration-fixes

#2472 Removed en-US from URLs in API reference
  xml/System.DirectoryServices.ActiveDirectory/Domain.xml
  xml/System.DirectoryServices.ActiveDirectory/Forest.xml
  xml/System.Globalization/CompareInfo.xml
  xml/System.Globalization/CompareOptions.xml
  xml/System.Globalization/SortKey.xml
  xml/System.Globalization/StringInfo.xml
  xml/System.Printing/EnumeratedPrintQueueTypes.xml
  xml/System.Printing/InputBin.xml
  xml/System.Reflection/Assembly.xml
  xml/System.Reflection/MemberInfo.xml
  xml/System.Runtime.Loader/AssemblyLoadContext.xml
  xml/System.Security.Cryptography.Xml/SignedXml.xml
  xml/System.Transactions/Enlistment.xml
  xml/System.Transactions/SinglePhaseEnlistment.xml
  xml/System.Web.UI.MobileControls/MobileControl.xml
  xml/System.Web.UI/Control.xml
  xml/System.Web.UI/ViewStateMode.xml
  xml/System.Windows.Forms/Form.xml
  xml/System.Windows.Forms/HtmlDocument.xml
  xml/System.Windows.Forms/HtmlElement.xml
  xml/System.Windows.Forms/HtmlWindow.xml
  xml/System/AggregateException.xml
  xml/System/InvalidProgramException.xml
  xml/System/String.xml
  xml/System/StringComparer.xml
  xml/System/StringComparison.xml
Labels: :bookmark_tabs: Information Architecture

#2248 Specify that this will use the hosts file and not only DNS
  xml/System.Net/Dns.xml
Labels: :card_file_box: Technology - NCL, :sparkles: 1st-time dotnet-api-docs contributor!

#2332 Port System.Reflection.Metadata source code comments to Docs (F-I files)
  xml/System.Reflection.Metadata/FieldDefinition.xml
  xml/System.Reflection.Metadata/GenericParameter.xml
  xml/System.Reflection.Metadata/GenericParameterConstraint.xml
  xml/System.Reflection.Metadata/HandleComparer.xml
  xml/System.Reflection.Metadata/IConstructedTypeProvider`1.xml
  xml/System.Reflection.Metadata/ICustomAttributeTypeProvider`1.xml
  xml/System.Reflection.Metadata/ILOpCodeExtensions.xml
  xml/System.Reflection.Metadata/ISZArrayTypeProvider`1.xml
  xml/System.Reflection.Metadata/ISignatureTypeProvider`2.xml
  xml/System.Reflection.Metadata/ISimpleTypeProvider`1.xml
  xml/System.Reflection.Metadata/ImportDefinitionCollection+Enumerator.xml
  xml/System.Reflection.Metadata/InterfaceImplementation.xml
Labels: changes-addressed, new-content

#2335 Port System.Reflection.Metadata source code comments to Docs (Method*-T files)
  xml/System.Reflection.Metadata/MethodBodyBlock.xml
  xml/System.Reflection.Metadata/MethodDebugInformation.xml
  xml/System.Reflection.Metadata/MethodDebugInformationHandle.xml
  xml/System.Reflection.Metadata/MethodDefinitionHandle.xml
  xml/System.Reflection.Metadata/MethodSpecification.xml
  xml/System.Reflection.Metadata/NamespaceDefinition.xml
  xml/System.Reflection.Metadata/PEReaderExtensions.xml
  xml/System.Reflection.Metadata/ReservedBlob`1.xml
  xml/System.Reflection.Metadata/StandaloneSignature.xml
  xml/System.Reflection.Metadata/TypeDefinition.xml
  xml/System.Reflection.Metadata/TypeReference.xml
Labels: changes-addressed, new-content

#2474 import UWP content from IntelliSense - part 2
  xml/Windows.UI.Xaml.Automation/ElementNotAvailableException.xml
  xml/Windows.UI.Xaml.Automation/ElementNotEnabledException.xml
  xml/Windows.UI.Xaml.Controls.Primitives/GeneratorPosition.xml
  xml/Windows.UI.Xaml.Markup/XamlParseException.xml
  xml/Windows.UI/Color.xml
Labels: migration-fixes

#2475 import UWP content from IntelliSense - Windows.UI.Xaml.Media.*
  xml/Windows.UI.Xaml.Media.Animation/KeyTime.xml
  xml/Windows.UI.Xaml.Media.Animation/RepeatBehavior.xml
  xml/Windows.UI.Xaml.Media.Animation/RepeatBehaviorType.xml
  xml/Windows.UI.Xaml.Media.Media3D/Matrix3D.xml
  xml/Windows.UI.Xaml.Media/Matrix.xml
Labels: migration-fixes

#2485 L89834: Removing extra spaces
  xml/System.Reflection.Metadata/MetadataReaderProvider.xml
Labels: loc

#2488 Update DateTime.xml
  xml/System/DateTime.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2494 Port System.Linq.Expressions remark from source comments to Docs
  xml/System.Linq.Expressions/IArgumentProvider.xml
Labels: verify-build-before-merge

#2504 Update Volatile.xml summary to be consistent
  xml/System.Threading/Volatile.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2502 Fix "complementary" typo in System.Span<T>
  xml/System/Span`1.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2515 Fix example link in StackOverflowException
  xml/System/StackOverflowException.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2513 Code block fix
  xml/System.Windows.Controls/ControlTemplate.xml
Labels: verify-build-before-merge

#2498 Added information on schema validation errors
  xml/System.Xml.Schema/XmlSchemaSet.xml
Labels: :construction: Hold for related PR

#2471 Port System.Text.Json source comments to Docs (second attempt)
  xml/System.Text.Json/JsonDocument.xml
  xml/System.Text.Json/JsonElement+ArrayEnumerator.xml
  xml/System.Text.Json/JsonElement+ObjectEnumerator.xml
  xml/System.Text.Json/JsonElement.xml
  xml/System.Text.Json/JsonProperty.xml
  xml/System.Text.Json/JsonReaderOptions.xml
  xml/System.Text.Json/JsonReaderState.xml
  xml/System.Text.Json/JsonValueType.xml
  xml/System.Text.Json/Utf8JsonReader.xml
  xml/System.Text.Json/Utf8JsonWriter.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2491 Port System.Net source comments to Docs
  xml/System.Net.Security/CipherSuitesPolicy.xml
  xml/System.Net.Security/SslClientAuthenticationOptions.xml
  xml/System.Net.Security/SslServerAuthenticationOptions.xml
  xml/System.Net.Sockets/UnixDomainSocketEndPoint.xml
  xml/System.Net.WebSockets/ValueWebSocketReceiveResult.xml
Labels: :card_file_box: Technology - NCL

#2514 Restored more enumeration member remarks
  xml/System.ComponentModel.Design/DisplayMode.xml
  xml/System.ComponentModel.Design/ViewTechnology.xml
  xml/System.ComponentModel/PropertyTabScope.xml
  xml/System.ComponentModel/RefreshProperties.xml
  xml/System.ComponentModel/ToolboxItemFilterType.xml
  xml/System.DirectoryServices.AccountManagement/ContextOptions.xml
  xml/System.Drawing.Design/UITypeEditorEditStyle.xml
  xml/System.EnterpriseServices/PropertyLockMode.xml
  xml/System.Messaging/AcknowledgeTypes.xml
  xml/System.Messaging/Acknowledgment.xml
  xml/System.Messaging/CryptographicProviderType.xml
  xml/System.Messaging/MessageQueueErrorCode.xml
  xml/System.Messaging/StandardAccessRights.xml
Labels: migration-fixes, verify-build-before-merge

#2487 Port System.Security source comments to Docs
  xml/System.Security.Claims/Claim.xml
  xml/System.Security.Claims/ClaimsIdentity.xml
  xml/System.Security.Claims/ClaimsPrincipal.xml
  xml/System.Security.Cryptography.Pkcs/Pkcs12CertBag.xml
  xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampToken.xml
  xml/System.Security.Cryptography.Xml/RSAKeyValue.xml
Labels: verify-build-before-merge

#2526 Update File.xml
  xml/System.IO/File.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2492 Port System.Collections.Immutable source comments to Docs
  xml/System.Collections.Immutable/ImmutableArray.xml
  xml/System.Collections.Immutable/ImmutableArray`1+Enumerator.xml
Labels: verify-build-before-merge
