Repository dotnet/dotnet-api-docs, pull requests merged in 2019-08, with the labels that each got.

#2897 Adding missing param description to NetworkStream.Write(System.ReadOnlySpan{System.Byte})
  xml/System.Net.Sockets/NetworkStream.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2877 Automatically port System.Text.Json.JsonValueKind
  xml/System.Text.Json/JsonValueKind.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2881 Automatically port System.Text.Json.JsonProperty
  xml/System.Text.Json/JsonProperty.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2886 Automatically port System.Text.Json.Serialization.JsonConverterFactory
  xml/System.Text.Json.Serialization/JsonConverterFactory.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2848 Add missing documentation in EnvelopedCms and update existing docs.
  xml/System.Security.Cryptography.Pkcs/EnvelopedCms.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#2857 Document System.Resources.Extensions
  xml/System.Resources.Extensions/DeserializingResourceReader.xml
  xml/System.Resources.Extensions/PreserializedResourceWriter.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#2860 Adding documentation for APIs in System.Collections.Immutable targeted for 3.0
  xml/System.Collections.Immutable/ImmutableArray.xml
  xml/System.Collections.Immutable/ImmutableArray`1.xml
  xml/System.Collections.Immutable/ImmutableDictionary.xml
  xml/System.Collections.Immutable/ImmutableHashSet.xml
  xml/System.Collections.Immutable/ImmutableList.xml
  xml/System.Collections.Immutable/ImmutableSortedDictionary.xml
  xml/System.Collections.Immutable/ImmutableSortedSet.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#2868 Add missing documentation for RandomNumberGenerator types
  xml/System.Security.Cryptography/RNGCryptoServiceProvider.xml
  xml/System.Security.Cryptography/RandomNumberGenerator.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2869 Copy Stream docs to CryptoStream overrides
  xml/System.Security.Cryptography/CryptoStream.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2870 Document SafeEvpPKeyHandle
  xml/System.Security.Cryptography/SafeEvpPKeyHandle.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2878 Automatically port System.Text.Json.Serialization.JsonStringEnumConverter
  xml/System.Text.Json.Serialization/JsonStringEnumConverter.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#2882 Automatically port System.Text.Json.JsonNamingPolicy
  xml/System.Text.Json/JsonNamingPolicy.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#2883 Automatically port System.Text.Json.JsonException
  xml/System.Text.Json/JsonException.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#2884 Automatically port System.Text.Json.JsonElement
  xml/System.Text.Json/JsonElement.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2840 Recommendations for SHA1.
  xml/System.Security.Cryptography/MD5.xml
  xml/System.ServiceModel.Security/Basic128SecurityAlgorithmSuite.xml
  xml/System.Web.Configuration/AuthenticationSection.xml
Labels: vendor-project

#2911 Minor typo in Environment.xml
  xml/System/Environment.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2885 Automatically port System.Text.Json.JsonDocumentOptions
  xml/System.Text.Json/JsonDocumentOptions.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2888 Automatically port System.Text.Json.Serialization.JsonConverter`1
  xml/System.Text.Json.Serialization/JsonConverter`1.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2913 Document System.Resources.Extensions Namespace
  xml/ns-System.Resources.Extensions.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2907 Document System.Text.Json.JsonDocument
  xml/System.Text.Json/JsonDocument.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2910 Document various isolated System.Text.Json elements
  xml/System.Text.Json.Serialization/JsonStringEnumConverter.xml
  xml/System.Text.Json/JsonElement.xml
  xml/System.Text.Json/JsonEncodedText.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2880 Automatically port System.Text.Json.JsonSerializer
  xml/System.Text.Json/JsonSerializer.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2906 Document Json namespaces
  xml/ns-System.Text.Json.Serialization.xml
  xml/ns-System.Text.Json.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content, verify-build-before-merge

#2842 Document System.IO.Pipelines Platform Extensions
  xml/System.IO.Pipelines/PipeReader.xml
  xml/System.IO.Pipelines/PipeWriter.xml
  xml/System.IO.Pipelines/StreamPipeExtensions.xml
  xml/System.IO.Pipelines/StreamPipeReaderOptions.xml
  xml/System.IO.Pipelines/StreamPipeWriterOptions.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#2902 Note about Dispose affecting Attachments
  xml/System.Net.Mail/MailMessage.xml
Labels: :card_file_box: Technology - NCL, :sparkles: 1st-time dotnet-api-docs contributor!

#2921 Document Pkcs12SafeBag
  xml/System.Security.Cryptography.Pkcs/Pkcs12SafeBag.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2891 Automatically port System.Text.Json.Utf8JsonWriter
  xml/System.Text.Json/Utf8JsonWriter.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#2900 Document System.Security.AccessControl.ObjectSecurity.SecurityDescriptor
  xml/System.Security.AccessControl/ObjectSecurity.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#2875 Adding documentation for System.Text APIs tergeted for 3.0
  xml/System.Text/ASCIIEncoding.xml
  xml/System.Text/UTF32Encoding.xml
  xml/System.Text/UTF8Encoding.xml
  xml/System.Text/UnicodeEncoding.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2923 Document Pkcs12SafeContents
  xml/System.Security.Cryptography.Pkcs/Pkcs12SafeContents.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2871 Document System.Reflection.MetadataAssemblyResolver and PathAssemblyResolver
  xml/System.Reflection/MetadataAssemblyResolver.xml
  xml/System.Reflection/PathAssemblyResolver.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2908 Document System.Text.Json.JsonElement+ArrayEnumerator
  xml/System.Text.Json/JsonElement+ArrayEnumerator.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#2887 Automatically port System.Text.Json.Serialization.JsonConverterAttribute
  xml/System.Text.Json.Serialization/JsonConverterAttribute.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#2724 coreclr: Automatic port of triple slash from System.IO
  xml/System.IO/Path.xml
  xml/System.IO/TextWriter.xml
  xml/System.IO/UnmanagedMemoryStream.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2919 Document Pkcs12Builder
  xml/System.Security.Cryptography.Pkcs/Pkcs12Builder.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#2926 Add documentation for the rest of the Pkcs12SafeBag derived types
  xml/System.Security.Cryptography.Pkcs/Pkcs12KeyBag.xml
  xml/System.Security.Cryptography.Pkcs/Pkcs12SafeContentsBag.xml
  xml/System.Security.Cryptography.Pkcs/Pkcs12SecretBag.xml
  xml/System.Security.Cryptography.Pkcs/Pkcs12ShroudedKeyBag.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2909 Document System.Text.Json.JsonElement+ObjectEnumerator
  xml/System.Text.Json/JsonElement+ObjectEnumerator.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#2890 Automatically port System.Text.Json.Utf8JsonReader
  xml/System.Text.Json/Utf8JsonReader.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2846 Document System.IO.WindowsRuntimeStorageExtensions
  xml/System.IO/WindowsRuntimeStorageExtensions.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-feedback

#2838 Try. NET update for system.collections.generic.list-1.*
  xml/System.Collections.Generic/List`1.xml
Labels: vendor-project, verify-build-before-merge

#2931 Add exception to GetObjectForIUnknown
  xml/System.Runtime.InteropServices/Marshal.xml
Labels: doc-enhancement, verify-build-before-merge

#2934 Document Pkcs9LocalKeyId
  xml/System.Security.Cryptography.Pkcs/Pkcs9LocalKeyId.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#2821 Initial docs for StringRuneEnumerator and SpanRuneEnumerator
  xml/System.Text/SpanRuneEnumerator.xml
  xml/System.Text/StringRuneEnumerator.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2914 Document Pkcs12Info
  xml/System.Security.Cryptography.Pkcs/Pkcs12Info.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2841 Document System.Buffers.SequenceReader
  xml/System.Buffers/ArrayBufferWriter`1.xml
  xml/System.Buffers/SequenceReaderExtensions.xml
  xml/System.Buffers/SequenceReader`1.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2889 Automatically port System.Text.Json.Serialization.JsonConverter
  xml/System.Text.Json.Serialization/JsonConverter.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2912 Document System.Numerics APIs
  xml/System.Numerics/Complex.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2938 Document System.Security.Cryptography.Pkcs.SignedCms
  xml/System.Security.Cryptography.Pkcs/SignedCms.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#2292 2 Mistakes? In GetEndComSlot & GetStartComSlot?
  xml/System.Runtime.InteropServices/Marshal.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2940 Document System.Security.Cryptography.X509Certificates.X509Certificate2UI
  xml/System.Security.Cryptography.X509Certificates/X509Certificate2UI.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#2946 Added documentation for System.Numerics.Complex APIs targeted for 3.0
  xml/System.Numerics/Complex.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2852 Fix http status code dead link
  xml/System.Web/HttpResponse.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#2905 Try. NET update for system.collections.generic.dictionary-2.*
  xml/System.Collections.Generic/Dictionary`2.xml
Labels: vendor-project, verify-build-before-merge

#2942 Document System.Security.Cryptography.Pkcs.SignerInfo
  xml/System.Security.Cryptography.Pkcs/SignerInfo.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2822 Adding documentation for new CipherSuitesPolicy, SslStream.NegotiatedCipherSuite and TlsCipherSuites
  xml/System.Net.Security/CipherSuitesPolicy.xml
  xml/System.Net.Security/SslStream.xml
  xml/System.Net.Security/TlsCipherSuite.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2932 Document Pkcs8PrivateKeyInfo
  xml/System.Security.Cryptography.Pkcs/Pkcs8PrivateKeyInfo.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content, waiting-on-reviews

#2943 Added documentation for System.Text.Rune struct
  xml/System.Text/Rune.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#2879 Automatically port System.Text.Json.JsonSerializerOptions
  xml/System.Text.Json/JsonSerializerOptions.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2939 Document System.Security.Cryptography.Pkcs.SubjectIdentifier.MatchesCertificate
  xml/System.Security.Cryptography.Pkcs/SubjectIdentifier.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2917 Updates re MD5/SHA1 usage.
  xml/Microsoft.Build.Tasks.Deployment.ManifestUtilities/BaseReference.xml
  xml/Mono.Security.Interface/HashAlgorithmType.xml
  xml/System.CodeDom/CodeChecksumPragma.xml
  xml/System.Configuration.Assemblies/AssemblyHashAlgorithm.xml
  xml/System.IO.Packaging/PackageDigitalSignatureManager.xml
  xml/System.IdentityModel.Tokens/InMemorySymmetricSecurityKey.xml
  xml/System.IdentityModel.Tokens/SecurityAlgorithms.xml
  xml/System.IdentityModel.Tokens/SymmetricSecurityKey.xml
  xml/System.IdentityModel.Tokens/X509AsymmetricSecurityKey.xml
  xml/System.IdentityModel/RsaEncryptionCookieTransform.xml
  xml/System.IdentityModel/RsaSignatureCookieTransform.xml
  xml/System.Messaging/DefaultPropertiesToSend.xml
  xml/System.Messaging/Message.xml
  xml/System.Net.Http.Headers/HttpContentHeaders.xml
  xml/System.Net/HttpRequestHeader.xml
  xml/System.Net/HttpResponseHeader.xml
  xml/System.Reflection/AssemblyHashAlgorithm.xml
  xml/System.Security.Authentication/HashAlgorithmType.xml
  xml/System.Security.Policy/Hash.xml
  xml/System.ServiceModel.Security/Basic192SecurityAlgorithmSuite.xml
  xml/System.ServiceModel.Security/Basic256SecurityAlgorithmSuite.xml
  xml/System.ServiceModel.Security/SecurityKeyEntropyMode.xml
  xml/System.ServiceModel.Security/TripleDesSecurityAlgorithmSuite.xml
  xml/System.ServiceModel/MsmqSecureHashAlgorithm.xml
  xml/System.ServiceModel/MsmqTransportSecurity.xml
Labels: vendor-project

#2936 Add missing visual basic sample
  xml/System.Net.Http/HttpClient.xml
Labels: changes-addressed

#2901 Dev/suwhang/system.diagnostics
  xml/System.Diagnostics.Tracing/DiagnosticCounter.xml
  xml/System.Diagnostics.Tracing/EventCounter.xml
  xml/System.Diagnostics.Tracing/IncrementingEventCounter.xml
  xml/System.Diagnostics.Tracing/IncrementingPollingCounter.xml
  xml/System.Diagnostics.Tracing/PollingCounter.xml
  xml/System.Diagnostics/Activity.xml
  xml/System.Diagnostics/ActivitySpanId.xml
  xml/System.Diagnostics/ActivityTraceFlags.xml
  xml/System.Diagnostics/ActivityTraceId.xml
  xml/System.Diagnostics/DiagnosticListener.xml
  xml/System.Diagnostics/DiagnosticSource.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2693 coreclr: Automatic port of triple slash from System.Buffers.Binary
  xml/System.Buffers.Binary/BinaryPrimitives.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2876 Fill in some missing Rune APIs
  xml/System.Text/Rune.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2967 Missing returns in System.Text.Rune.GetRuneAt
  xml/System.Text/Rune.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#2966 Wrong param name in an overload for System.Text.Json.Utf8JsonReader.ValueTextEquals
  xml/System.Text.Json/Utf8JsonReader.xml
Labels: waiting-on-reviews

#2965 Missing returns from System.Reflection.MetadataLoadContext.LoadFromStream
  xml/System.Reflection/MetadataLoadContext.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#2964 Missing params in System.IO.Path
  xml/System.IO/Path.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#2968 Document 2 APIs in System.Security.Cryptography.DCACng
  xml/System.Security.Cryptography/DSACng.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed

#2963 [small fix] Commas in System.Buffers.Binary
  xml/System.Buffers.Binary/BinaryPrimitives.xml
Labels: doc-enhancement, verify-build-before-merge

#2663 Added documentation for new System.Net APIs released in 3.0
  xml/System.Net/CookieCollection.xml
  xml/System.Net/FileWebRequest.xml
  xml/System.Net/IPEndPoint.xml
Labels: :card_file_box: Technology - NCL, :checkered_flag: Release: .NET Core 3.0, new-content

#2969 Added documentation for System.Diagnostics APIs targeted for 3.0
  xml/System.Diagnostics/Activity.xml
  xml/System.Diagnostics/DiagnosticListener.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2972 Added documentation for System.Diagnostics.Tracing APIs targeted for 3.0
  xml/System.Diagnostics.Tracing/DiagnosticCounter.xml
  xml/System.Diagnostics.Tracing/EventCounter.xml
  xml/System.Diagnostics.Tracing/IncrementingEventCounter.xml
  xml/System.Diagnostics.Tracing/IncrementingPollingCounter.xml
  xml/System.Diagnostics.Tracing/PollingCounter.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2978 Add ReadTimeout unit on SslStream
  xml/System.Net.Security/SslStream.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2979 Remove dead MSDN link to details
  xml/System.Data.Metadata.Edm/MetadataWorkspace.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#2981 Document new constructor for Windows.UI.Xaml.Automation.ElementNotAvailableException
  xml/Windows.UI.Xaml.Automation/ElementNotAvailableException.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2983 Document new constructor for Windows.UI.Xaml.LayoutCycleException
  xml/Windows.UI.Xaml/LayoutCycleException.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2975 update docs for BoundsSpecified
  xml/System.Windows.Forms/BoundsSpecified.xml
Labels: :checkered_flag: Release: .NET Core 3.0, doc-update

#2783 Add NSUrlSessionHandler docs
  xml/System.Net.Http/NSUrlSessionHandler.xml
Labels: new-content, verify-build-before-merge

#2987 fix CDATA section
  xml/System.Diagnostics/DiagnosticListener.xml
  xml/System.IO/WindowsRuntimeStorageExtensions.xml
  xml/System.Numerics/Complex.xml
  xml/System.Reflection/MetadataAssemblyResolver.xml
  xml/System.Reflection/PathAssemblyResolver.xml
Labels: loc

#2784 Some API docs for SocketHttpHandler
  xml/System.Net.Http/SocketsHttpHandler.xml
Labels: new-content, verify-build-before-merge

#2984 doc updates for BehaviorServiceAdornerCollection
  xml/System.Windows.Forms.Design.Behavior/BehaviorServiceAdornerCollection.xml
Labels: :card_file_box: Technology - WinForms, :checkered_flag: Release: .NET Core 3.0, doc-update, waiting-on-reviews

#2985 API docs for DesignerActionListsChangedEventArgs
  xml/System.Windows.Forms.Design/DesignerActionListsChangedEventArgs.xml
Labels: :card_file_box: Technology - WinForms, :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#2976 Fix JSON Writer docs for data writter as Base64-encoded text
  xml/System.Text.Json/JsonElement.xml
  xml/System.Text.Json/Utf8JsonWriter.xml
Labels: changes-addressed

#2989 Removed duplicate member group
  xml/System.Numerics/Complex.xml
Labels: verify-build-before-merge

#2990 Update Directory.xml
  xml/System.IO/Directory.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#2994 Missing API docs for Application
  xml/System.Windows.Forms/Application.xml
Labels: :card_file_box: Technology - WinForms, new-content, verify-build-before-merge

#2992 Added dropped mention of peverify tool
  xml/System.Security/SecurityRulesAttribute.xml
Labels: migration-fixes

#2998 added dropped text
  xml/System.Data.EntityClient/EntityConnection.xml
Labels: migration-fixes

#3005 fix see cref links
  xml/Microsoft.Build.Tasks.Xaml/CommandLineGenerator.xml
  xml/System.Activities.Presentation.PropertyEditing/CategoryEntry.xml
  xml/System.Buffers/SequenceReaderExtensions.xml
  xml/System.Collections/IDictionaryEnumerator.xml
  xml/System.Diagnostics.Tracing/EventWrittenEventArgs.xml
  xml/System.IdentityModel.Configuration/IdentityModelCachesElement.xml
  xml/System.Printing.IndexedProperties/PrintDateTimeProperty.xml
  xml/System.Reflection.Metadata/ConstantTypeCode.xml
  xml/System.Reflection.Metadata/PrimitiveSerializationTypeCode.xml
  xml/System.Reflection.Metadata/PrimitiveTypeCode.xml
  xml/System.Reflection.Metadata/SerializationTypeCode.xml
  xml/System.Reflection.Metadata/SignatureTypeCode.xml
  xml/System.Reflection/PathAssemblyResolver.xml
  xml/System.Runtime.InteropServices/MemoryMarshal.xml
  xml/System.ServiceModel.Description/ServiceHealthModel+ServiceEndpointModel.xml
  xml/System.Text.Unicode/UnicodeRange.xml
  xml/System.Text.Unicode/UnicodeRanges.xml
  xml/System.Text/StringBuilder.xml
  xml/System.Web.UI.DataVisualization.Charting/Chart.xml
  xml/System.Web.UI.DataVisualization.Charting/Legend.xml
  xml/System.Windows.Automation/AutomationProperties.xml
  xml/System.Windows.Controls/InkCanvas.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Chart.xml
  xml/System.Windows.Forms.DataVisualization.Charting/Legend.xml
  xml/System.Windows.Forms/ToolStripStatusLabel.xml
  xml/System.Workflow.Runtime.Hosting/ManualWorkflowSchedulerService.xml
  xml/System/DateTimeOffset.xml
  xml/System/ReadOnlySpan`1+Enumerator.xml
  xml/System/ReadOnlySpan`1.xml
  xml/System/Span`1+Enumerator.xml
  xml/System/Span`1.xml
  xml/System/Type.xml
Labels: :bookmark_tabs: Information Architecture, verify-build-before-merge

#3001 Replaced dropped text, fixed some formatting
  xml/System.Collections.Generic/IList`1.xml
  xml/System.Collections.Generic/SortedDictionary`2+ValueCollection+Enumerator.xml
  xml/System.Collections.Immutable/ImmutableInterlocked.xml
  xml/System.Collections.ObjectModel/KeyedCollection`2.xml
  xml/System.Collections.Specialized/BitVector32.xml
  xml/System.Collections.Specialized/IOrderedDictionary.xml
  xml/System.Collections.Specialized/NameObjectCollectionBase+KeysCollection.xml
  xml/System.Collections.Specialized/NameValueCollection.xml
  xml/System.Collections.Specialized/OrderedDictionary.xml
  xml/System.Collections.Specialized/StringCollection.xml
  xml/System.Diagnostics/Debug.xml
  xml/System.Windows.Controls/Grid.xml
  xml/System.Windows.Controls/StickyNoteControl.xml
  xml/System.Windows.Controls/VirtualizingPanel.xml
  xml/System.Windows.Forms.VisualStyles/VisualStyleElement+ScrollBar+ThumbButtonHorizontal.xml
  xml/System.Windows.Markup/UidPropertyAttribute.xml
  xml/System.Windows.Markup/XamlSetMarkupExtensionAttribute.xml
  xml/System.Windows/Point.xml
  xml/System.Workflow.Runtime/WorkflowRuntime.xml
  xml/System/InvalidOperationException.xml
  xml/System/TimeZoneInfo.xml
Labels: migration-fixes, verify-build-before-merge

#3007 Automatic port of System.IO.Pipelines PipeReader/PipeWriter CompleteAsync
  xml/System.IO.Pipelines/PipeReader.xml
  xml/System.IO.Pipelines/PipeWriter.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#3009 Automatically port System.Text.Json.Serialization.JsonConverterFactory
  xml/System.Text.Json.Serialization/JsonConverterFactory.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#3010 Automatically port System.Text.Json.JsonDocument
  xml/System.Text.Json/JsonDocument.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#3011 Automatically port System.Text.Json.JsonElement
  xml/System.Text.Json/JsonElement.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#3012 Automatically port System.Text.Json.JsonEncodedText
  xml/System.Text.Json/JsonEncodedText.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#3013 Automatically port System.Text.Json.JsonProperty
  xml/System.Text.Json/JsonProperty.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#3014 Automatically port System.Text.Json.JsonSerializer
  xml/System.Text.Json/JsonSerializer.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#3015 Automatically port System.Text.Json.JsonSerializerOptions
  xml/System.Text.Json/JsonSerializerOptions.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#3017 Automatically port System.Text.Json.Utf8JsonReader/Writer
  xml/System.Text.Json/Utf8JsonReader.xml
  xml/System.Text.Json/Utf8JsonWriter.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#3016 Automatically port System.Text.Json.JsonWriterOptions
  xml/System.Text.Json/JsonWriterOptions.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, waiting-on-reviews

#3008 Automatic port of System.Text.Encodings.Web
  xml/System.Text.Encodings.Web/JavaScriptEncoder.xml
  xml/System.Text.Encodings.Web/TextEncoder.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#2995 Missing API docs for FolderBrowserDialog
  xml/System.Windows.Forms/FolderBrowserDialog.xml
Labels: :card_file_box: Technology - WinForms, new-content, verify-build-before-merge

#3019 add missing return value
  xml/System.Windows.Automation/AndCondition.xml
Labels: :card_file_box: Technology - WPF, new-content, verify-build-before-merge

#3023 New async APIs in DbCommand
  xml/System.Data.Common/DbCommand.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge, waiting-on-feedback

#3022 New async APIs in DbTransaction
  xml/System.Data.Common/DbTransaction.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#3021 New async APIs in DbConnection
  xml/System.Data.Common/DbConnection.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#3034 New API docs for NotifyIcon
  xml/System.Windows.Forms/NotifyIcon.xml
Labels: :card_file_box: Technology - WinForms, :checkered_flag: Release: .NET Core 3.0, new-content

#3030 add missing docs for ImageList
  xml/System.Windows.Forms/ImageList.xml
Labels: :card_file_box: Technology - WinForms, :checkered_flag: Release: .NET Core 3.0, new-content

#3026 New async APIs in DbDataReader
  xml/System.Data.Common/DbDataReader.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge, waiting-on-feedback

#3038 New API doc for TextBox
  xml/System.Windows.Forms/TextBox.xml
Labels: :card_file_box: Technology - WinForms, :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content, verify-build-before-merge

#3046 Fix mistake in description of OSPlatform.FreeBSD
  xml/System.Runtime.InteropServices/OSPlatform.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3018 Add documentation for WPF's System.Windows.Media.PenDashCap enum and System.Windows.Media.IAnimation interface
  xml/System.Windows.Media.Animation/IAnimation.xml
  xml/System.Windows.Media/PenDashCap.xml
Labels: :checkered_flag: Release: .NET Core 3.0, verify-build-before-merge

#3027 New API on DbProviderFactory
  xml/System.Data.Common/DbProviderFactory.xml
Labels: :checkered_flag: Release: .NET Core 3.0, changes-addressed, new-content

#3035 Update docs for PropertyManager
  xml/System.Windows.Forms/PropertyManager.xml
Labels: :card_file_box: Technology - WinForms, :checkered_flag: Release: .NET Core 3.0, doc-update, waiting-on-feedback

#3052 Update Attribute.xml
  xml/System/Attribute.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, loc, verify-build-before-merge

#3037 New API + docs update for SplitterPanel
  xml/System.Windows.Forms/SplitterPanel.xml
Labels: :card_file_box: Technology - WinForms, :checkered_flag: Release: .NET Core 3.0, new-content

#3033 New API docs for MdiClient
  xml/System.Windows.Forms/MdiClient.xml
Labels: :card_file_box: Technology - WinForms, :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#3032 New API docs for ListViewItemStateImageIndexConverter
  xml/System.Windows.Forms/ListViewItemStateImageIndexConverter.xml
Labels: :card_file_box: Technology - WinForms, :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#3047 URL to docs for OutputDebugString instead of vague instructions
  xml/System.Diagnostics/DefaultTraceListener.xml
Labels: verify-build-before-merge

#3002 Replaced link to events information
  xml/System.Workflow.ComponentModel/Activity.xml
  xml/System.Workflow.Runtime/WorkflowRuntime.xml
Labels: changes-addressed

#2953 Updates re MD5/SHA1 usage second batch
  xml/System.Security.Cryptography.Xml/Reference.xml
  xml/System.Security.Cryptography.Xml/SignedXml.xml
  xml/System.Security.Cryptography/CngAlgorithm.xml
  xml/System.Security.Cryptography/DSACryptoServiceProvider.xml
  xml/System.Security.Cryptography/ECDiffieHellmanCng.xml
  xml/System.Security.Cryptography/ECDsaCng.xml
  xml/System.Security.Cryptography/HMAC.xml
  xml/System.Security.Cryptography/HMACMD5.xml
  xml/System.Security.Cryptography/HMACRIPEMD160.xml
  xml/System.Security.Cryptography/HMACSHA1.xml
  xml/System.Security.Cryptography/HashAlgorithm.xml
  xml/System.Security.Cryptography/HashAlgorithmName.xml
  xml/System.Security.Cryptography/KeyedHashAlgorithm.xml
  xml/System.Security.Cryptography/PKCS1MaskGenerationMethod.xml
  xml/System.Security.Cryptography/RSACryptoServiceProvider.xml
  xml/System.Security.Cryptography/RSAEncryptionPadding.xml
  xml/System.Security.Cryptography/SHA1.xml
  xml/System.Security.Cryptography/SHA1Cng.xml
  xml/System.Security.Cryptography/SHA1CryptoServiceProvider.xml
  xml/System.Security.Cryptography/SHA1Managed.xml
  xml/System.Web.Configuration/FormsAuthPasswordFormat.xml
  xml/System.Web.Configuration/FormsAuthenticationConfiguration.xml
  xml/System.Web.Configuration/FormsAuthenticationCredentials.xml
  xml/System.Web.Configuration/FormsAuthenticationUser.xml
  xml/System.Web.Configuration/MachineKeySection.xml
  xml/System.Web.Security/FormsAuthentication.xml
  xml/System.Web.Security/MembershipPasswordFormat.xml
  xml/System.Web.Security/SqlMembershipProvider.xml
  xml/System.Web/HttpWorkerRequest.xml
  xml/System.Workflow.ComponentModel.Compiler/WorkflowMarkupSourceAttribute.xml
Labels: vendor-project

#3056 Update ReflectionOnly methods for .NET Core
  xml/System.Reflection/Assembly.xml
  xml/System/Type.xml
Labels: :checkered_flag: Release: .NET Core 3.0, doc-enhancement

#3057 Standardized or removed PlatformNotSupportedException
  xml/System.Data.Common/DbDataReader.xml
  xml/System.Diagnostics/EventLogInstaller.xml
  xml/System.Diagnostics/PerformanceCounter.xml
  xml/System.Diagnostics/Process.xml
  xml/System.Diagnostics/ProcessThread.xml
  xml/System.Security.Cryptography.Pkcs/CmsSigner.xml
Labels: verify-build-before-merge

#3058 Clarify relative vs full path to *Info classes
  xml/System.IO/DirectoryInfo.xml
  xml/System.IO/FileInfo.xml
  xml/System.IO/FileSystemInfo.xml
Labels: doc-enhancement, verify-build-before-merge

#3066 Fix spacing in System.Net.Sockets remarks
  xml/System.Net.Sockets/Socket.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge

#3069 fix reference enum field - Part 2
  xml/System.IO/SearchOption.xml
  xml/System.IdentityModel.Configuration/IdentityModelCaches.xml
  xml/System.IdentityModel.Tokens/SecurityKeyType.xml
  xml/System.Net.Cache/HttpRequestCacheLevel.xml
  xml/System.Net.Sockets/SocketFlags.xml
  xml/System.Net.Sockets/TransmitFileOptions.xml
  xml/System.Net/Cookie.xml
  xml/System.Numerics/Complex.xml
  xml/System.Printing/DeviceFontSubstitution.xml
  xml/System.Printing/EnumeratedPrintQueueTypes.xml
  xml/System.Printing/InputBin.xml
  xml/System.Printing/PhotoPrintingIntent.xml
  xml/System.Reflection/TypeAttributes.xml
  xml/System.Runtime.InteropServices.ComTypes/CALLCONV.xml
  xml/System.Security.AccessControl/FileSystemRights.xml
  xml/System.Security.Cryptography.X509Certificates/OpenFlags.xml
  xml/System.Security.Cryptography.X509Certificates/X500DistinguishedNameFlags.xml
  xml/System.Security.Permissions/EnvironmentPermissionAccess.xml
  xml/System.Security.Permissions/ReflectionPermissionFlag.xml
  xml/System.Security.Permissions/RegistryPermissionAccess.xml
  xml/System.Security/PartialTrustVisibilityLevel.xml
  xml/System.ServiceModel.Activation/AspNetCompatibilityRequirementsMode.xml
Labels: migration-fixes, verify-build-before-merge

#3065 add missing param
  xml/System.Buffers/StandardFormat.xml
Labels: verify-build-before-merge

#3068 fix reference enum field - Part 1
  xml/System.ComponentModel.Design/ViewTechnology.xml
  xml/System.Configuration/ConfigurationElementCollectionType.xml
  xml/System.Configuration/SettingsManageability.xml
  xml/System.Data.Services.Client/SaveChangesOptions.xml
  xml/System.Data/CommandType.xml
  xml/System.Diagnostics.Tracing/EventLevel.xml
  xml/System.Diagnostics/DebuggableAttribute+DebuggingModes.xml
  xml/System.Diagnostics/PerformanceCounterInstanceLifetime.xml
  xml/System.Drawing.Drawing2D/SmoothingMode.xml
  xml/System.Globalization/CalendarWeekRule.xml
  xml/System.Globalization/GregorianCalendarTypes.xml
  xml/System.Globalization/NumberStyles.xml
  xml/System.IO.Compression/ZipArchiveMode.xml
  xml/System.IO.Packaging/CertificateEmbeddingOption.xml
  xml/System.IO.Packaging/TargetMode.xml
  xml/System.IO.Pipes/PipeDirection.xml
  xml/System.IO.Ports/SerialData.xml
  xml/System.IO.Ports/SerialError.xml
  xml/System.IO/FileShare.xml
Labels: migration-fixes, verify-build-before-merge

#3103 Correct documentation copied from Double
  xml/System/Decimal.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3094 fix reference enum field - Part 5
  xml/System.Windows.Media/BitmapScalingMode.xml
  xml/System.Windows.Media/EdgeMode.xml
  xml/System.Windows.Media/HitTestFilterBehavior.xml
  xml/System.Windows.Media/HitTestResultBehavior.xml
  xml/System.Windows.Threading/DispatcherPriority.xml
  xml/System.Windows/FrameworkPropertyMetadataOptions.xml
  xml/System.Windows/MessageBoxButton.xml
  xml/System.Workflow.ComponentModel/ActivityExecutionResult.xml
  xml/System.Xml.Schema/XmlSchemaValidationFlags.xml
  xml/System.Xml.Serialization/CodeGenerationOptions.xml
  xml/System.Xml/XmlReader.xml
  xml/System/Base64FormattingOptions.xml
  xml/System/DateTimeOffset.xml
  xml/System/IComparable`1.xml
  xml/System/LoaderOptimization.xml
  xml/System/MidpointRounding.xml
  xml/System/PlatformID.xml
  xml/System/StringSplitOptions.xml
  xml/System/TimeZoneInfo.xml
Labels: migration-fixes, verify-build-before-merge

#3083 Document System.Text.Json.Serialization.JsonConverter CreateConverter
  xml/System.Text.Json.Serialization/JsonStringEnumConverter.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content

#3081 Automatically port Utf8JsonReader remark
  xml/System.Text.Json/Utf8JsonReader.xml
Labels: :checkered_flag: Release: .NET Core 3.0, new-content, verify-build-before-merge

#3082 Automatically port System.Xml.Xsl.Runtime.XmlQueryNodeSequence.OnItemsChanged triple slash
  xml/System.Xml.Xsl.Runtime/XmlQueryNodeSequence.xml
Labels: verify-build-before-merge

#3025 Display 0 as escaped
  xml/System.Windows.Forms/TextBox.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, verify-build-before-merge
