Repository dotnet/dotnet-api-docs, pull requests merged in 2020-02, with the labels that each got.

#3780 Update and add documentation for Rfc3161TimestampToken
  xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampToken.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3861 Fix link to EXCEPTION_POINTERS
  xml/System.Runtime.InteropServices/Marshal.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3846 Update DbConnectionStringBuilder.xml
  xml/System.Data.Common/DbConnectionStringBuilder.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3820 Update ISOWeek.xml
  xml/System.Globalization/ISOWeek.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3768 Fixes #3724 - Remark about RegularExpression attribute
  xml/System.ComponentModel.DataAnnotations/RegularExpressionAttribute.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3781 Add usage examples for the new FileSystemAclExtensions file and directory creation methods
  xml/System.IO/DirectoryInfo.xml
  xml/System.IO/File.xml
  xml/System.IO/FileStream.xml
  xml/System.IO/FileSystemAclExtensions.xml
Labels: doc-enhancement

#3854 Fix HttpWebRequest.IfModifiedSince
  xml/System.Net/HttpWebRequest.xml
Labels: :card_file_box: Technology - NCL

#3866 SignedCMS.ComputeSignature change for .NET Core
  xml/System.Security.Cryptography.Pkcs/SignedCms.xml
Labels: verify-build-before-merge

#3873 Delete Windows 2000 notes
  xml/Microsoft.VisualBasic.ApplicationServices/WindowsFormsApplicationBase.xml
  xml/Microsoft.VisualBasic.Devices/ComputerInfo.xml
  xml/Microsoft.VisualBasic.Devices/Network.xml
  xml/System.EnterpriseServices/ContextUtil.xml
  xml/System.IO/Directory.xml
  xml/System.IO/DirectoryInfo.xml
  xml/System.IO/FileInfo.xml
  xml/System.IO/FileSystemWatcher.xml
  xml/System.Net.NetworkInformation/IPInterfaceProperties.xml
  xml/System.Net.NetworkInformation/NetworkAddressChangedEventHandler.xml
  xml/System.Net.NetworkInformation/NetworkAvailabilityChangedEventHandler.xml
  xml/System.Net.NetworkInformation/NetworkChange.xml
  xml/System.Net.NetworkInformation/Ping.xml
  xml/System.Net.Sockets/IOControlCode.xml
  xml/System.Net.Sockets/Socket.xml
  xml/System.Runtime.InteropServices/Marshal.xml
  xml/System.Security/SecureStringMarshal.xml
  xml/System.Windows.Forms/Keys.xml
  xml/System/ConsoleKey.xml
Labels: verify-build-before-merge

#3867 add missing samples
  xml/System.Web.UI/ClientIDMode.xml
  xml/System.Web.UI/Control.xml
Labels: migration-fixes

#3876 fixes for missing param content
  xml/Microsoft.JScript.Vsa/ResInfo.xml
  xml/Microsoft.Vsa/VsaException.xml
  xml/Microsoft.Vsa/VsaLoader.xml
  xml/Microsoft_VsaVb/VsaEngineClass.xml
  xml/System.Drawing.Design/IconEditor.xml
  xml/System.Net/FileWebResponse.xml
  xml/System.Net/WriteStreamClosedEventHandler.xml
  xml/System.ServiceModel.Channels/UdpTransportBindingElement.xml
  xml/System.Web.Hosting/LowPhysicalMemoryObserver.xml
  xml/System.Web.Hosting/RecycleLimitObserver.xml
Labels: vendor-project

#3882 add missing docs
  xml/System.Windows.Navigation/BaseUriHelper.xml
Labels: migration-fixes

#3771 Remark for null in UWP
  xml/System.ComponentModel/INotifyPropertyChanged.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3875 Automatically port remarks for Reflection and Security APIs
  xml/Microsoft.Win32/CommonDialog.xml
  xml/System.Reflection.PortableExecutable/DebugDirectoryEntryType.xml
Labels: new-content

#3868 HidePrefix and PrefixOnly are still effective
  xml/System.Windows.Forms/TextFormatFlags.xml
Labels: verify-build-before-merge

#3884 Correct redundancy in Object.xml
  xml/System/Object.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3894 updating for Try .NET -- final set of first round
  xml/System.Text/Encoding.xml
  xml/System.Text/StringBuilder.xml
  xml/System/DateTime.xml
  xml/System/Func`2.xml
  xml/System/Int32.xml
Labels: vendor-project

#3933 System.IO 1.x undocumented APIs
  xml/System.IO.Pipes/PipesAclExtensions.xml
Labels: new-content, waiting-on-reviews

#3939 System.Threading.Tasks.Dataflow automatic port of comments
  xml/System.Threading.Tasks.Dataflow/BatchedJoinBlock`2.xml
  xml/System.Threading.Tasks.Dataflow/BatchedJoinBlock`3.xml
  xml/System.Threading.Tasks.Dataflow/JoinBlock`2.xml
  xml/System.Threading.Tasks.Dataflow/JoinBlock`3.xml
Labels: Release: .NET Core 1.x, new-content, waiting-on-reviews

#3941 Marshal and SafeBuffer doc updates
  xml/System.Runtime.InteropServices/Marshal.xml
  xml/System.Runtime.InteropServices/SafeBuffer.xml
Labels: Release: .NET Core 1.x, new-content

#3943 Rename readerOptions to options in JsonDocument exceptions
  xml/System.Text.Json/JsonDocument.xml
Labels: doc-bug, waiting-on-reviews

#3937 Add try.net to a few more examples in batch 1
  xml/System.Collections.Generic/List`1.xml
  xml/System/DateTime.xml
  xml/System/Enum.xml
Labels: verify-build-before-merge

#3936 For obsolote method alternate suggesting XmlDateTimeSerializationMode
  xml/System.Xml/XmlConvert.xml
Labels: new-content
