Repository dotnet/dotnet-api-docs, pull requests merged in 2020-05, with the labels that each got.

#4191 Added missing plural to the work "block"
  xml/System.Threading.Tasks.Dataflow/ExecutionDataflowBlockOptions.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4196 .NET Interactive: Enable_try_dotnet_to_batch_7b
  xml/System.Collections.Generic/Queue`1.xml
Labels: :woman_technologist: .NET Interactive

#4122 Update links to "LINQ: Building an IQueryable Provider" tutorial
  xml/System.Linq/IOrderedQueryable.xml
  xml/System.Linq/IOrderedQueryable`1.xml
  xml/System.Linq/IQueryProvider.xml
  xml/System.Linq/IQueryable.xml
  xml/System.Linq/IQueryable`1.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4192 .NET Interactive: Enable_try_dotnet_to_batch_7a
  xml/System.Collections.Generic/Dictionary`2.xml
  xml/System.Collections.Generic/ICollection`1.xml
  xml/System.Collections.Generic/IDictionary`2.xml
  xml/System.Collections.Generic/LinkedListNode`1.xml
  xml/System/Array.xml
Labels: :woman_technologist: .NET Interactive, changes-addressed

#4202 .NET Interactive: Enable_try_dotnet_to_batch_7c
  xml/System.Collections.Generic/SortedDictionary`2.xml
  xml/System/Object.xml
Labels: :woman_technologist: .NET Interactive, changes-addressed

#4219 Enable .NET Interactive - Example for batch 8
  xml/System/Char.xml
Labels: :woman_technologist: .NET Interactive

#4232 Add Uri Security Considerations section
  xml/System/Uri.xml
Labels: :card_file_box: Technology - NCL

#4240 Update data refresh description on DirectoryInfo.Create
  xml/System.IO/DirectoryInfo.xml
  xml/System.IO/FileSystemInfo.xml
Labels: doc-enhancement

#4222 .NET Interactive: Enable_try_dotnet_to_batch_8a
  xml/System/Char.xml
Labels: :woman_technologist: .NET Interactive

#4267 Document that System.Uri is thread-safe
  xml/System/Uri.xml
Labels: :card_file_box: Technology - NCL

#4246 .NET Interactive: Enable_try_dotnet_to_batch_8b
  xml/System/Char.xml
Labels: :woman_technologist: .NET Interactive

#4263 Add proxy credentials remark to HttpHandler.UseDefaultCredentials
  xml/System.Net.Http/HttpClientHandler.xml
Labels: :card_file_box: Technology - NCL

#4234 Automatically port new System.Threading ACL documentation
  xml/System.Threading/EventWaitHandleAcl.xml
  xml/System.Threading/MutexAcl.xml
  xml/System.Threading/SemaphoreAcl.xml
  xml/System.Threading/ThreadingAclExtensions.xml
Labels: :checkered_flag: Release: .NET 5

#4294 Automatically port 5.0 System.Collections documentation
  xml/System.Collections.Concurrent/BlockingCollection`1.xml
  xml/System.Collections.Concurrent/ConcurrentBag`1.xml
  xml/System.Collections.Concurrent/ConcurrentDictionary`2.xml
  xml/System.Collections.Concurrent/ConcurrentQueue`1.xml
  xml/System.Collections.Concurrent/ConcurrentStack`1.xml
  xml/System.Collections.Generic/IReadOnlySet`1.xml
  xml/System.Collections.Generic/SynchronizedCollection`1.xml
  xml/System.Collections.Generic/SynchronizedReadOnlyCollection`1.xml
  xml/System.Collections.Immutable/ImmutableArray`1.xml
  xml/System.Collections.Immutable/ImmutableDictionary`2+Builder.xml
  xml/System.Collections.Immutable/ImmutableDictionary`2.xml
  xml/System.Collections.Immutable/ImmutableHashSet`1+Builder.xml
  xml/System.Collections.Immutable/ImmutableSortedDictionary`2.xml
  xml/System.Collections.Immutable/ImmutableSortedSet`1+Builder.xml
  xml/System.Collections.Specialized/OrderedDictionary.xml
Labels: :checkered_flag: Release: .NET 5, new-content
