Repository dotnet/dotnet-api-docs, pull requests merged in 2020-04, with the labels that each got.

#4043 .NET Interactive - Enable try dotnet to batch1
  xml/System.Linq/Enumerable.xml
Labels: vendor-project, verify-build-before-merge

#4063 Document missing value in TimeSpan CompareTo EII
  xml/System/TimeSpan.xml
Labels: Release: .NET Core 1.x, new-content

#3881 fix missing param content
  xml/System.Web.ModelBinding/DataAnnotationsModelValidationFactory.xml
  xml/System.Web.ModelBinding/DataAnnotationsValidatableObjectAdapterFactory.xml
  xml/System.Web.ModelBinding/ModelBinderErrorMessageProvider.xml
  xml/System.Web.UI.WebControls/CreatingModelDataSourceEventHandler.xml
  xml/System.Windows.Forms/Control+ControlCollection.xml
  xml/System.Windows.Forms/DomainUpDown.xml
  xml/System.Windows.Forms/ListViewItem+ListViewSubItemCollection.xml
  xml/System.Windows.Forms/Splitter.xml
Labels: vendor-project

#4073 Update NegotiateStream with async code
  samples/snippets/csharp/VS_Snippets_Remoting/NclNegoAsyncServer/CS/server.cs
  samples/snippets/csharp/VS_Snippets_Remoting/NclNegoasyncClient/CS/client.cs
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4075 Redundant variable usage
  samples/snippets/csharp/VS_Snippets_CLR_System/system.threading.tasks.parallelloopstate/cs/break1.cs
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4068 .NET Interactive - enable try dotnet to batch2
  samples/snippets/cpp/VS_Snippets_CLR_System/system.String.EndsWithCmp/cpp/ewcmp.cpp
  samples/snippets/csharp/VS_Snippets_CLR_System/system.String.EndsWithCmp/cs/ewcmp.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.string.EndsWithCI/cs/ewci.cs
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.String.EndsWithCmp/vb/ewcmp.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.string.EndsWithCI/vb/ewci.vb
  xml/System/String.xml
Labels: vendor-project

#4085 .NET Interactive: Enable try dotnet to batch3(a)
  xml/System/Math.xml
Labels: vendor-project

#4094 Enable .NET Interactive on partially enabled APIs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.math.round.overload/cs/midpoint1.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.math.round.overload/cs/midpoint2.cs
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.math.round.overload/vb/midpoint1.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.math.round.overload/vb/midpoint2.vb
  xml/System.Text/StringBuilder.xml
  xml/System/Math.xml
  xml/System/Random.xml
  xml/System/String.xml
Labels: :woman_technologist: .NET Interactive

#4060 Add missing docs for System.Collections.Immutable
  xml/System.Collections.Immutable/ImmutableArray.xml
  xml/System.Collections.Immutable/ImmutableArray`1+Builder.xml
  xml/System.Collections.Immutable/ImmutableArray`1.xml
  xml/System.Collections.Immutable/ImmutableDictionary`2+Builder.xml
  xml/System.Collections.Immutable/ImmutableDictionary`2+Enumerator.xml
  xml/System.Collections.Immutable/ImmutableDictionary`2.xml
  xml/System.Collections.Immutable/ImmutableHashSet`1+Builder.xml
  xml/System.Collections.Immutable/ImmutableHashSet`1+Enumerator.xml
  xml/System.Collections.Immutable/ImmutableHashSet`1.xml
  xml/System.Collections.Immutable/ImmutableInterlocked.xml
  xml/System.Collections.Immutable/ImmutableList`1+Builder.xml
  xml/System.Collections.Immutable/ImmutableList`1+Enumerator.xml
  xml/System.Collections.Immutable/ImmutableList`1.xml
  xml/System.Collections.Immutable/ImmutableQueue`1.xml
  xml/System.Collections.Immutable/ImmutableSortedDictionary`2+Builder.xml
  xml/System.Collections.Immutable/ImmutableSortedDictionary`2+Enumerator.xml
  xml/System.Collections.Immutable/ImmutableSortedDictionary`2.xml
  xml/System.Collections.Immutable/ImmutableSortedSet`1+Builder.xml
  xml/System.Collections.Immutable/ImmutableSortedSet`1+Enumerator.xml
  xml/System.Collections.Immutable/ImmutableSortedSet`1.xml
Labels: Release: .NET Core 1.x, changes-addressed, new-content

#4066 Add note about HttpClientHandler
  xml/System.Net.Http/HttpClientHandler.xml
Labels: :card_file_box: Technology - NCL

#4072 HttpListener.IsSupported always returns true
  xml/System.Net/HttpListener.xml
Labels: :card_file_box: Technology - NCL

#4110 .NET Interactive: Enable_try_dotnet_to_batch_4a
  xml/System.Text.RegularExpressions/Capture.xml
  xml/System.Text.RegularExpressions/CaptureCollection.xml
  xml/System.Text.RegularExpressions/Group.xml
  xml/System.Text.RegularExpressions/GroupCollection.xml
  xml/System.Text.RegularExpressions/Match.xml
  xml/System.Text.RegularExpressions/MatchCollection.xml
  xml/System.Text.RegularExpressions/MatchEvaluator.xml
Labels: :woman_technologist: .NET Interactive, vendor-project, verify-build-before-merge

#4081 update the docs for System.Runtime.CompilerServices.Unsafe
  xml/System.Runtime.CompilerServices/AsyncValueTaskMethodBuilder`1.xml
  xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.xml
  xml/System.Runtime.CompilerServices/TupleElementNamesAttribute.xml
  xml/System.Runtime.CompilerServices/ValueTaskAwaiter`1.xml
Labels: Project, Release: .NET Core 1.x, new-content

#4116 .NET Interactive: Enable_try_dotnet_to_batch_4b
  xml/System.Text.RegularExpressions/Regex.xml
  xml/System.Text.RegularExpressions/RegexOptions.xml
Labels: :woman_technologist: .NET Interactive, vendor-project

#4123 .NET Interactive: Enable_try_dotnet_to_batch_5a
  xml/System/Int16.xml
  xml/System/Int32.xml
  xml/System/Int64.xml
  xml/System/StringSplitOptions.xml
Labels: :woman_technologist: .NET Interactive, vendor-project

#4135 readd missing sample
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Text.RegularExpressions.Regex.Split/cs/split6.cs
  xml/System.Text.RegularExpressions/Regex.xml
Labels: :woman_technologist: .NET Interactive

#4145 Corrected url to the blogpost with code
  xml/System/Progress`1.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4157 Auto-generated changes for System.Xml
  xml/System.Xml.Serialization/XmlAnyElementAttributes.xml
  xml/System.Xml.Serialization/XmlArrayItemAttributes.xml
  xml/System.Xml.Serialization/XmlElementAttributes.xml
  xml/System.Xml.Serialization/XmlSchemaEnumerator.xml
  xml/System.Xml.Xsl.Runtime/ContentMergeIterator.xml
  xml/System.Xml.Xsl.Runtime/XmlQuerySequence`1.xml
  xml/System.Xml/XmlNodeList.xml
Labels: Release: .NET Core 1.x, new-content

#4147 Auto port System.Threading ACL comments
  xml/System.Threading/EventWaitHandleAcl.xml
  xml/System.Threading/MutexAcl.xml
  xml/System.Threading/SemaphoreAcl.xml
Labels: :checkered_flag: Release: .NET Core 3.1, new-content

#4151 .NET Interactive: Enable_try_dotnet_to_batch_5b
  xml/System.Linq/Enumerable.xml
  xml/System/Object.xml
  xml/System/String.xml
Labels: :woman_technologist: .NET Interactive

#4167 .NET Interactive: Enable_try_dotnet_to_batch6a
  xml/System.Collections.Generic/LinkedList`1.xml
  xml/System.Collections.Generic/List`1.xml
Labels: :woman_technologist: .NET Interactive

#4171 .NET Interactive: Enable_try_dotnet_to_batch_6b
  xml/System.Collections.Generic/List`1.xml
Labels: :woman_technologist: .NET Interactive

#4121 Add missing docs for System.Collections[.Generic]
  xml/System.Collections.Generic/Dictionary`2.xml
  xml/System.Collections.Generic/KeyValuePair`2.xml
  xml/System.Collections.Generic/Queue`1.xml
  xml/System.Collections.Generic/ReferenceEqualityComparer.xml
  xml/System.Collections.Generic/Stack`1.xml
  xml/System.Collections/BitArray.xml
  xml/System.Collections/DictionaryEntry.xml
Labels: Release: .NET Core 1.x, new-content

#3444 Update ObjectSecurity.xml
  xml/System.Security.AccessControl/ObjectSecurity.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4176 .NET Interactive: Enable_try_dotnet_to_batch_6c
  xml/System.Collections.Generic/List`1.xml
Labels: :woman_technologist: .NET Interactive
