Repository dotnet/dotnet-api-docs, pull requests merged in 2020-07, with the labels that each got.

#4455 .NET Interactive: Enable_try_dotnet_to_batch_13a
  xml/System.Globalization/RegionInfo.xml
  xml/System.Globalization/StringInfo.xml
  xml/System/Attribute.xml
  xml/System/BitConverter.xml
  xml/System/Decimal.xml
  xml/System/Enum.xml
  xml/System/TimeSpan.xml
Labels: :woman_technologist: .NET Interactive

#4425 NET Interactive: Enable_try_dotnet_to_batch_12d
  xml/System/Byte.xml
  xml/System/Exception.xml
Labels: :woman_technologist: .NET Interactive

#4457 Samples fixes for Batch 13 of .NET Interactive changes
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Attribute.TypeId/CPP/typeid.cpp
  samples/snippets/cpp/VS_Snippets_CLR_System/system.BitConverter.ToXXX.Others/CPP/batochar.cpp
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Globalization.DateTimeFormatInfo.LongDatePattern/CPP/dtfi_longdatepattern.cpp
  samples/snippets/csharp/VS_Snippets_CLR/RNGCSP/CS/rngcsp.cs
  samples/snippets/csharp/VS_Snippets_CLR/StringInfo/CS/StringInfo.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Attribute.TypeId/CS/typeid.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.BitConverter.ToXXX.Others/CS/batochar.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Globalization.DateTimeFormatInfo.LongDatePattern/CS/dtfi_longdatepattern.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Globalization.DateTimeFormatInfo.LongDatePattern/CS/longdatepattern1.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Globalization.DateTimeFormatInfo.LongDatePattern/CS/longdatepattern2.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Int64.ToString/cs/ToString.cs
  samples/snippets/visualbasic/VS_Snippets_CLR/RNGCSP/VB/rngcsp.vb
  samples/snippets/visualbasic/VS_Snippets_CLR/StringInfo/vb/stringinfo.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Attribute.TypeId/VB/typeid.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.BitConverter.ToXXX.Others/VB/batochar.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Globalization.DateTimeFormatInfo.LongDatePattern/VB/dtfi_longdatepattern.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Globalization.DateTimeFormatInfo.LongDatePattern/VB/longdatepattern1.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Globalization.DateTimeFormatInfo.LongDatePattern/VB/longdatepattern2.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Int64.ToString/vb/ToString.vb
Labels: :woman_technologist: .NET Interactive

#4461 Fix typo in metadata
  xml/System.Reflection.Metadata/PEReaderExtensions.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4369 .NET Interactive: Enable_try_dotnet_to_batch_11b
  xml/System/Boolean.xml
  xml/System/DateTime.xml
  xml/System/Decimal.xml
  xml/System/Enum.xml
  xml/System/Type.xml
Labels: :woman_technologist: .NET Interactive

#4463 .NET Interactive: Enable_try_dotnet_to_batch_13b
  xml/System.Linq/Queryable.xml
  xml/System.Security.Cryptography/SymmetricAlgorithm.xml
  xml/System.Text/StringBuilder.xml
  xml/System/BitConverter.xml
  xml/System/Enum.xml
  xml/System/Int64.xml
  xml/System/TimeSpan.xml
Labels: :woman_technologist: .NET Interactive

#4361 .NET Interactive: Enable_try_dotnet_to_batch_11a
  xml/System/ArgumentException.xml
  xml/System/Array.xml
  xml/System/Convert.xml
  xml/System/FormatException.xml
  xml/System/InvalidOperationException.xml
Labels: :woman_technologist: .NET Interactive

#4479 Fix infinite loop
  samples/snippets/csharp/VS_Snippets_CLR_System/System.ArgumentOutOfRangeException/cs/FindWords1.cs
Labels: :woman_technologist: .NET Interactive

#4472 .NET Interactive: Enable_try_dotnet_to_batch_13c
  xml/System.Globalization/DateTimeFormatInfo.xml
  xml/System.Linq/Queryable.xml
  xml/System.Security.Cryptography/Oid.xml
  xml/System.Security.Cryptography/RNGCryptoServiceProvider.xml
  xml/System/Array.xml
  xml/System/Func`4.xml
Labels: :woman_technologist: .NET Interactive

#4487 .NET Interactive: Enable_try_dotnet_to_batch_14a
  xml/System.Collections.Specialized/NameValueCollection.xml
  xml/System.Linq/Queryable.xml
  xml/System.Text/Encoder.xml
  xml/System.Text/UTF8Encoding.xml
  xml/System/ArgumentOutOfRangeException.xml
  xml/System/IndexOutOfRangeException.xml
  xml/System/Type.xml
Labels: :woman_technologist: .NET Interactive

#4494 .NET Interactive: Enable_dotnet_to_batch_14b
  xml/System.Globalization/DateTimeFormatInfo.xml
  xml/System.Globalization/NumberFormatInfo.xml
  xml/System/TimeSpan.xml
  xml/System/TimeZoneInfo.xml
  xml/System/Tuple`4.xml
  xml/System/Type.xml
  xml/System/Version.xml
Labels: :woman_technologist: .NET Interactive

#4511 Markdown code block in TransactionEventArgs
  xml/System.Transactions/TransactionEventArgs.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4510 Fix Typo
  samples/snippets/csharp/VS_Snippets_Wpf/DataTemplatingIntro_snip/CSharp/Window1.xaml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4501 .NET Interactive: Enable_try_dotnet_to_batch_14c
  xml/System.Collections.Generic/Stack`1.xml
  xml/System.Security.Cryptography/HashAlgorithm.xml
  xml/System.Text/StringBuilder.xml
  xml/System/BitConverter.xml
  xml/System/Decimal.xml
  xml/System/Type.xml
Labels: :woman_technologist: .NET Interactive

#4521 .NET Interactive: Enable_try_dotnet_to_batch_15a
  xml/System.Collections.Specialized/ListDictionary.xml
  xml/System.Collections.Specialized/StringCollection.xml
Labels: :woman_technologist: .NET Interactive

#4526 Improve sample and sample outputs
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary2/CPP/hybriddictionary.cpp
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary_AddRemove/CPP/hybriddictionary_addremove.cpp
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary_Contains/CPP/hybriddictionary_contains.cpp
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary_CopyTo/CPP/hybriddictionary_copyto.cpp
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary_Enumerator/CPP/hybriddictionary_enumerator.cpp
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Collections.Specialized.ListDictionary_AddRemove/CPP/listdictionary_addremove.cpp
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Collections.Specialized.OrderedDictionary1/cpp/ordereddictionary1.cpp
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Text.Encoding.GetChars/CPP/getchars.cpp
  samples/snippets/cpp/VS_Snippets_Remoting/NCLUriEnhancements/CPP/nclurienhancements.cpp
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary2/CS/hybriddictionary.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary_AddRemove/CS/hybriddictionary_addremove.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary_Contains/CS/hybriddictionary_contains.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary_CopyTo/CS/hybriddictionary_copyto.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary_Enumerator/CS/hybriddictionary_enumerator.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Collections.Specialized.ListDictionary_AddRemove/CS/listdictionary_addremove.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Collections.Specialized.OrderedDictionary1/CS/OrderedDictionary1.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Text.Encoding.GetChars/CS/getchars.cs
  samples/snippets/csharp/VS_Snippets_Remoting/NCLUriEnhancements/CS/nclurienhancements.cs
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary2/VB/hybriddictionary.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary_AddRemove/VB/hybriddictionary_addremove.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary_Contains/VB/hybriddictionary_contains.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary_CopyTo/VB/hybriddictionary_copyto.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Collections.Specialized.HybridDictionary_Enumerator/VB/hybriddictionary_enumerator.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Collections.Specialized.ListDictionary_AddRemove/VB/listdictionary_addremove.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Collections.Specialized.OrderedDictionary1/VB/OrderedDictionary1.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Text.Encoding.GetChars/VB/getchars.vb
  samples/snippets/visualbasic/VS_Snippets_Remoting/NCLUriEnhancements/VB/nclurienhancements.vb
Labels: :woman_technologist: .NET Interactive

#4491 Fix PipeOptions ctor pauseWriterThreshold
  xml/System.IO.Pipelines/PipeOptions.xml
Labels: doc-bug

#3744 Note performance counter permission distinction for interactive logons
  xml/System.Diagnostics/PerformanceCounter.xml
  xml/System.Diagnostics/PerformanceCounterCategory.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4529 Update ComboBox.xml
  xml/System.Windows.Forms/ComboBox.xml
Labels: :card_file_box: Technology - WinForms

#4531 .NET Interactive: Enable_dotnet_to_batch_15b
  xml/System.Collections.Specialized/ListDictionary.xml
  xml/System.Collections.Specialized/StringCollection.xml
Labels: :woman_technologist: .NET Interactive

#4567 .NET Interactive: Enable_try_dotnet_to_batch_16b
  xml/System.Collections.Generic/SortedList`2.xml
  xml/System.Collections.Specialized/HybridDictionary.xml
  xml/System.Text/UTF32Encoding.xml
  xml/System/Decimal.xml
  xml/System/Type.xml
  xml/System/Uri.xml
Labels: :woman_technologist: .NET Interactive

#4570 .NET Interactive: Enable_try_dotnet_to_batch_16c
  xml/System.Collections.Specialized/HybridDictionary.xml
Labels: :woman_technologist: .NET Interactive

#4549 .NET Interactive: Enable_try_dotnet_to_batch_16a
  xml/System.Collections.Specialized/OrderedDictionary.xml
  xml/System.Globalization/DateTimeFormatInfo.xml
  xml/System.Globalization/NumberFormatInfo.xml
  xml/System.Security.Cryptography/KeyedHashAlgorithm.xml
  xml/System.Text/Encoding.xml
  xml/System.Text/StringBuilder.xml
  xml/System/Buffer.xml
  xml/System/Double.xml
  xml/System/TimeSpan.xml
  xml/System/Uri.xml
Labels: :woman_technologist: .NET Interactive, verify-build-before-merge
