Repository dotnet/dotnet-api-docs, pull requests merged in 2020-09, with the labels that each got.

#4712 .NET Interactive; Add try dotnet to batch 19c
  xml/System.Globalization/NumberFormatInfo.xml
  xml/System/Exception.xml
Labels: :woman_technologist: .NET Interactive

#4709 .NET Interactive: Add try dotnet to batch 19b
  xml/System.Globalization/NumberFormatInfo.xml
  xml/System.Security.Cryptography/HashAlgorithm.xml
  xml/System.Security.Cryptography/RijndaelManaged.xml
  xml/System/Convert.xml
  xml/System/Exception.xml
  xml/System/IComparable.xml
  xml/System/Version.xml
Labels: :woman_technologist: .NET Interactive

#4753 .NET Interactive: Add try dotnet to batch 20b
  xml/System/Uri.xml
Labels: :woman_technologist: .NET Interactive

#4740 .NET Interactive: Add try dotnet to batch 20a
  xml/System/Uri.xml
Labels: :woman_technologist: .NET Interactive

#4736 CornerRadius.xml - typo fixed
  xml/System.Windows/CornerRadius.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3810 Update Semaphore.xml
  xml/System.Threading/Semaphore.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4756 Batch 20 - sample improvements
  samples/snippets/cpp/VS_Snippets_Remoting/NCLUriExamples/CPP/uriexamples.cpp
  samples/snippets/csharp/VS_Snippets_Remoting/Classic Uri.AbsolutePath Example/CS/source.cs
  samples/snippets/csharp/VS_Snippets_Remoting/Classic Uri.AbsoluteUri Example/CS/source.cs
  samples/snippets/csharp/VS_Snippets_Remoting/Classic Uri.Host Example/CS/source.cs
  samples/snippets/csharp/VS_Snippets_Remoting/Classic Uri.PathAndQuery Example/CS/source.cs
  samples/snippets/csharp/VS_Snippets_Remoting/Classic Uri.Port Example/CS/source.cs
  samples/snippets/csharp/VS_Snippets_Remoting/Classic Uri.Scheme Example/CS/source.cs
  samples/snippets/csharp/VS_Snippets_Remoting/NCLUriExamples/CS/uriexamples.cs
  samples/snippets/visualbasic/VS_Snippets_Remoting/NCLUriExamples/VB/uriexamples.vb
  xml/System/Uri.xml
Labels: :woman_technologist: .NET Interactive

#4767 .NET Interactive: Add try dotnet to batch 20c
  xml/System/Uri.xml
Labels: :woman_technologist: .NET Interactive, verify-build-before-merge

#4773 Automatic port of System.Diagnostics.Activity* docs
  xml/System.Diagnostics.CodeAnalysis/ExcludeFromCodeCoverageAttribute.xml
  xml/System.Diagnostics/Activity.xml
  xml/System.Diagnostics/ActivityContext.xml
  xml/System.Diagnostics/ActivityCreationOptions`1.xml
  xml/System.Diagnostics/ActivityEvent.xml
  xml/System.Diagnostics/ActivityKind.xml
  xml/System.Diagnostics/ActivityLink.xml
  xml/System.Diagnostics/ActivityListener.xml
  xml/System.Diagnostics/ActivitySource.xml
  xml/System.Diagnostics/ActivityTagsCollection+Enumerator.xml
  xml/System.Diagnostics/ActivityTagsCollection.xml
Labels: new-content

#4106 Docs for Extensions: FileProviders and Hosting
  xml/Microsoft.Extensions.FileProviders.Composite/CompositeDirectoryContents.xml
  xml/Microsoft.Extensions.FileProviders.Embedded/EmbeddedResourceFileInfo.xml
  xml/Microsoft.Extensions.FileProviders.Internal/PhysicalDirectoryContents.xml
  xml/Microsoft.Extensions.FileProviders.Physical/PhysicalDirectoryInfo.xml
  xml/Microsoft.Extensions.FileProviders.Physical/PhysicalFileInfo.xml
  xml/Microsoft.Extensions.FileProviders.Physical/PollingWildCardChangeToken.xml
  xml/Microsoft.Extensions.FileProviders/ManifestEmbeddedFileProvider.xml
  xml/Microsoft.Extensions.FileProviders/NotFoundDirectoryContents.xml
  xml/Microsoft.Extensions.FileProviders/NotFoundFileInfo.xml
  xml/Microsoft.Extensions.Hosting.Internal/ConsoleLifetime.xml
  xml/Microsoft.Extensions.Hosting.Internal/HostingEnvironment.xml
  xml/Microsoft.Extensions.Hosting/BackgroundService.xml
  xml/Microsoft.Extensions.Options/ConfigurationChangeTokenSource`1.xml
Labels: Release: .NET Core 1.x, new-content

#4783 Add documentation to System.Net.Http.Json APIs
  xml/System.Net.Http.Json/HttpClientJsonExtensions.xml
  xml/System.Net.Http.Json/HttpContentJsonExtensions.xml
  xml/System.Net.Http.Json/JsonContent.xml
  xml/ns-System.Net.Http.Json.xml
Labels: area-System.Net

#4782 Provide valid C# example and remove C++/CLI function definition.
  samples/snippets/csharp/VS_Snippets_CLR_System/system.runtime.interopservices.icustommarshaler/cs/source.cs
  xml/System.Runtime.InteropServices/ICustomMarshaler.xml
Labels: area-System.Runtime.InteropServices

#4777 Update docs for Half
  xml/System/Half.xml
Labels: area-System.Runtime

#4780 .NET Interactive: Add try dotnet to batch 20d
  xml/System/Uri.xml
Labels: :woman_technologist: .NET Interactive

#4826 .NET Interactive: Add try dotnet to batch 21a
  xml/System.Collections.Generic/IDictionary`2.xml
  xml/System.Linq/IGrouping`2.xml
  xml/System/Array.xml
  xml/System/Attribute.xml
  xml/System/BitConverter.xml
  xml/System/Boolean.xml
  xml/System/Decimal.xml
  xml/System/Exception.xml
  xml/System/MidpointRounding.xml
  xml/System/Nullable`1.xml
  xml/System/Type.xml
Labels: :woman_technologist: .NET Interactive

#4832 .NET Interactive: Add try dotnet to batch 21b
  samples/snippets/cpp/VS_Snippets_CLR_Classic/classic Array.CopyTo Example/CPP/source.cpp
  samples/snippets/cpp/VS_Snippets_CLR_Classic/classic Array.CopyTo Example/CPP/source2.cpp
  samples/snippets/csharp/VS_Snippets_CLR_Classic/classic Array.CopyTo Example/CS/source.cs
  samples/snippets/csharp/VS_Snippets_CLR_Classic/classic Array.CopyTo Example/CS/source2.cs
  samples/snippets/visualbasic/VS_Snippets_CLR_Classic/classic Array.CopyTo Example/VB/source.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_Classic/classic Array.CopyTo Example/VB/source2.vb
  xml/System.Globalization/Calendar.xml
  xml/System.Globalization/NumberStyles.xml
  xml/System/Array.xml
  xml/System/DateTime.xml
  xml/System/Enum.xml
  xml/System/InvalidCastException.xml
  xml/System/Single.xml
  xml/System/UriBuilder.xml
Labels: :woman_technologist: .NET Interactive, verify-build-before-merge

#4813 Update TableLayoutSettings.xml
  xml/System.Windows.Forms/TableLayoutSettings.xml
Labels: :card_file_box: Technology - WinForms

#4814 Update TableLayoutPanel.xml
  xml/System.Windows.Forms/TableLayoutPanel.xml
Labels: :card_file_box: Technology - WinForms

#4776 HttpClient sync operations
  xml/System.Net.Http/ByteArrayContent.xml
  xml/System.Net.Http/DelegatingHandler.xml
  xml/System.Net.Http/HttpClient.xml
  xml/System.Net.Http/HttpClientHandler.xml
  xml/System.Net.Http/HttpContent.xml
  xml/System.Net.Http/HttpMessageHandler.xml
  xml/System.Net.Http/HttpMessageInvoker.xml
  xml/System.Net.Http/MessageProcessingHandler.xml
  xml/System.Net.Http/MultipartContent.xml
  xml/System.Net.Http/ReadOnlyMemoryContent.xml
  xml/System.Net.Http/SocketsHttpHandler.xml
  xml/System.Net.Http/StreamContent.xml
Labels: new-content
