Repository dotnet/dotnet-api-docs, pull requests merged in 2020-08, with the labels that each got.

#4284 Automatically port 5.0 System.Text.Json documentation
  xml/System.Text.Json.Serialization/JsonConstructorAttribute.xml
  xml/System.Text.Json.Serialization/JsonIgnoreAttribute.xml
  xml/System.Text.Json.Serialization/JsonIgnoreCondition.xml
  xml/System.Text.Json.Serialization/JsonIncludeAttribute.xml
  xml/System.Text.Json/JsonElement+ArrayEnumerator.xml
  xml/System.Text.Json/JsonElement+ObjectEnumerator.xml
  xml/System.Text.Json/JsonSerializer.xml
  xml/System.Text.Json/JsonSerializerOptions.xml
  xml/System.Text.Json/Utf8JsonReader.xml
Labels: :checkered_flag: Release: .NET 5, new-content

#4618 Port XmlWriter.DisposeAsync documentation
  xml/System.Xml/XmlWriter.xml
Labels: new-content

#4623 Automatically port System.Linq documentation
  xml/System.Linq.Expressions/DynamicExpression.xml
  xml/System.Linq.Expressions/ElementInit.xml
  xml/System.Linq.Expressions/IndexExpression.xml
  xml/System.Linq.Expressions/InvocationExpression.xml
  xml/System.Linq.Expressions/MethodCallExpression.xml
  xml/System.Linq.Expressions/NewExpression.xml
  xml/System.Linq/EnumerableQuery`1.xml
  xml/System.Linq/Lookup`2.xml
  xml/System.Linq/ParallelQuery.xml
Labels: new-content

#4619 Automatic port of System.Text.Json documentation
  xml/System.Text.Json.Serialization/JsonConverter`1.xml
  xml/System.Text.Json.Serialization/ReferenceHandler.xml
  xml/System.Text.Json.Serialization/ReferenceHandler`1.xml
  xml/System.Text.Json.Serialization/ReferenceResolver.xml
  xml/System.Text.Json/JsonSerializerDefaults.xml
  xml/System.Text.Json/JsonSerializerOptions.xml
Labels: new-content

#4626 Automatic port of System.Threading documentation
  xml/System.Threading.Channels/ChannelReader`1.xml
  xml/System.Threading.Tasks/Task.xml
  xml/System.Threading.Tasks/TaskCompletionSource.xml
  xml/System.Threading.Tasks/TaskCompletionSource`1.xml
  xml/System.Threading.Tasks/ValueTask.xml
  xml/System.Threading/CancellationTokenSource.xml
  xml/System.Threading/Interlocked.xml
Labels: new-content

#4627 Automatic port of System.Text.RegularExpressions documentation
  xml/System.Text.RegularExpressions/CaptureCollection.xml
  xml/System.Text.RegularExpressions/GroupCollection.xml
  xml/System.Text.RegularExpressions/RegexMatchTimeoutException.xml
Labels: new-content

#4629 Automatic port of System.Buffers documentation
  xml/System.Buffers.Binary/BinaryPrimitives.xml
  xml/System.Buffers/SequenceReader`1.xml
Labels: new-content

#4604 .NET Interactive: Enable_try_dotnet_to_batch_17b
  xml/System/Decimal.xml
Labels: :woman_technologist: .NET Interactive

#4605 .NET Interactive: Enable_try_dotnet_to_batch_17c
  xml/System.Text/ASCIIEncoding.xml
  xml/System/BitConverter.xml
Labels: :woman_technologist: .NET Interactive

#4620 Automatic port of System.Net documentation
  xml/System.Net.Http.Headers/AuthenticationHeaderValue.xml
  xml/System.Net.Http.Headers/CacheControlHeaderValue.xml
  xml/System.Net.Http.Headers/ContentDispositionHeaderValue.xml
  xml/System.Net.Http.Headers/ContentRangeHeaderValue.xml
  xml/System.Net.Http.Headers/EntityTagHeaderValue.xml
  xml/System.Net.Http.Headers/HttpHeaderValueCollection`1.xml
  xml/System.Net.Http.Headers/HttpHeaders.xml
  xml/System.Net.Http.Headers/MediaTypeHeaderValue.xml
  xml/System.Net.Http.Headers/MediaTypeWithQualityHeaderValue.xml
  xml/System.Net.Http.Headers/NameValueHeaderValue.xml
  xml/System.Net.Http.Headers/NameValueWithParametersHeaderValue.xml
  xml/System.Net.Http.Headers/ProductHeaderValue.xml
  xml/System.Net.Http.Headers/ProductInfoHeaderValue.xml
  xml/System.Net.Http.Headers/RangeConditionHeaderValue.xml
  xml/System.Net.Http.Headers/RangeHeaderValue.xml
  xml/System.Net.Http.Headers/RangeItemHeaderValue.xml
  xml/System.Net.Http.Headers/RetryConditionHeaderValue.xml
  xml/System.Net.Http.Headers/StringWithQualityHeaderValue.xml
  xml/System.Net.Http.Headers/TransferCodingHeaderValue.xml
  xml/System.Net.Http.Headers/TransferCodingWithQualityHeaderValue.xml
  xml/System.Net.Http.Headers/ViaHeaderValue.xml
  xml/System.Net.Http.Headers/WarningHeaderValue.xml
  xml/System.Net.Http.Json/HttpClientJsonExtensions.xml
  xml/System.Net.Http/MultipartContent.xml
  xml/System.Net.Mail/MailAddress.xml
  xml/System.Net.Sockets/Socket.xml
  xml/System.Net.Sockets/SocketAsyncEventArgs.xml
  xml/System.Net/CookieCollection.xml
  xml/System.Net/WebHeaderCollection.xml
  xml/System.Net/WebResponse.xml
Labels: new-content

#4628 Automatic port of System.Drawing documentation
  xml/System.Drawing.Design/ToolboxService.xml
  xml/System.Drawing.Imaging/Encoder.xml
  xml/System.Drawing.Imaging/EncoderParameterValueType.xml
  xml/System.Drawing.Printing/PrinterSettings+PaperSizeCollection.xml
  xml/System.Drawing.Printing/PrinterSettings+PaperSourceCollection.xml
  xml/System.Drawing.Printing/PrinterSettings+PrinterResolutionCollection.xml
  xml/System.Drawing.Printing/PrinterSettings+StringCollection.xml
  xml/System.Drawing/Color.xml
  xml/System.Drawing/FontConverter+FontNameConverter.xml
  xml/System.Drawing/PointF.xml
  xml/System.Drawing/Rectangle.xml
  xml/System.Drawing/RectangleF.xml
  xml/System.Drawing/Size.xml
  xml/System.Drawing/SizeF.xml
Labels: new-content

#4625 Automatic port of System.Text documentation
  xml/System.Text/Encoding.xml
  xml/System.Text/EncodingExtensions.xml
  xml/System.Text/EncodingInfo.xml
  xml/System.Text/Rune.xml
Labels: new-content

#4622 Automatically port System.Security documentation
  xml/System.Security.AccessControl/AuthorizationRuleCollection.xml
  xml/System.Security.AccessControl/GenericAcl.xml
  xml/System.Security.Authentication.ExtendedProtection/ServiceNameCollection.xml
  xml/System.Security.Permissions/KeyContainerPermissionAccessEntryCollection.xml
  xml/System.Security.Policy/ApplicationTrustCollection.xml
  xml/System.Security.Principal/IdentityReferenceCollection.xml
  xml/System.Security.Principal/WindowsIdentity.xml
  xml/System.Security/CodeAccessPermission.xml
Labels: new-content

#4624 Automatic port of System.Runtime.Intrinsics documentation
  xml/System.Runtime.Intrinsics.Arm/AdvSimd+Arm64.xml
  xml/System.Runtime.Intrinsics.Arm/AdvSimd.xml
  xml/System.Runtime.Intrinsics.Arm/Aes.xml
  xml/System.Runtime.Intrinsics.Arm/ArmBase+Arm64.xml
  xml/System.Runtime.Intrinsics.Arm/ArmBase.xml
  xml/System.Runtime.Intrinsics.Arm/Crc32+Arm64.xml
  xml/System.Runtime.Intrinsics.Arm/Crc32.xml
  xml/System.Runtime.Intrinsics.Arm/Sha1.xml
  xml/System.Runtime.Intrinsics.Arm/Sha256.xml
  xml/System.Runtime.Intrinsics.X86/Avx.xml
  xml/System.Runtime.Intrinsics.X86/Sse2.xml
  xml/System.Runtime.Intrinsics/Vector128.xml
  xml/System.Runtime.Intrinsics/Vector128`1.xml
  xml/System.Runtime.Intrinsics/Vector256.xml
  xml/System.Runtime.Intrinsics/Vector256`1.xml
  xml/System.Runtime.Intrinsics/Vector64.xml
  xml/System.Runtime.Intrinsics/Vector64`1.xml
Labels: new-content

#4648 output fixes for batch 17
  samples/snippets/cpp/VS_Snippets_CLR/Type_FindMembers/CPP/type_findmembers.cpp
  samples/snippets/cpp/VS_Snippets_CLR/Type_IsInterface/CPP/type_isinterface.cpp
  samples/snippets/cpp/VS_Snippets_CLR_Classic/classic Type.DeclaringType Example/CPP/source.cpp
  samples/snippets/csharp/VS_Snippets_CLR/Type_FindMembers/CS/type_findmembers.cs
  samples/snippets/csharp/VS_Snippets_CLR/Type_IsInterface/CS/type_isinterface.cs
  samples/snippets/csharp/VS_Snippets_CLR_Classic/classic Type.DeclaringType Example/CS/source.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.decimal.equals/cs/equalsoverl.cs
  samples/snippets/visualbasic/VS_Snippets_CLR/Type_FindMembers/VB/type_findmembers.vb
  samples/snippets/visualbasic/VS_Snippets_CLR/Type_IsInterface/VB/type_isinterface.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.decimal.equals/vb/equalsoverl.vb
Labels: :woman_technologist: .NET Interactive

#4649 Automatic port of System.Buffers exceptions
  xml/System.Buffers.Binary/BinaryPrimitives.xml
Labels: new-content

#4593 .NET Interactive: Enable_try_dotnet_to_batch_17a
  xml/System/Type.xml
Labels: :woman_technologist: .NET Interactive

#4665 Automatic port of System.IO exceptions
  xml/System.IO.Compression/ZipArchive.xml
  xml/System.IO.Compression/ZipArchiveEntry.xml
  xml/System.IO.Compression/ZipFile.xml
  xml/System.IO/FileSystemAclExtensions.xml
  xml/System.IO/Path.xml
Labels: new-content

#4661 Automatic port of System.Net exceptions
  xml/System.Net.Sockets/Socket.xml
Labels: new-content

#4657 Automatic port of System.Text exceptions
  xml/System.Text.RegularExpressions/Regex.xml
  xml/System.Text/EncodingExtensions.xml
Labels: new-content

#4659 Automatic port of System.Linq exceptions
  xml/System.Linq/ParallelEnumerable.xml
Labels: new-content

#4656 Automatic port of System.Threading exceptions
  xml/System.Threading.Channels/ChannelReader`1.xml
  xml/System.Threading.Tasks/Task.xml
  xml/System.Threading.Tasks/TaskCompletionSource.xml
  xml/System.Threading.Tasks/TaskCompletionSource`1.xml
  xml/System.Threading/Interlocked.xml
Labels: new-content

#4664 Batch 18 - Sample fixes for .NET Interactive
  samples/snippets/cpp/VS_Snippets_CLR/sys.txt.fallbackEncRpl/cpp/fallEncRpl.cpp
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Text.Encoding.ASCII Example/CPP/ascii.cpp
  samples/snippets/csharp/VS_Snippets_CLR/sys.txt.fallbackEncRpl/cs/fallEncRpl.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Text.Encoding.ASCII Example/CS/ascii.cs
  samples/snippets/visualbasic/VS_Snippets_CLR/sys.txt.fallbackEncRpl/vb/fallEncRpl.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Text.Encoding.ASCII Example/VB/ascii.vb
Labels: :woman_technologist: .NET Interactive

#4660 Automatic port of System.Text.Json exceptions
  xml/System.Text.Json/JsonSerializerOptions.xml
Labels: new-content

#4668 Automatic port of System.Formats.Asn1 documentation
  xml/System.Formats.Asn1/Asn1Tag.xml
  xml/System.Formats.Asn1/AsnDecoder.xml
  xml/System.Formats.Asn1/AsnEncodingRules.xml
  xml/System.Formats.Asn1/AsnReader.xml
  xml/System.Formats.Asn1/AsnReaderOptions.xml
  xml/System.Formats.Asn1/AsnWriter+Scope.xml
  xml/System.Formats.Asn1/AsnWriter.xml
  xml/System.Formats.Asn1/TagClass.xml
  xml/System.Formats.Asn1/UniversalTagNumber.xml
Labels: new-content

#4679 Batch 19 sample fixes
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.HResult/CPP/hresult.cpp
  samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Properties/CPP/properties.cpp
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.HResult/CS/hresult.cs
  samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Properties/CS/properties.cs
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.HResult/VB/hresult.vb
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Properties/VB/properties.vb
Labels: :woman_technologist: .NET Interactive

#4667 Automatic port of GC documentation
  xml/System/GC.xml
  xml/System/GCGenerationInfo.xml
  xml/System/GCKind.xml
  xml/System/GCMemoryInfo.xml
Labels: new-content

#4658 Automatic port of System.Runtime.Intrinsics exceptions
  xml/System.Runtime.Intrinsics/Vector128.xml
  xml/System.Runtime.Intrinsics/Vector128`1.xml
  xml/System.Runtime.Intrinsics/Vector256.xml
  xml/System.Runtime.Intrinsics/Vector256`1.xml
  xml/System.Runtime.Intrinsics/Vector64`1.xml
Labels: new-content

#4662 .NET Interactive: Enable_try_dotnet_to_batch_18a
  xml/System.Text/Encoding.xml
  xml/System.Text/UTF8Encoding.xml
Labels: :construction: Hold for related PR, :woman_technologist: .NET Interactive

#4582 CI Update - MSDN URL Update
  xml/System.ServiceModel.Configuration/WSDualHttpBindingCollectionElement.xml
  xml/System.ServiceModel.Configuration/WSDualHttpBindingElement.xml
  xml/System.ServiceModel.Configuration/WSFederationHttpBindingCollectionElement.xml
  xml/System.ServiceModel.Configuration/WSFederationHttpBindingElement.xml
  xml/System.ServiceModel.Configuration/WSHttpBindingCollectionElement.xml
  xml/System.ServiceModel.Configuration/WSHttpBindingElement.xml
  xml/System.ServiceModel.Configuration/WsdlImporterElementCollection.xml
  xml/System.ServiceModel.Configuration/X509ClientCertificateAuthenticationElement.xml
  xml/System.ServiceModel.Configuration/XPathMessageFilterElement.xml
  xml/System.ServiceModel.Configuration/XPathMessageFilterElementCollection.xml
  xml/System.ServiceModel.Description/DataContractSerializerOperationBehavior.xml
  xml/System.ServiceModel.Description/IMetadataExchange.xml
  xml/System.ServiceModel.Description/XmlSerializerOperationBehavior.xml
  xml/System.ServiceModel.Security/IdentityVerifier.xml
  xml/System.ServiceModel.Security/MessageProtectionOrder.xml
  xml/System.ServiceModel.Security/X509ClientCertificateAuthentication.xml
  xml/System.Threading/CancellationTokenSource.xml
  xml/System.Threading/SpinLock.xml
  xml/System.Threading/ThreadLocal`1.xml
  xml/System.Threading/WaitHandle.xml
  xml/System.Transactions/DependentTransaction.xml
  xml/System.Transactions/IEnlistmentNotification.xml
  xml/System.Transactions/TransactionInterop.xml
  xml/System.Web.Configuration/FormsAuthenticationCredentials.xml
  xml/System.Web.Configuration/HttpModuleAction.xml
  xml/System.Web.Configuration/TagMapInfo.xml
  xml/System.Web.Configuration/WebConfigurationManager.xml
  xml/System.Web.DynamicData/DynamicDataExtensions.xml
  xml/System.Web.Mail/MailMessage.xml
  xml/System.Web.UI.WebControls.Adapters/HideDisabledControlAdapter.xml
  xml/System.Web/HttpClientCertificate.xml
  xml/System.Windows.Automation/AndCondition.xml
  xml/System.Windows.Automation/AsyncContentLoadedEventArgs.xml
  xml/System.Windows.Automation/Automation.xml
  xml/System.Windows.Automation/AutomationElement+AutomationElementInformation.xml
  xml/System.Windows.Automation/AutomationElement.xml
  xml/System.Windows.Automation/AutomationElementIdentifiers.xml
  xml/System.Windows.Automation/AutomationElementMode.xml
  xml/System.Windows.Automation/AutomationEvent.xml
  xml/System.Windows.Automation/AutomationEventArgs.xml
  xml/System.Windows.Automation/AutomationEventHandler.xml
  xml/System.Windows/DataFormats.xml
  xml/System.Windows/DataTemplateKey.xml
  xml/System.Windows/FrameworkElement.xml
  xml/System.Windows/IFrameworkInputElement.xml
  xml/System.Windows/PropertyPath.xml
  xml/System.Windows/Style.xml
  xml/System.Windows/SystemParameters.xml
  xml/System.Windows/UIElement.xml
Labels: verify-build-before-merge

#4672 Automatic port of System.ComponentModel documentation
  xml/System.ComponentModel/AttributeCollection.xml
  xml/System.ComponentModel/BackgroundWorker.xml
  xml/System.ComponentModel/BindingList`1.xml
  xml/System.ComponentModel/GroupDescription.xml
  xml/System.ComponentModel/ListSortDescriptionCollection.xml
  xml/System.ComponentModel/PropertyDescriptorCollection.xml
  xml/System.ComponentModel/SortDescriptionCollection.xml
  xml/System.ComponentModel/TypeConverter+StandardValuesCollection.xml
Labels: new-content

#4663 Automatic port of System.Security exceptions
  xml/System.Security.Claims/ClaimsIdentity.xml
  xml/System.Security.Claims/ClaimsPrincipal.xml
  xml/System.Security.Cryptography.X509Certificates/CertificateRequest.xml
Labels: new-content

#4621 Automatic port of System.Security.Cryptography documentation
  xml/System.Security.Cryptography.Pkcs/CmsRecipientCollection.xml
  xml/System.Security.Cryptography.Pkcs/CmsRecipientEnumerator.xml
  xml/System.Security.Cryptography.Pkcs/RecipientInfoCollection.xml
  xml/System.Security.Cryptography.Pkcs/RecipientInfoEnumerator.xml
  xml/System.Security.Cryptography.Pkcs/SignerInfoCollection.xml
  xml/System.Security.Cryptography.Pkcs/SignerInfoEnumerator.xml
  xml/System.Security.Cryptography.X509Certificates/X509ChainPolicy.xml
  xml/System.Security.Cryptography/AsnEncodedDataCollection.xml
  xml/System.Security.Cryptography/AsnEncodedDataEnumerator.xml
  xml/System.Security.Cryptography/AsymmetricAlgorithm.xml
  xml/System.Security.Cryptography/CryptoAPITransform.xml
  xml/System.Security.Cryptography/CryptoStream.xml
  xml/System.Security.Cryptography/CryptographicAttributeObjectCollection.xml
  xml/System.Security.Cryptography/CryptographicAttributeObjectEnumerator.xml
  xml/System.Security.Cryptography/DSA.xml
  xml/System.Security.Cryptography/DSASignatureFormat.xml
  xml/System.Security.Cryptography/ECDiffieHellman.xml
  xml/System.Security.Cryptography/ECDsa.xml
  xml/System.Security.Cryptography/HKDF.xml
  xml/System.Security.Cryptography/HashAlgorithmName.xml
  xml/System.Security.Cryptography/OidCollection.xml
  xml/System.Security.Cryptography/OidEnumerator.xml
  xml/System.Security.Cryptography/PemEncoding.xml
  xml/System.Security.Cryptography/PemFields.xml
  xml/System.Security.Cryptography/RSA.xml
  xml/System.Security.Cryptography/RSAEncryptionPaddingMode.xml
  xml/System.Security.Cryptography/RSASignaturePaddingMode.xml
  xml/System.Security.Cryptography/RijndaelManagedTransform.xml
  xml/System.Security.Cryptography/SymmetricAlgorithm.xml
Labels: new-content

#4286 Automatically port 5.0 System.Runtime.InteropServices documentation
  xml/System.Runtime.InteropServices/CollectionsMarshal.xml
  xml/System.Runtime.InteropServices/ComWrappers+ComInterfaceDispatch.xml
  xml/System.Runtime.InteropServices/ComWrappers+ComInterfaceEntry.xml
  xml/System.Runtime.InteropServices/ComWrappers.xml
  xml/System.Runtime.InteropServices/CreateComInterfaceFlags.xml
  xml/System.Runtime.InteropServices/CreateObjectFlags.xml
  xml/System.Runtime.InteropServices/RuntimeInformation.xml
  xml/System.Runtime.InteropServices/SuppressGCTransitionAttribute.xml
Labels: :checkered_flag: Release: .NET 5, new-content

#4654 Fix example description
  xml/System.Windows/Trigger.xml
Labels: verify-build-before-merge

#4689 Automatic port of System.Collections exceptions
  xml/System.Collections.Concurrent/ConcurrentDictionary`2.xml
  xml/System.Collections.Generic/IReadOnlySet`1.xml
  xml/System.Collections.Immutable/ImmutableArray`1.xml
  xml/System.Collections.Immutable/ImmutableDictionary`2.xml
  xml/System.Collections.Immutable/ImmutableList`1.xml
  xml/System.Collections.Immutable/ImmutableQueue`1.xml
  xml/System.Collections.Immutable/ImmutableSortedDictionary`2.xml
  xml/System.Collections.Immutable/ImmutableStack`1.xml
Labels: new-content

#4693 .NET Interactive: Add try dotnet to batch 18c
  xml/System.Text/UTF8Encoding.xml
Labels: :woman_technologist: .NET Interactive

#4691 .NET Interactive: Add try dotnet to batch 18b
  xml/System.Text/Encoding.xml
Labels: :woman_technologist: .NET Interactive

#4666 Automatic port of System and System.Numerics documentation
  xml/System.Numerics/Vector.xml
  xml/System/Decimal.xml
  xml/System/Half.xml
  xml/System/IntPtr.xml
  xml/System/Math.xml
  xml/System/MemoryExtensions.xml
  xml/System/StringSplitOptions.xml
  xml/System/UIntPtr.xml
Labels: new-content

#4702 .NET Interactive: Add try dotnet to batch 19a
  xml/System.Globalization/TextInfo.xml
  xml/System.Security.Cryptography/RNGCryptoServiceProvider.xml
  xml/System.Text/StringBuilder.xml
  xml/System/DateTime.xml
  xml/System/Decimal.xml
  xml/System/Delegate.xml
  xml/System/Exception.xml
  xml/System/IComparable.xml
  xml/System/StackOverflowException.xml
  xml/System/TimeSpan.xml
Labels: :woman_technologist: .NET Interactive

#4701 Automatic port of System.Threading.Interlocked exceptions
  xml/System.Threading/Interlocked.xml
Labels: new-content

#4671 Automatic port of System.Diagnostics.CodeAnalysis documentation
  xml/System.Diagnostics.CodeAnalysis/DynamicDependencyAttribute.xml
  xml/System.Diagnostics.CodeAnalysis/DynamicallyAccessedMemberTypes.xml
  xml/System.Diagnostics.CodeAnalysis/DynamicallyAccessedMembersAttribute.xml
  xml/System.Diagnostics.CodeAnalysis/MemberNotNullAttribute.xml
  xml/System.Diagnostics.CodeAnalysis/MemberNotNullWhenAttribute.xml
  xml/System.Diagnostics.CodeAnalysis/RequiresUnreferencedCodeAttribute.xml
  xml/System.Diagnostics.CodeAnalysis/UnconditionalSuppressMessageAttribute.xml
Labels: new-content

#4705 Automatically port System.Runtime.InteropServices documentation
  xml/System.Runtime.InteropServices/ComWrappers.xml
  xml/System.Runtime.InteropServices/DynamicInterfaceCastableImplementationAttribute.xml
  xml/System.Runtime.InteropServices/IDynamicInterfaceCastable.xml
  xml/System.Runtime.InteropServices/MemoryMarshal.xml
  xml/System.Runtime.InteropServices/UnmanagedCallersOnlyAttribute.xml
Labels: new-content

#4699 Automatic port of System.Globalization documentation
  xml/System.Globalization/CompareInfo.xml
  xml/System.Globalization/DateTimeFormatInfo.xml
Labels: new-content

#4703 Automatic port of System.Reflection documentation
  xml/System.Reflection.Metadata.Ecma335/ArrayShapeEncoder.xml
  xml/System.Reflection.Metadata.Ecma335/BlobEncoder.xml
  xml/System.Reflection.Metadata.Ecma335/CodedIndex.xml
  xml/System.Reflection.Metadata.Ecma335/ControlFlowBuilder.xml
  xml/System.Reflection.Metadata.Ecma335/CustomModifiersEncoder.xml
  xml/System.Reflection.Metadata.Ecma335/ExceptionRegionEncoder.xml
  xml/System.Reflection.Metadata.Ecma335/InstructionEncoder.xml
  xml/System.Reflection.Metadata.Ecma335/LiteralEncoder.xml
  xml/System.Reflection.Metadata.Ecma335/MetadataBuilder.xml
  xml/System.Reflection.Metadata.Ecma335/MetadataReaderExtensions.xml
  xml/System.Reflection.Metadata.Ecma335/MetadataRootBuilder.xml
  xml/System.Reflection.Metadata.Ecma335/MetadataTokens.xml
  xml/System.Reflection.Metadata.Ecma335/MethodBodyStreamEncoder.xml
  xml/System.Reflection.Metadata.Ecma335/MethodSignatureEncoder.xml
  xml/System.Reflection.Metadata.Ecma335/NamedArgumentsEncoder.xml
  xml/System.Reflection.Metadata.Ecma335/PortablePdbBuilder.xml
  xml/System.Reflection.Metadata.Ecma335/ScalarEncoder.xml
  xml/System.Reflection.Metadata.Ecma335/SignatureDecoder`2.xml
  xml/System.Reflection.Metadata.Ecma335/SignatureTypeEncoder.xml
  xml/System.Reflection/MethodInfo.xml
Labels: new-content

#4706 Automatically port System.Windows.Forms documentation
  xml/System.Windows.Forms/FileDialog.xml
  xml/System.Windows.Forms/ListView.xml
  xml/System.Windows.Forms/ListViewGroup.xml
  xml/System.Windows.Forms/ListViewGroupEventArgs.xml
  xml/System.Windows.Forms/TaskDialog.xml
  xml/System.Windows.Forms/TaskDialogButton.xml
  xml/System.Windows.Forms/TaskDialogButtonCollection.xml
  xml/System.Windows.Forms/TaskDialogCommandLinkButton.xml
  xml/System.Windows.Forms/TaskDialogControl.xml
  xml/System.Windows.Forms/TaskDialogExpander.xml
  xml/System.Windows.Forms/TaskDialogExpanderPosition.xml
  xml/System.Windows.Forms/TaskDialogFootnote.xml
  xml/System.Windows.Forms/TaskDialogIcon.xml
  xml/System.Windows.Forms/TaskDialogPage.xml
  xml/System.Windows.Forms/TaskDialogProgressBar.xml
  xml/System.Windows.Forms/TaskDialogProgressBarState.xml
  xml/System.Windows.Forms/TaskDialogRadioButton.xml
  xml/System.Windows.Forms/TaskDialogStartupLocation.xml
  xml/System.Windows.Forms/TaskDialogVerificationCheckBox.xml
Labels: new-content

#4726 Automatic port of System.Console documentation
  xml/System/Console.xml
Labels: new-content

#4729 Add missing documentation for System.Formats.Asn1
  xml/System.Formats.Asn1/AsnReader.xml
  xml/System.Formats.Asn1/AsnWriter+Scope.xml
  xml/System.Formats.Asn1/AsnWriter.xml
  xml/ns-System.Formats.Asn1.xml
Labels: new-content

#4751 Document System.Globalization.CultureInfo.GetCultureInfo
  xml/System.Globalization/CultureInfo.xml
Labels: new-content

#4696 CI Update - MSDN URL Update
  xml/System.ComponentModel.DataAnnotations/ValidationContext.xml
  xml/System.Diagnostics.Tracing/EventSource.xml
  xml/System.Speech.Synthesis.TtsEngine/FragmentState.xml
  xml/System.Windows.Automation.Peers/PasswordBoxAutomationPeer.xml
  xml/System.Windows.Automation.Peers/PatternInterface.xml
  xml/System.Windows.Automation.Peers/ProgressBarAutomationPeer.xml
  xml/System.Windows.Automation.Peers/RadioButtonAutomationPeer.xml
  xml/System.Windows.Automation.Peers/RangeBaseAutomationPeer.xml
  xml/System.Windows.Automation/AutomationFocusChangedEventArgs.xml
  xml/System.Windows.Automation/AutomationFocusChangedEventHandler.xml
  xml/System.Windows.Automation/AutomationPropertyChangedEventArgs.xml
  xml/System.Windows.Automation/AutomationPropertyChangedEventHandler.xml
  xml/System.Windows.Automation/CacheRequest.xml
  xml/System.Windows.Automation/ClientSettings.xml
  xml/System.Windows.Automation/ClientSideProviderDescription.xml
  xml/System.Windows.Automation/Condition.xml
  xml/System.Windows.Automation/ControlType.xml
  xml/System.Windows.Automation/DockPattern+DockPatternInformation.xml
  xml/System.Windows.Automation/DockPatternIdentifiers.xml
  xml/System.Windows.Automation/ExpandCollapsePattern+ExpandCollapsePatternInformation.xml
  xml/System.Windows.Automation/ExpandCollapsePatternIdentifiers.xml
  xml/System.Windows.Automation/GridItemPattern+GridItemPatternInformation.xml
  xml/System.Windows.Automation/GridItemPattern.xml
  xml/System.Windows.Automation/GridItemPatternIdentifiers.xml
  xml/System.Windows.Automation/GridPattern+GridPatternInformation.xml
  xml/System.Windows.Automation/GridPattern.xml
  xml/System.Windows.Automation/GridPatternIdentifiers.xml
  xml/System.Windows.Automation/InvokePattern.xml
  xml/System.Windows.Automation/InvokePatternIdentifiers.xml
  xml/System.Windows.Automation/MultipleViewPattern+MultipleViewPatternInformation.xml
  xml/System.Windows.Automation/MultipleViewPatternIdentifiers.xml
  xml/System.Windows.Automation/ProxyAssemblyNotLoadedException.xml
  xml/System.Windows.Automation/RangeValuePattern+RangeValuePatternInformation.xml
  xml/System.Windows.Automation/ScrollItemPatternIdentifiers.xml
  xml/System.Windows.Automation/ScrollPattern+ScrollPatternInformation.xml
  xml/System.Windows.Automation/ScrollPatternIdentifiers.xml
  xml/System.Windows.Automation/SelectionItemPattern+SelectionItemPatternInformation.xml
  xml/System.Windows.Automation/SelectionItemPatternIdentifiers.xml
  xml/System.Windows.Automation/SelectionPattern+SelectionPatternInformation.xml
  xml/System.Windows.Automation/SelectionPattern.xml
  xml/System.Windows.Automation/SelectionPatternIdentifiers.xml
  xml/System.Windows.Automation/StructureChangedEventArgs.xml
  xml/System.Windows.Automation/StructureChangedEventHandler.xml
  xml/System.Windows.Automation/SynchronizedInputPatternIdentifiers.xml
  xml/System.Windows.Automation/TableItemPattern+TableItemPatternInformation.xml
  xml/System.Windows.Automation/TableItemPattern.xml
  xml/System.Windows.Automation/TableItemPatternIdentifiers.xml
  xml/System.Windows.Automation/TablePattern+TablePatternInformation.xml
  xml/System.Windows.Automation/TablePattern.xml
  xml/System.Windows.Automation/TablePatternIdentifiers.xml
Labels: verify-build-before-merge
