Repository dotnet/dotnet-api-docs, pull requests merged in 2020-01, with the labels that each got.

#3728 Fix link in Remarks sections
  xml/System.Collections.Immutable/ImmutableSortedSet`1.xml
  xml/System.Composition.Hosting.Core/ExportDescriptorProvider.xml
  xml/System.Diagnostics/Activity.xml
  xml/System.Reflection.Metadata.Ecma335/MetadataBuilder.xml
  xml/System.Reflection/MetadataLoadContext.xml
  xml/System.Web.UI.MobileControls.Adapters/ControlAdapter.xml
  xml/System.Web.UI.MobileControls.Adapters/HtmlFormAdapter.xml
  xml/System.Web/SameSiteMode.xml
  xml/System.Windows.Forms/DataGridViewComboBoxCell.xml
  xml/System.Windows.Forms/DataGridViewTextBoxCell.xml
  xml/System/ReadOnlyMemory`1.xml
  xml/System/String.xml
Labels: verify-build-before-merge

#3703 Add missing documentation for Rfc3161TimestampRequest
  xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampRequest.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3684 Document System.IO.FileSystemAclExtensions
  xml/System.IO/FileSystemAclExtensions.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, waiting-on-reviews

#3690 Type.xml -- updating first page for Try .NET
  xml/System/Type.xml
Labels: vendor-project

#3755 Fix documentation
  xml/System.Threading/WaitHandle.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3743 Update docs for new Syndication APIs in 2.x
  xml/System.ServiceModel.Syndication/SyndicationFeed.xml
  xml/System.ServiceModel.Syndication/SyndicationFeedFormatter.xml
  xml/System.ServiceModel.Syndication/SyndicationTextInput.xml
  xml/System.ServiceModel.Syndication/TryParseDateTimeCallback.xml
  xml/System.ServiceModel.Syndication/TryParseUriCallback.xml
  xml/System.ServiceModel.Syndication/XmlDateTimeData.xml
  xml/System.ServiceModel.Syndication/XmlUriData.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content

#3747 Add missing API docs part 11 - SA
  xml/Microsoft.CLRAdmin/CData.xml
  xml/Microsoft.JScript.Vsa/VsaEngine.xml
  xml/Microsoft.VisualBasic.Vsa/VsaCompilerError.xml
Labels: vendor-project, verify-build-before-merge

#3757 fix some broken links
  xml/Microsoft.VisualBasic.Compatibility.VB6/ADODCArray.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/CheckBoxArray.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/CheckedListBoxArray.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/DriveListBoxArray.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/LabelArray.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/ListBoxArray.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/ListViewArray.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/MaskedTextBoxArray.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/MenuItemArray.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/PanelArray.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/PictureBoxArray.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/ProgressBarArray.xml
  xml/Microsoft.VisualBasic.Compatibility.VB6/RadioButtonArray.xml
  xml/Microsoft.VisualBasic.CompilerServices/ObjectType.xml
  xml/Microsoft.VisualBasic.CompilerServices/Operators.xml
  xml/Microsoft.VisualBasic.Devices/Ports.xml
  xml/System.Diagnostics/Activity.xml
  xml/System.Drawing.Printing/PrinterResolution.xml
  xml/System.Printing.Interop/PrintTicketConverter.xml
Labels: verify-build-before-merge

#3219 updating Random.xml for Try .NET
  xml/System/Random.xml
Labels: vendor-project, verify-build-before-merge

#3430 Try .Net updates -- HashSet`1.xml refresh for out-of-sync PR 3222
  xml/System.Collections.Generic/HashSet`1.xml
Labels: vendor-project, verify-build-before-merge

#3776 Update dead link
  xml/System.Security.Cryptography/Rijndael.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3731 Math.xml -- updating for Try .NET
  xml/System/Math.xml
Labels: vendor-project, verify-build-before-merge

#3773 String.xml -- Try .NET -- replacing out-of-sync PR 3458
  xml/System/String.xml
Labels: vendor-project

#3788 fix typo
  xml/System.Windows.Controls/ItemsControl.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3355 Update Docs for DateTime.Ticks to explain it depends on the time zone of the object instance.
  xml/System/DateTime.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, changes-addressed

#3784 update invalid link. repo moved.
  xml/System.Diagnostics/DiagnosticSource.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3789 Fix GZipStream.Flush summary and remarks
  xml/System.IO.Compression/GZipStream.xml
Labels: doc-enhancement

#3794 fix snippet references
  xml/System.Diagnostics/Process.xml
  xml/System.Diagnostics/ProcessStartInfo.xml
Labels: verify-build-before-merge

#3795 Automatically port System.Text.Json documentation
  xml/System.Text.Json/JsonSerializer.xml
Labels: new-content

#3793 Update Environment.xml
  xml/System/Environment.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3797 IntelliSense fixes
  xml/System.IO/Path.xml
  xml/System.Reflection.Metadata.Ecma335/SignatureTypeEncoder.xml
  xml/System.Security.Cryptography/DSACng.xml
  xml/System.Security.Cryptography/ECDiffieHellmanCng.xml
  xml/System.Threading.Channels/ChannelReader`1.xml
  xml/System.Windows.Controls/PasswordBox.xml
  xml/System.Windows.Controls/Slider.xml
  xml/System.Windows.Documents/AdornerDecorator.xml
  xml/System.Windows.Media.Animation/Storyboard.xml
  xml/System.Windows.Media/StreamGeometryContext.xml
  xml/System.Windows/Application.xml
  xml/System.Windows/Setter.xml
  xml/System/Convert.xml
Labels: migration-fixes

#3568 added missing info (Part 2)
  xml/Microsoft.Vsa.Vb.CodeDOM/CodeDOMProcessor.xml
  xml/Microsoft.Vsa.Vb.CodeDOM/Location.xml
  xml/Microsoft.Vsa.Vb.CodeDOM/_CodeDOMProcessor.xml
  xml/Microsoft.Vsa.Vb.CodeDOM/_Location.xml
  xml/Microsoft.Vsa/VsaException.xml
  xml/Microsoft.Vsa/VsaLoader.xml
  xml/Microsoft.Vsa/VsaModule.xml
  xml/Microsoft_VsaVb/VsaDTEngineClass.xml
  xml/Microsoft_VsaVb/VsaEngineClass.xml
  xml/System.Activities.Presentation.Expressions/CreateExpressionFromStringCallback.xml
  xml/System.Activities.XamlIntegration/DynamicUpdateMapExtension.xml
  xml/System.ComponentModel.Design.Serialization/CodeDomSerializer.xml
  xml/System.Data.Entity.Design/MetadataExtensionMethods.xml
  xml/System.Data/DataView.xml
  xml/System.Data/TypedTableBaseExtensions.xml
  xml/System.Data/TypedTableBase`1.xml
Labels: vendor-project, verify-build-before-merge

#3715 Added docs
  xml/Microsoft.Vsa.Vb.CodeDOM/Location.xml
  xml/Microsoft.Vsa.Vb.CodeDOM/_Location.xml
  xml/System.Data.Objects/CurrentValueRecord.xml
  xml/System.Data.OleDb/OleDbConnection.xml
  xml/System.Data.OleDb/OleDbPermission.xml
  xml/System.DirectoryServices/SearchWaitHandler.xml
Labels: vendor-project, verify-build-before-merge

#3268 Add note for differences on unix
  xml/System.IO/Path.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, doc-enhancement

#3335 Update HandleProcessCorruptedStateExceptionsAttribute docs
  xml/System.Runtime.ExceptionServices/HandleProcessCorruptedStateExceptionsAttribute.xml
Labels: verify-build-before-merge

#3740 Minor Update Object.xml - Fix phrase
  xml/System/Object.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3748 Update documentation for SerializationSurrogateProvider property
  xml/System.ServiceModel.Description/DataContractSerializerOperationBehavior.xml
Labels: :checkered_flag: Release: .NET Core 2.x, new-content, verify-build-before-merge, waiting-on-reviews

#3733 Update XElement.xml - correct/specify Attributes(XName) Summary and Returns description
  xml/System.Xml.Linq/XElement.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3716 Fixed remarks on limitations
  xml/System.Threading.Tasks/ValueTask`1.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3813 Missing Quotation in UrlsSection Example
  xml/System.Configuration/ConfigurationElementCollection.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3550 InitializesServerApplication required for calls to interface methods
  xml/System.EnterpriseServices/IProcessInitializer.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3823 IntelliSense fixes
  xml/System.Data.Common/DbParameter.xml
  xml/System.Text/Encoding.xml
  xml/System/Type.xml
Labels: migration-fixes

#3409 Fix FileSystemInfo.Attributes exceptions
  xml/System.IO/FileSystemInfo.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!, waiting-on-reviews

#3803 Add related articles to Memory and Span types
  xml/System/Memory`1.xml
  xml/System/ReadOnlyMemory`1.xml
  xml/System/ReadOnlySpan`1.xml
  xml/System/Span`1.xml
Labels: doc-enhancement

#3766 Make note on change from previous behavior
  xml/System/Double.xml
  xml/System/Single.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#3827 new content + fixes
  xml/Microsoft.Build.Tasks.Xaml/CommandLineGenerator.xml
  xml/Microsoft.JScript.Vsa/BaseVsaEngine.xml
  xml/Microsoft.JScript.Vsa/VsaEngine.xml
  xml/Microsoft.Vsa/BaseVsaEngine.xml
Labels: new-content, verify-build-before-merge
