Repository dotnet/dotnet-api-docs, pull requests merged in 2020-06, with the labels that each got.

#4255 .NET Interactive: Enable_try_dotnet_to_batch_8c
  xml/System/Char.xml
Labels: :woman_technologist: .NET Interactive

#4260 .NET Interactive: Enable_try_dotnet_to_batch_8d
  xml/System/Char.xml
Labels: :woman_technologist: .NET Interactive

#4301 Fix spelling of method
  xml/System.Buffers.Text/Utf8Formatter.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4245 Automatically port System.IO EII, FileSystemAclExtensions, CopyTo
  xml/System.IO.Enumeration/FileSystemEnumerable`1.xml
  xml/System.IO.Enumeration/FileSystemEnumerator`1.xml
  xml/System.IO.Log/LogExtentCollection.xml
  xml/System.IO.Log/ReservationCollection.xml
  xml/System.IO.Packaging/Package.xml
  xml/System.IO.Packaging/PackageRelationshipCollection.xml
  xml/System.IO/BinaryWriter.xml
  xml/System.IO/FileSystemAclExtensions.xml
  xml/System.IO/UnmanagedMemoryStream.xml
Labels: new-content

#4285 Automatically port 5.0 System.Runtime.CompilerServices documentation
  xml/System.Runtime.CompilerServices/RuntimeHelpers.xml
  xml/System.Runtime.CompilerServices/SkipLocalsInitAttribute.xml
Labels: :checkered_flag: Release: .NET 5, changes-addressed, new-content

#4316 Add documentation to XmlDocumentXPathExtensions
  xml/System.Xml/XmlDocumentXPathExtensions.xml
Labels: Release: .NET Core 1.x, new-content

#4321 Escaped backslash character on markdown syntax
  xml/System.IO/Path.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4306 NET Interactive: Enable_try_dotnet_to_batch_10a
  xml/System.Collections.Generic/List`1.xml
  xml/System.Collections.Generic/SortedDictionary`2.xml
  xml/System.Collections.Generic/SortedList`2.xml
  xml/System.Collections.Generic/Stack`1.xml
  xml/System/Activator.xml
  xml/System/Array.xml
  xml/System/Guid.xml
  xml/System/IFormatProvider.xml
Labels: :woman_technologist: .NET Interactive

#4341 HttpRequestException.StatusCode property and ctor
  xml/System.Net.Http/HttpRequestException.xml
Labels: :card_file_box: Technology - NCL

#4283 .NET Interactive: Enable_try_dotnet_to_batch_9
  xml/System.Security.Cryptography/Aes.xml
  xml/System.Security.Cryptography/AesCryptoServiceProvider.xml
  xml/System.Security.Cryptography/AesManaged.xml
  xml/System/Double.xml
Labels: :woman_technologist: .NET Interactive

#4383 Fix defaultCredentialsHandleCacheSize docs
  xml/System.Net.Configuration/WindowsAuthenticationElement.xml
Labels: :card_file_box: Technology - NCL

#4373 CookieCollection - update documentation
  xml/System.Net/CookieCollection.xml
Labels: :card_file_box: Technology - NCL

#4340 Different exceptions are thrown in case of timeout on different .NET platforms
  xml/System.Net.Http/HttpClient.xml
Labels: :card_file_box: Technology - NCL

#4335 NegotiateStream - update documentation
  samples/snippets/csharp/VS_Snippets_Remoting/NclNegoSyncClient/CS/client.cs
  xml/System.Net.Security/NegotiateStream.xml
Labels: :card_file_box: Technology - NCL

#4132 Migration fixes + minor fixes
  xml/System.Data.Objects.DataClasses/EntityCollection`1.xml
  xml/System.Globalization/PersianCalendar.xml
  xml/System.IO/BinaryWriter.xml
  xml/System.Net/WebHeaderCollection.xml
  xml/System.Resources/ResourceManager.xml
  xml/System.Resources/SatelliteContractVersionAttribute.xml
  xml/System.ServiceModel.Description/ServiceHealthModel+ProcessInformationModel.xml
  xml/System.Threading/WaitHandle.xml
  xml/System.Web.Configuration/OutputCacheProfile.xml
  xml/System.Windows.Automation/AutomationElement.xml
  xml/System.Windows.Media.Animation/AnimationTimeline.xml
  xml/System.Windows.Media.Animation/ByteAnimation.xml
  xml/System.Windows.Media.Animation/ColorAnimation.xml
  xml/System.Windows.Media.Animation/DecimalAnimation.xml
  xml/System.Windows.Media.Animation/DoubleAnimation.xml
  xml/System.Windows.Media.Animation/Int16Animation.xml
  xml/System.Windows.Media.Animation/Int32Animation.xml
  xml/System.Windows.Media.Animation/Int64Animation.xml
  xml/System.Windows.Media.Animation/Point3DAnimation.xml
  xml/System.Windows.Media.Animation/PointAnimation.xml
  xml/System.Windows.Media.Animation/QuaternionAnimation.xml
  xml/System.Windows.Media.Animation/RectAnimation.xml
  xml/System.Windows.Media.Animation/Rotation3DAnimation.xml
  xml/System.Windows.Media.Animation/SingleAnimation.xml
  xml/System.Windows.Media.Animation/SizeAnimation.xml
  xml/System.Windows.Media.Animation/ThicknessAnimation.xml
  xml/System.Windows.Media.Animation/Vector3DAnimation.xml
  xml/System.Windows.Media.Animation/VectorAnimation.xml
  xml/System.Windows.Media.Media3D/GeneralTransform3DCollection.xml
  xml/System.Windows.Media/DoubleCollection.xml
  xml/System.Windows.Media/Drawing.xml
  xml/System.Windows.Media/DrawingCollection.xml
  xml/System.Windows.Media/DrawingGroup.xml
  xml/System.Windows.Media/GradientStopCollection.xml
  xml/System.Windows.Media/ImageBrush.xml
  xml/System.Windows.Media/Int32Collection.xml
  xml/System.Windows.Media/LineGeometry.xml
  xml/System.Windows.Media/LineSegment.xml
  xml/System.Windows.Media/PathFigureCollection.xml
  xml/System.Windows.Media/PathSegment.xml
  xml/System.Windows.Media/PathSegmentCollection.xml
  xml/System.Windows.Media/PointCollection.xml
  xml/System.Windows.Media/QuadraticBezierSegment.xml
  xml/System.Windows.Media/RadialGradientBrush.xml
  xml/System.Windows.Media/RotateTransform.xml
  xml/System.Windows.Media/ScaleTransform.xml
  xml/System.Windows.Media/SkewTransform.xml
  xml/System.Windows.Media/SolidColorBrush.xml
  xml/System.Windows.Media/TransformCollection.xml
  xml/System.Windows.Media/TransformGroup.xml
  xml/System.Windows.Media/TranslateTransform.xml
  xml/System.Windows.Media/VectorCollection.xml
  xml/System/Int32.xml
Labels: verify-build-before-merge

#4408 fix sample code
  samples/snippets/csharp/VS_Snippets_CLR_System/system.invalidoperationexception/cs/List_Sort2.cs
  samples/snippets/visualbasic/VS_Snippets_CLR_System/system.invalidoperationexception/vb/List_Sort2.vb
Labels: verify-build-before-merge

#4156 Fix misleading wording in PipeReader and PipeWriter's AsStream documentation.
  xml/System.IO.Pipelines/PipeReader.xml
  xml/System.IO.Pipelines/PipeWriter.xml
Labels: doc-bug

#4447 Fix typo "charter" => "character"
  xml/System/IntPtr.xml
Labels: :sparkles: 1st-time dotnet-api-docs contributor!

#4343 .NET Interactive: Enable_try_dotnet_to_batch_10b
  xml/System.Collections.Generic/Dictionary`2.xml
  xml/System.Collections.Generic/List`1.xml
  xml/System.Collections.Generic/Queue`1.xml
  xml/System/Enum.xml
  xml/System/Exception.xml
  xml/System/Object.xml
  xml/System/Random.xml
  xml/System/String.xml
  xml/System/Type.xml
Labels: :woman_technologist: .NET Interactive, verify-build-before-merge

#4374 .NET Interactive: Enable_try_dotnet_to_batch_11c
  xml/System/DateTime.xml
  xml/System/Enum.xml
  xml/System/Exception.xml
  xml/System/FlagsAttribute.xml
  xml/System/Predicate`1.xml
Labels: :woman_technologist: .NET Interactive

#4395 .NET Interactive: Enable_try_dotnet_to_batch_12a
  xml/System.Globalization/CultureInfo.xml
  xml/System.Text/Encoding.xml
  xml/System/Environment.xml
  xml/System/Func`1.xml
  xml/System/Type.xml
Labels: :woman_technologist: .NET Interactive

#4404 .NET Interactive: Enable_try_dotnet_to_batch_12b
  xml/System/Array.xml
  xml/System/BitConverter.xml
  xml/System/Byte.xml
  xml/System/DayOfWeek.xml
  xml/System/Environment.xml
Labels: :woman_technologist: .NET Interactive

#4412 .NET Interactive: Enable_try_dotnet_to_batch_12c
  xml/System/Array.xml
  xml/System/DateTime.xml
  xml/System/Exception.xml
  xml/System/TimeSpan.xml
  xml/System/Tuple.xml
Labels: :woman_technologist: .NET Interactive
