Repository dotnet/dotnet-api-docs, pull requests merged in 2023-02, with the labels that each got.

#8830 Fix the remarks for the inequality operator
  xml/System/Span`1.xml
Labels: area-System.Runtime, community-contribution

#8832 Fix grammatical error
  xml/Microsoft.Extensions.Logging/ILogger.xml
Labels: area-Extensions-Logging, community-contribution

#8834 Update locate projects net7
  .github/workflows/dependencies/DotnetDocsTools.LocateProjects.1.0.10.nupkg
  .github/workflows/dependencies/DotnetDocsTools.LocateProjects.2.0.0.nupkg
Labels: area-Infrastructure

#8839 Fix: Parameter name changed for better readibility
  snippets/csharp/System.IO/Directory/GetAccessControl/sample.cs
Labels: area-System.IO, community-contribution

#8838 Fix ref struct documentation link for Span<T>
  xml/System/Span`1.xml
Labels: area-System.Runtime, community-contribution

#8843 Update Rune samples project to net6.0
  snippets/csharp/System.Text/Rune/Overview/RuneSamples.csproj
Labels: area-Meta

#8842 Allow ConcurrentDictionary concurrencyLevel == -1 in .NET 8+
  xml/System.Collections.Concurrent/ConcurrentDictionary`2.xml
Labels: area-System.Collections

#8836 Updated Enumerable.Skip<TSource> example for C# and VB
  snippets/csharp/System.Linq/Enumerable/AggregateTSource/enumerable.cs
  snippets/visualbasic/VS_Snippets_CLR_System/system.Linq.Enumerable/VB/Enumerable.vb
  xml/System.Linq/Enumerable.xml
Labels: area-System.Linq, community-contribution

#8845 Add link to conceptual doc
  xml/System.Runtime.ExceptionServices/ExceptionDispatchInfo.xml
Labels: area-System.Runtime

#8846 Remove link to self
  xml/System.Xml.Serialization/XmlAttributes.xml
  xml/System.Xml.Serialization/XmlSerializer.xml
Labels: area-Serialization

#8853 System.Collections.Concurrent.BlockingCollection<T> F# snippets
  snippets/fsharp/System.Collections.Concurrent/BlockingCollectionT/Overview/blockingcoll.fs
  snippets/fsharp/System.Collections.Concurrent/BlockingCollectionT/Overview/fs.fsproj
  xml/System.Collections.Concurrent/BlockingCollection`1.xml
Labels: community-contribution

#8854 System.Collections.Concurrent.ConcurrentBag<T> F# snippet
  snippets/fsharp/System.Collections.Concurrent/ConcurrentBag/concbag.fs
  snippets/fsharp/System.Collections.Concurrent/ConcurrentBag/fs.fsproj
  xml/System.Collections.Concurrent/ConcurrentBag`1.xml
Labels: community-contribution

#8856 System.Collections.Concurrent.ConcurrentQueue<T> F# snippet
  snippets/fsharp/System.Collections.Concurrent/ConcurrentQueueT/Overview/concqueue.fs
  snippets/fsharp/System.Collections.Concurrent/ConcurrentQueueT/Overview/fs.fsproj
  xml/System.Collections.Concurrent/ConcurrentQueue`1.xml
Labels: community-contribution

#8857 System.Collections.Concurrent.ConcurrentStack<T> F# snippets
  snippets/fsharp/System.Collections.Concurrent/ConcurrentStackT/Overview/concstack_range.fs
  snippets/fsharp/System.Collections.Concurrent/ConcurrentStackT/Overview/concstack_single.fs
  snippets/fsharp/System.Collections.Concurrent/ConcurrentStackT/Overview/fs.fsproj
  xml/System.Collections.Concurrent/ConcurrentStack`1.xml
Labels: community-contribution

#8855 System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue> F# snippets
  snippets/fsharp/System.Collections.Concurrent/ConcurrentDictionaryTKey,TValue/AddOrUpdate/fs.fsproj
  snippets/fsharp/System.Collections.Concurrent/ConcurrentDictionaryTKey,TValue/AddOrUpdate/program.fs
  snippets/fsharp/System.Collections.Concurrent/ConcurrentDictionaryTKey,TValue/Overview/concdictionary.fs
  snippets/fsharp/System.Collections.Concurrent/ConcurrentDictionaryTKey,TValue/Overview/fs.fsproj
  xml/System.Collections.Concurrent/ConcurrentDictionary`2.xml
Labels: community-contribution

#8861 System.Timers F# snippets
  snippets/fsharp/System.Timers/ElapsedEventArgs/Overview/AsyncHandlerEx1.fs
  snippets/fsharp/System.Timers/ElapsedEventArgs/Overview/fs.fsproj
  snippets/fsharp/System.Timers/ElapsedEventArgs/Overview/timer1.fs
  snippets/fsharp/System.Timers/ElapsedEventArgs/Overview/timer2a.fs
  snippets/fsharp/System.Timers/ElapsedEventHandler/Overview/fs.fsproj
  snippets/fsharp/System.Timers/ElapsedEventHandler/Overview/source.fs
  snippets/fsharp/System.Timers/Timer/AutoReset/fs.fsproj
  snippets/fsharp/System.Timers/Timer/AutoReset/source.fs
  snippets/fsharp/System.Timers/Timer/Interval/fs.fsproj
  snippets/fsharp/System.Timers/Timer/Interval/interval2.fs
  snippets/fsharp/System.Timers/Timer/Stop/fs.fsproj
  snippets/fsharp/System.Timers/Timer/Stop/source.fs
  xml/System.Timers/ElapsedEventArgs.xml
  xml/System.Timers/ElapsedEventHandler.xml
  xml/System.Timers/Timer.xml
Labels: community-contribution

#8866 System.Text.StringBuilder F# snippets
  snippets/fsharp/System.Text/StringBuilder/.ctor/constructors.fs
  snippets/fsharp/System.Text/StringBuilder/.ctor/fs.fsproj
  snippets/fsharp/System.Text/StringBuilder/Append/append2.fs
  snippets/fsharp/System.Text/StringBuilder/Append/append3.fs
  snippets/fsharp/System.Text/StringBuilder/Append/append4.fs
  snippets/fsharp/System.Text/StringBuilder/Append/fs.fsproj
  snippets/fsharp/System.Text/StringBuilder/AppendFormat/appendformat1.fs
  snippets/fsharp/System.Text/StringBuilder/AppendFormat/appendformat2.fs
  snippets/fsharp/System.Text/StringBuilder/AppendFormat/appendformat3.fs
  snippets/fsharp/System.Text/StringBuilder/AppendFormat/appfmt.fs
  snippets/fsharp/System.Text/StringBuilder/AppendFormat/customernumberformatter1.fs
  snippets/fsharp/System.Text/StringBuilder/AppendFormat/fs.fsproj
  snippets/fsharp/System.Text/StringBuilder/AppendLine/al.fs
  snippets/fsharp/System.Text/StringBuilder/AppendLine/fs.fsproj
  snippets/fsharp/System.Text/StringBuilder/Capacity/cap.fs
  snippets/fsharp/System.Text/StringBuilder/Capacity/fs.fsproj
  snippets/fsharp/System.Text/StringBuilder/Chars/chars1.fs
  snippets/fsharp/System.Text/StringBuilder/Chars/fs.fsproj
  snippets/fsharp/System.Text/StringBuilder/Clear/clear1.fs
  snippets/fsharp/System.Text/StringBuilder/Clear/fs.fsproj
  snippets/fsharp/System.Text/StringBuilder/CopyTo/ct2.fs
  snippets/fsharp/System.Text/StringBuilder/CopyTo/fs.fsproj
  snippets/fsharp/System.Text/StringBuilder/Insert/fs.fsproj
  snippets/fsharp/System.Text/StringBuilder/Insert/insert.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/StringBuilder.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/call1.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/call2.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/chars1.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/default1.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/delete1.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/expand1.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/fs.fsproj
  snippets/fsharp/System.Text/StringBuilder/Overview/immutability2.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/instantiate1.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/pattern1.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/pattern2.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/pattern3.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/pattern4.fs
  snippets/fsharp/System.Text/StringBuilder/Overview/replace1.fs
  snippets/fsharp/System.Text/StringBuilder/Remove/fs.fsproj
  snippets/fsharp/System.Text/StringBuilder/Remove/remove.fs
  snippets/fsharp/System.Text/StringBuilder/Replace/fs.fsproj
  snippets/fsharp/System.Text/StringBuilder/Replace/replace.fs
  xml/System.Text/StringBuilder.xml
Labels: community-contribution

#8871 System.Collections.Generic.Queue<T> F# snippet
  snippets/fsharp/System.Collections.Generic/QueueT/Overview/fs.fsproj
  snippets/fsharp/System.Collections.Generic/QueueT/Overview/source.fs
  xml/System.Collections.Generic/Queue`1.xml
Labels: community-contribution

#8872 System.Collections.Generic.Stack<T> F# snippet
  snippets/fsharp/System.Collections.Generic/StackT/Overview/fs.fsproj
  snippets/fsharp/System.Collections.Generic/StackT/Overview/source.fs
  xml/System.Collections.Generic/Stack`1.xml
Labels: community-contribution

#8873 System.IO.FileStream F# snippets
  snippets/fsharp/System.IO/FileOptions/Overview/example.fs
  snippets/fsharp/System.IO/FileOptions/Overview/fs.fsproj
  snippets/fsharp/System.IO/FileStream/.ctor/example.fs
  snippets/fsharp/System.IO/FileStream/.ctor/fs.fsproj
  snippets/fsharp/System.IO/FileStream/.ctor/fstreamlock.fs
  snippets/fsharp/System.IO/FileStream/.ctor/source.fs
  snippets/fsharp/System.IO/FileStream/.ctor/source1.fs
  snippets/fsharp/System.IO/FileStream/CanRead/fs.fsproj
  snippets/fsharp/System.IO/FileStream/CanRead/source.fs
  snippets/fsharp/System.IO/FileStream/CanSeek/fs.fsproj
  snippets/fsharp/System.IO/FileStream/CanSeek/fstream canseek.fs
  snippets/fsharp/System.IO/FileStream/CanWrite/fs.fsproj
  snippets/fsharp/System.IO/FileStream/CanWrite/fstream canwrite.fs
  snippets/fsharp/System.IO/FileStream/CanWrite/source.fs
  snippets/fsharp/System.IO/FileStream/Length/fs.fsproj
  snippets/fsharp/System.IO/FileStream/Length/source.fs
  snippets/fsharp/System.IO/FileStream/Overview/example4.fs
  snippets/fsharp/System.IO/FileStream/Overview/fs.fsproj
  snippets/fsharp/System.IO/FileStream/Overview/fstream class.fs
  snippets/fsharp/System.IO/FileStream/Read/fs.fsproj
  snippets/fsharp/System.IO/FileStream/Read/fsread.fs
  snippets/fsharp/System.IO/FileStream/Seek/fs.fsproj
  snippets/fsharp/System.IO/FileStream/Seek/source.fs
  xml/System.IO/FileStream.xml
Labels: community-contribution

#8877 fix: Exception description of TrimExcess(Int32)
  xml/System.Collections.Generic/Dictionary`2.xml
Labels: area-System.Collections, community-contribution
