Repository dotnet/dotnet-api-docs, pull requests merged in 2025-10, with the labels that each got.

#11891 Fix typo in Type.GetMethod remarks section
  xml/System/Type.xml
Labels: community-contribution, needs-area-label

#11881 Random exception fixes
  xml/System.IO.Log/LogExtentCollection.xml
  xml/System.IO.Log/LogStore.xml
  xml/System.IO.Log/ReservationCollection.xml
  xml/System.IO/DirectoryInfo.xml
Labels: area-System.IO

#11758 Try to fix output display
  snippets/csharp/System.Xml/XmlDocument/CreateElement/project.csproj
  snippets/csharp/System.Xml/XmlDocument/CreateElement/source.cs
  snippets/csharp/System.Xml/XmlDocument/CreateElement/source1.cs
  snippets/visualbasic/VS_Snippets_Data/Classic WebData XmlDocument.CreateElement Example/VB/project.vbproj
  snippets/visualbasic/VS_Snippets_Data/Classic WebData XmlDocument.CreateElement Example/VB/source.vb
  xml/System.Xml/XmlDocument.xml
Labels: area-Infrastructure
